//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { RegistrationFamilyBag } from "@Obsidian/ViewModels/CheckIn/registrationFamilyBag";
import { RegistrationPersonBag } from "@Obsidian/ViewModels/CheckIn/registrationPersonBag";
import { ValidPropertiesBox } from "@Obsidian/ViewModels/Utility/validPropertiesBox";

/** The options to provide to the SaveFamily block action. */
export type SaveFamilyOptionsBag = {
    /** The details of the family that should be updated. */
    family?: ValidPropertiesBox<RegistrationFamilyBag> | null;

    /** The encrypted identifier of the kiosk performing the operation. */
    kioskId?: string | null;

    /**
     * The details of the various people in the family that should be
     * updated. This will contain both family members and those associated
     * by a relationship.
     */
    people?: ValidPropertiesBox<RegistrationPersonBag>[] | null;

    /** The encrypted identifiers of the people to remove from the family. */
    removedPersonIds?: string[] | null;

    /** The encrypted identifier of the check-in template configuration. */
    templateId?: string | null;
};
