//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** The Push Open Action used by the Communication Entry block. */
export const PushOpenActionType = {
    /** No action */
    NoAction: 0,

    /** Show details */
    ShowDetails: 1,

    /** Link to mobile page */
    LinkToMobilePage: 2,

    /** Link to URL */
    LinkToUrl: 3
} as const;

/** The Push Open Action used by the Communication Entry block. */
export const PushOpenActionTypeDescription: Record<number, string> = {
    0: "No Action",

    1: "Show Details",

    2: "Link To Mobile Page",

    3: "Link To Url"
};

/** The Push Open Action used by the Communication Entry block. */
export type PushOpenActionType = typeof PushOpenActionType[keyof typeof PushOpenActionType];
