// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
namespace Rock.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    /// <summary>
    ///
    /// </summary>
    public partial class UpdateMissingEntities : Rock.Migrations.RockMigration
    {
        /// <summary>
        /// Operations to be performed during the upgrade process.
        /// </summary>
        public override void Up()
        {
            // migration rollup of EntityTypes
            RockMigrationHelper.UpdateEntityType( "Rock.Address.Bing", "Bing", "Rock.Address.Bing, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F9090BDE-83EB-4D93-B5D6-19016A830E2D" );
            RockMigrationHelper.UpdateEntityType( "Rock.Address.MelissaData", "Melissa Data", "Rock.Address.MelissaData, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "25590809-DFEA-42B4-B556-67E311AC331A" );
            RockMigrationHelper.UpdateEntityType( "Rock.Address.ServiceObjects", "Service Objects", "Rock.Address.ServiceObjects, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "FDBE662A-51F8-436B-ACEC-890EE4CDE124" );
            RockMigrationHelper.UpdateEntityType( "Rock.Address.SmartyStreets", "Smarty Streets", "Rock.Address.SmartyStreets, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "4278E7EF-221B-45E6-B9C6-5D11884389EF" );
            RockMigrationHelper.UpdateEntityType( "Rock.Communication.Transport.MailgunSmtp", "Mailgun Smtp", "Rock.Communication.Transport.MailgunSmtp, Rock.Mailgun, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "40229185-BF3F-4428-8F98-0EC37EDD3BE2" );
            RockMigrationHelper.UpdateEntityType( "Rock.Communication.Transport.MandrillSmtp", "Mandrill Smtp", "Rock.Communication.Transport.MandrillSmtp, Rock.Mandrill, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "73158C6E-CE56-4CA8-9A52-7CBA58CA52F9" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.AuditDetail", "Audit Detail", "Rock.Model.AuditDetail, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, false, "00A4323F-4A05-4E6A-8480-35D8B7BB6615" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.BackgroundCheck", "Background Check", "Rock.Model.BackgroundCheck, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "6D3A2293-BA7E-44D9-B5B3-5B85DA0EECAC" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.BenevolenceRequestDocument", "Benevolence Request Document", "Rock.Model.BenevolenceRequestDocument, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "3D627F51-E262-454B-95A0-2EF97103BCE1" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.BenevolenceResult", "Benevolence Result", "Rock.Model.BenevolenceResult, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "A4929A2D-5B83-4535-A1D4-8A2C84FBA581" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.CommunicationRecipientActivity", "Communication Recipient Activity", "Rock.Model.CommunicationRecipientActivity, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "D3537CF4-658A-4F2C-A04F-FCF58185457E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.CommunicationTemplate", "Communication Template", "Rock.Model.CommunicationTemplate, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "A9493AFE-4316-4651-800D-5028E4C7444D" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.ConnectionOpportunityConnectorGroup", "Connection Opportunity Connector Group", "Rock.Model.ConnectionOpportunityConnectorGroup, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "2ADBE499-C9EC-479B-B33B-6E92BDE09FD1" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.ConnectionOpportunityGroupConfig", "Connection Opportunity Group Config", "Rock.Model.ConnectionOpportunityGroupConfig, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "59756122-B779-4A4E-9CE7-6A4468AA9524" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.ContentChannelItemAssociation", "Content Channel Item Association", "Rock.Model.ContentChannelItemAssociation, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "7C86EED3-C3F9-4B25-887B-F732FE3C35F0" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.ContentChannelType", "Content Channel Type", "Rock.Model.ContentChannelType, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "D5992F79-7FB8-49FF-82AB-E8CB2CEC1E74" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EntitySet", "Entity Set", "Rock.Model.EntitySet, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "50E3F9C8-4010-41AF-8F61-08308DC44640" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EntitySetItem", "Entity Set Item", "Rock.Model.EntitySetItem, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "1F9D13F9-BF55-48BE-BEA9-0939CD6FDA5B" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EventCalendar", "Event Calendar", "Rock.Model.EventCalendar, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "E67D8D6D-4FE6-48D5-A940-A39213047314" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EventCalendarContentChannel", "Event Calendar Content Channel", "Rock.Model.EventCalendarContentChannel, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "B8631058-DAC3-4164-9A50-9E732B0C3882" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EventCalendarItem", "Event Calendar Item", "Rock.Model.EventCalendarItem, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "E37FB26F-03F6-48DA-8E96-F412616F5EE4" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EventItemAudience", "Event Item Audience", "Rock.Model.EventItemAudience, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "22394315-E21B-40AF-AFDA-75D9F5DAD721" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EventItemOccurrence", "Event Item Occurrence", "Rock.Model.EventItemOccurrence, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "71632E1A-1E7F-42B9-A630-EC99F375303A" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EventItemOccurrenceChannelItem", "Event Item Occurrence Channel Item", "Rock.Model.EventItemOccurrenceChannelItem, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "378A9559-BD86-45A8-B218-2C5D4CF3D770" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.EventItemOccurrenceGroupMap", "Event Item Occurrence Group Map", "Rock.Model.EventItemOccurrenceGroupMap, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "1479D2B7-65C0-4E98-9E70-0848422FA00C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.FinancialPaymentDetail", "Financial Payment Detail", "Rock.Model.FinancialPaymentDetail, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "F3659077-43FD-4805-BC42-BC8A3F9C3008" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.Following", "Following", "Rock.Model.Following, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "D9AD7A30-92F2-467B-A3F9-37CA246F90BD" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.FollowingEventNotification", "Following Event Notification", "Rock.Model.FollowingEventNotification, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "21BA6002-1FB0-45C7-BCA6-D6629EC8AB52" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.FollowingEventSubscription", "Following Event Subscription", "Rock.Model.FollowingEventSubscription, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "2EEA3DF1-1FBE-472C-85AF-6D952DFC4684" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.FollowingSuggested", "Following Suggested", "Rock.Model.FollowingSuggested, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "EC14B80A-3776-4134-884D-031A89C0EF03" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.GroupMemberRequirement", "Group Member Requirement", "Rock.Model.GroupMemberRequirement, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "FF1B2C4B-0F2D-4D9B-9E85-7336CCC24A62" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.GroupMemberWorkflowTrigger", "Group Member Workflow Trigger", "Rock.Model.GroupMemberWorkflowTrigger, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, false, "3CE3406A-1FFE-4CCA-A8D5-916EEF800D76" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.GroupRequirement", "Group Requirement", "Rock.Model.GroupRequirement, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "CFC7DE86-222E-4669-83C2-A3F5B04CB5D6" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.GroupRequirementType", "Group Requirement Type", "Rock.Model.GroupRequirementType, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "8E67E852-D1BF-485C-9898-09F19998CC40" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.GroupScheduleExclusion", "Group Schedule Exclusion", "Rock.Model.GroupScheduleExclusion, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "047D57EE-1B06-455F-86EA-D96B8325C77D" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.MetricPartition", "Metric Partition", "Rock.Model.MetricPartition, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "82ED733F-BAD8-4D8D-BCB7-10A6433F452A" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.MetricValuePartition", "Metric Value Partition", "Rock.Model.MetricValuePartition, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "FEC12664-C5F2-44E1-9805-1137068AC755" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.Notification", "Notification", "Rock.Model.Notification, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "6DB6D280-9740-41FD-B8BD-0AA29E12F4B6" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.NotificationRecipient", "Notification Recipient", "Rock.Model.NotificationRecipient, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "2ECE2776-0FE2-429D-B655-AB56A2D6EE0B" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.PageView", "Page View", "Rock.Model.PageView, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, false, "F10A1BAD-7950-46E2-B066-24D4F2857E44" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.PageViewSession", "Page View Session", "Rock.Model.PageViewSession, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, false, "D76045A3-1A0A-40FD-8850-145EFA03E92E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.PageViewUserAgent", "Page View User Agent", "Rock.Model.PageViewUserAgent, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, false, "C7D5C1E7-AC1F-4588-8D20-9320B447E7FA" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.PersonDuplicate", "Person Duplicate", "Rock.Model.PersonDuplicate, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "20B2B2B6-38C3-4302-9200-63DD4C78687B" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.PersonPreviousName", "Person Previous Name", "Rock.Model.PersonPreviousName, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "80AC80E1-F769-4E34-9937-E2FEEF2B60EE" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.PluginMigration", "Plugin Migration", "Rock.Model.PluginMigration, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "F239557E-C7A8-4D1F-82CC-55CDD0ACA3C8" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.RegistrationRegistrant", "Registration Registrant", "Rock.Model.RegistrationRegistrant, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "8A25E5CE-1B4F-4825-BCEA-216167836305" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.RegistrationRegistrantFee", "Registration Registrant Fee", "Rock.Model.RegistrationRegistrantFee, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "AB66F63A-3E79-438F-8C52-C9A8C70A0511" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.RegistrationTemplateDiscount", "Registration Template Discount", "Rock.Model.RegistrationTemplateDiscount, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "88D94ECB-FCEE-4A00-ACB9-FF90BDBA7A17" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.RegistrationTemplateFee", "Registration Template Fee", "Rock.Model.RegistrationTemplateFee, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "2DB3A441-6CA1-49D1-BB25-C744E2FFA457" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.RegistrationTemplateForm", "Registration Template Form", "Rock.Model.RegistrationTemplateForm, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "2F0B3A6A-4E47-45A8-A331-7234CE711356" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.RegistrationTemplateFormField", "Registration Template Form Field", "Rock.Model.RegistrationTemplateFormField, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "A773CAA2-2211-416B-BDD7-D907085B4441" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.SignatureDocument", "Signature Document", "Rock.Model.SignatureDocument, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "C1724719-1C03-4D0C-8A66-E3545138F57F" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.SignatureDocumentTemplate", "Signature Document Template", "Rock.Model.SignatureDocumentTemplate, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "3F9828CC-8224-4AB0-98A5-6D60001EBE32" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.UserLoginWithPlainTextPassword", "User Login With Plain Text Password", "Rock.Model.UserLoginWithPlainTextPassword, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "4DF3BA27-E6CD-4E6D-A5E4-E1617DD83185" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.WorkflowActionForm", "Workflow Action Form", "Rock.Model.WorkflowActionForm, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "FDAB9AEB-B2AA-4FB5-A35D-83254A9B014C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Model.WorkflowActionFormAttribute", "Workflow Action Form Attribute", "Rock.Model.WorkflowActionFormAttribute, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "E147611F-D1AB-4C34-A1F8-84A118BAFDE3" );
            RockMigrationHelper.UpdateEntityType( "Rock.PersonProfile.AlertNote.AlertNote", "Alert Note", "Rock.PersonProfile.AlertNote.AlertNote, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "139E9BD6-2159-49F0-B8C8-29C7E251BE50" );
            RockMigrationHelper.UpdateEntityType( "Rock.PersonProfile.Badge.GeofencedByGroup", "Geofenced By Group", "Rock.PersonProfile.Badge.GeofencedByGroup, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "CD6477C8-F567-4313-980E-CC63D46EAE84" );
            RockMigrationHelper.UpdateEntityType( "Rock.PersonProfile.Badge.InGroupWithPurpose", "In Group With Purpose", "Rock.PersonProfile.Badge.InGroupWithPurpose, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "1844AC11-7117-4C91-8D82-A6340D50323E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.ContentChannelItem.ContentChannel", "Content Channel", "Rock.Reporting.DataFilter.ContentChannelItem.ContentChannel, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "E469CB19-C22E-4811-9779-49C797A0E528" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.ContentChannelItem.ContentChannelItemAttributesFilter", "Content Channel Item Attributes Filter", "Rock.Reporting.DataFilter.ContentChannelItem.ContentChannelItemAttributesFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "DE53F3DE-B1D7-45D3-89C5-C9D3513DDEEE" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.ContentChannelItem.ContentChannelType", "Content Channel Type", "Rock.Reporting.DataFilter.ContentChannelItem.ContentChannelType, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "6FF3488F-9AAE-484E-A4CC-D3B3D3A2C4A6" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.FinancialPledge.AccountFilter", "Account Filter", "Rock.Reporting.DataFilter.FinancialPledge.AccountFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "1559B401-BF31-4E58-BAC0-53C2DB7DE49F" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.FinancialTransaction.TotalAmountFilter", "Total Amount Filter", "Rock.Reporting.DataFilter.FinancialTransaction.TotalAmountFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "356D67D8-2D00-4C7F-921D-95DD78769B39" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.FinancialTransactionDetail.AccountFilter", "Account Filter", "Rock.Reporting.DataFilter.FinancialTransactionDetail.AccountFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "3BE224DE-B630-44BC-A7A6-32B8A7FA459E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.CampusFilter", "Campus Filter", "Rock.Reporting.DataFilter.Group.CampusFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "32AEA2DF-2374-478D-865E-D1B6FB2E06D0" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.ContainsGroupMembersFilter", "Contains Group Members Filter", "Rock.Reporting.DataFilter.Group.ContainsGroupMembersFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F9EA71FD-81F0-4C30-9A4E-4B870F8C8573" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.ContainsPeopleFilter", "Contains People Filter", "Rock.Reporting.DataFilter.Group.ContainsPeopleFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "79E9FE53-3BAD-4935-B8AE-BC412615F057" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.DistanceFromFilter", "Distance From Filter", "Rock.Reporting.DataFilter.Group.DistanceFromFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "C3D102D5-2678-468F-8A6C-2118D94F43E8" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.GroupAttributesFilter", "Group Attributes Filter", "Rock.Reporting.DataFilter.Group.GroupAttributesFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "0F4D0B55-EC26-43D5-91CE-D7162ABCDCE6" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.GroupBranchFilter", "Group Branch Filter", "Rock.Reporting.DataFilter.Group.GroupBranchFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "A1D53B49-EDB6-4644-BA31-93C0F2E22368" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.GroupTypeFilter", "Group Type Filter", "Rock.Reporting.DataFilter.Group.GroupTypeFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "6880CE3A-366B-4D21-8CAC-DEC7D18173C3" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.MemberCountFilter", "Member Count Filter", "Rock.Reporting.DataFilter.Group.MemberCountFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "9972788B-5947-4EE1-AEBD-C9D861D94F02" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Group.SimpleMemberCountFilter", "Simple Member Count Filter", "Rock.Reporting.DataFilter.Group.SimpleMemberCountFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "27E521A3-9F5C-424E-8AED-43A228B1702F" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.GroupMember.GroupDataViewFilter", "Group Data View Filter", "Rock.Reporting.DataFilter.GroupMember.GroupDataViewFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "FE44A344-DED1-4E93-8C74-1820E6313322" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.GroupMember.GroupMemberAttributesFilter", "Group Member Attributes Filter", "Rock.Reporting.DataFilter.GroupMember.GroupMemberAttributesFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "5ABED6E0-BD45-455A-B28C-72F5648A28AD" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.GroupMembers.ContainsPeopleFilter", "Contains People Filter", "Rock.Reporting.DataFilter.GroupMembers.ContainsPeopleFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "7C59C380-A99B-4D6F-9BBE-5C2A6CC37593" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.NotInOtherDataViewFilter", "Not In Other Data View Filter", "Rock.Reporting.DataFilter.NotInOtherDataViewFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "CEEEE67D-DF8E-4D99-9E39-A410DF7A2680" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.CampusesFilter", "Campuses Filter", "Rock.Reporting.DataFilter.Person.CampusesFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "D3B4BF7D-7F03-4F42-8411-A6CBDD1675B6" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.CampusFilter", "Campus Filter", "Rock.Reporting.DataFilter.Person.CampusFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "D976C41F-226F-4051-9CA3-C661C938B064" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.DistanceFromFilter", "Distance From Filter", "Rock.Reporting.DataFilter.Person.DistanceFromFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "0B08B4E8-5C3D-479A-A53A-0889189413AC" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.FirstContributionDateFilter", "First Contribution Date Filter", "Rock.Reporting.DataFilter.Person.FirstContributionDateFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "B4B70487-E620-4BC1-8983-124578118BC0" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.GivingAmountFilter", "Giving Amount Filter", "Rock.Reporting.DataFilter.Person.GivingAmountFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "1087DEE3-9932-4647-88A3-7CD87AB16B7D" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.GradeFilter", "Grade Filter", "Rock.Reporting.DataFilter.Person.GradeFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "7311CCCF-BBFB-4FF7-AFD0-3D7F2D466C1B" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.GroupAttendanceFilter", "Group Attendance Filter", "Rock.Reporting.DataFilter.Person.GroupAttendanceFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "E69E1FD7-0E03-42A5-A2EB-90C8812CFD47" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.GroupDataViewFilter", "Group Data View Filter", "Rock.Reporting.DataFilter.Person.GroupDataViewFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "09D0169F-BA45-4827-AD92-455E1B05B9F2" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.GroupMemberDataViewFilter", "Group Member Data View Filter", "Rock.Reporting.DataFilter.Person.GroupMemberDataViewFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "256909FC-74F2-4C3E-94B5-7F82A195A910" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.GroupTypeAttendanceFilter", "Group Type Attendance Filter", "Rock.Reporting.DataFilter.Person.GroupTypeAttendanceFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "55E78F48-F849-444A-B285-FDA99E7236E7" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.HasPictureFilter", "Has Picture Filter", "Rock.Reporting.DataFilter.Person.HasPictureFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "569CD481-0C0A-4A05-8EB5-4836CF13E853" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.HistoryDataViewFilter", "History Data View Filter", "Rock.Reporting.DataFilter.Person.HistoryDataViewFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "EE2E4C8E-0A0C-4270-9DD0-00BB061820F2" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.InGroupFilter", "In Group Filter", "Rock.Reporting.DataFilter.Person.InGroupFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "A40B4BD4-FA17-4A82-97CC-2C71805F9D7C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.InGroupGeofenceFilter", "In Group Geofence Filter", "Rock.Reporting.DataFilter.Person.InGroupGeofenceFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "32ADC9E4-29CB-4D19-9073-CD9D3A8D2A6C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.LocationDataViewFilter", "Location Data View Filter", "Rock.Reporting.DataFilter.Person.LocationDataViewFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "CC24FC79-5A5F-48F2-A6A3-9DD49A90A42B" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.NotInGroupFilter", "Not In Group Filter", "Rock.Reporting.DataFilter.Person.NotInGroupFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "C5F2E726-D16F-4E4A-8273-35CAC2ED7762" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.NotInGroupGroupTypeFilter", "Not In Group Group Type Filter", "Rock.Reporting.DataFilter.Person.NotInGroupGroupTypeFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "6401B50D-A675-4C91-B981-BBCAD7362832" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Person.TagFilter", "Tag Filter", "Rock.Reporting.DataFilter.Person.TagFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "DD28F6C7-6571-4C6A-A021-13A5EB8BD216" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Workflow.WorkflowAttributesFilter", "Workflow Attributes Filter", "Rock.Reporting.DataFilter.Workflow.WorkflowAttributesFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F0DF027F-65F5-49DE-BA26-25610B83879A" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataFilter.Workflow.WorkflowTypeFilter", "Workflow Type Filter", "Rock.Reporting.DataFilter.Workflow.WorkflowTypeFilter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "48975139-45A8-4CCC-BC03-FDB32B9BB7C6" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.FinancialTransaction.TotalAmountSelect", "Total Amount Select", "Rock.Reporting.DataSelect.FinancialTransaction.TotalAmountSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "5BD5E922-D729-4ECB-990F-8DA8440FA28A" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.CampusSelect", "Campus Select", "Rock.Reporting.DataSelect.Group.CampusSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "90FDBE43-4321-4D4D-AFBB-7E8D74DE89CE" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.DistanceFromSelect", "Distance From Select", "Rock.Reporting.DataSelect.Group.DistanceFromSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "90E58F48-E133-49CB-AC16-29C53E7044F1" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.GroupLinkSelect", "Group Link Select", "Rock.Reporting.DataSelect.Group.GroupLinkSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "CACA75F2-29FE-4A52-AD4D-22E7314A35EB" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.GroupTypeSelect", "Group Type Select", "Rock.Reporting.DataSelect.Group.GroupTypeSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "8800858A-C980-4EC0-83A6-29F2B51DBD4E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.LocationSelect", "Location Select", "Rock.Reporting.DataSelect.Group.LocationSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "8533C1A1-01E6-4791-B653-C3D0774818BA" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.MemberCountSelect", "Member Count Select", "Rock.Reporting.DataSelect.Group.MemberCountSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "45786F38-F50B-4FB2-8CEB-AFDCF42C5EB5" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.MemberListSelect", "Member List Select", "Rock.Reporting.DataSelect.Group.MemberListSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "42D54FD1-74AA-4D47-BE84-BF92334ECD33" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.ParentGroupMemberListSelect", "Parent Group Member List Select", "Rock.Reporting.DataSelect.Group.ParentGroupMemberListSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "3909997E-E096-4B17-A864-E0D0953FE576" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.ParentGroupSelect", "Parent Group Select", "Rock.Reporting.DataSelect.Group.ParentGroupSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "0F99D3D5-E198-4E54-95CB-16B9EB23E718" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Group.ParticipationRateSelect", "Participation Rate Select", "Rock.Reporting.DataSelect.Group.ParticipationRateSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "A09DEA74-82ED-41F7-8A1E-AAC771DEC692" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.GroupMember.GroupCampusSelect", "Group Campus Select", "Rock.Reporting.DataSelect.GroupMember.GroupCampusSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "59C8E685-9576-4629-99E5-E7461B907F41" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.GroupMember.GroupLinkSelect", "Group Link Select", "Rock.Reporting.DataSelect.GroupMember.GroupLinkSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "9CF6163A-6E6A-47F3-B9E3-4558E75B1B9F" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.GroupMember.GroupMemberAttributeSelect", "Group Member Attribute Select", "Rock.Reporting.DataSelect.GroupMember.GroupMemberAttributeSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "9153410A-814E-46B2-8921-464E938412D4" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.GroupMember.GroupRoleSelect", "Group Role Select", "Rock.Reporting.DataSelect.GroupMember.GroupRoleSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "D68102CB-B11C-41ED-B0CE-411B922E5669" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.GroupMember.GroupStatusSelect", "Group Status Select", "Rock.Reporting.DataSelect.GroupMember.GroupStatusSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F6107037-DA13-49D0-B2EB-A5989D221318" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.GroupMember.PersonLinkSelect", "Person Link Select", "Rock.Reporting.DataSelect.GroupMember.PersonLinkSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "52E351C8-F44C-49CC-B547-13C28A5F3386" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.AddressSelect", "Address Select", "Rock.Reporting.DataSelect.Person.AddressSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "0A1731E9-CBFC-4CB9-920C-107C8D275583" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.AgeSelect", "Age Select", "Rock.Reporting.DataSelect.Person.AgeSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "E6048FE3-1EC4-4C7B-A606-70FEC56015F3" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.CampusSelect", "Campus Select", "Rock.Reporting.DataSelect.Person.CampusSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "4739CF62-E7E7-42AB-85E4-E972E264170A" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.ChildNamesSelect", "Child Names Select", "Rock.Reporting.DataSelect.Person.ChildNamesSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "8DE06919-D68C-4A29-989B-359A0379F1F3" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.DistanceFromSelect", "Distance From Select", "Rock.Reporting.DataSelect.Person.DistanceFromSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "D7997EC5-99EA-493A-8655-A31C38477C1C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.FamilyNameSelect", "Family Name Select", "Rock.Reporting.DataSelect.Person.FamilyNameSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "13CA0DC6-0A62-4B3E-BED2-2FBE5B284CCE" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.FirstContributionSelect", "First Contribution Select", "Rock.Reporting.DataSelect.Person.FirstContributionSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "6C7C6C7A-3355-4FBF-9D39-AEB50E46A7C1" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.GradeSelect", "Grade Select", "Rock.Reporting.DataSelect.Person.GradeSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "1BF02438-BF23-4BC3-A98A-B5D7523297B2" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.GroupParticipationSelect", "Group Participation Select", "Rock.Reporting.DataSelect.Person.GroupParticipationSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "CC008C3C-AD0E-437D-A55F-274718679F4D" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.InGroupGeofenceGroupTypeSelect", "In Group Geofence Group Type Select", "Rock.Reporting.DataSelect.Person.InGroupGeofenceGroupTypeSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "26571938-D421-4BAA-8150-84A31FE5D2FF" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.InGroupGroupTypeSelect", "In Group Group Type Select", "Rock.Reporting.DataSelect.Person.InGroupGroupTypeSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "0F27DC55-91B0-448A-B270-D5D93EA5B4F1" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.LastAttendedGroupOfType", "Last Attended Group Of Type", "Rock.Reporting.DataSelect.Person.LastAttendedGroupOfType, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F3C67ECD-5E80-4807-8F90-6AD110674ADF" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.LastLoginSelect", "Last Login Select", "Rock.Reporting.DataSelect.Person.LastLoginSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F4A1FC8D-D27C-40C9-86CA-3DE87046E79E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.LastNoteSelect", "Last Note Select", "Rock.Reporting.DataSelect.Person.LastNoteSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "230E6B5E-8472-47E3-91DC-30D5D044665C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.ParentsEmailSelect", "Parents Email Select", "Rock.Reporting.DataSelect.Person.ParentsEmailSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "2DAB411C-281B-498A-9164-8E3C9BA06E08" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.ParentsNamesSelect", "Parents Names Select", "Rock.Reporting.DataSelect.Person.ParentsNamesSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "0A97FB21-EC9E-4199-9872-AE526C7D0CBC" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.ParentsPhoneNumberSelect", "Parents Phone Number Select", "Rock.Reporting.DataSelect.Person.ParentsPhoneNumberSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "CDE54D9E-CA91-4E13-920A-24EC01F75C1E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.PhoneNumberSelect", "Phone Number Select", "Rock.Reporting.DataSelect.Person.PhoneNumberSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "5CBFBC11-826A-4B83-845E-247DD6268FFF" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.PhotoSelect", "Photo Select", "Rock.Reporting.DataSelect.Person.PhotoSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "C2EE52FA-044F-47DE-A398-18F8E3D9311D" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.RelatedPeopleSelect", "Related People Select", "Rock.Reporting.DataSelect.Person.RelatedPeopleSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "7D2CB16A-9391-4D5A-A4B4-4DA34FD3E96E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.SpouseNameSelect", "Spouse Name Select", "Rock.Reporting.DataSelect.Person.SpouseNameSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "E8B3A661-5C6D-4B24-A09A-4D3ED080CE0C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataSelect.Person.TotalGivingAmountSelect", "Total Giving Amount Select", "Rock.Reporting.DataSelect.Person.TotalGivingAmountSelect, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "680C50EC-2815-4390-9BCD-6EE0D2496E34" );
            RockMigrationHelper.UpdateEntityType( "Rock.Reporting.DataTransform.Person.ChildrenTransform", "Children Transform", "Rock.Reporting.DataTransform.Person.ChildrenTransform, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "C4440BAA-AEFC-455B-983D-9D6CCFA8C5D9" );
            RockMigrationHelper.UpdateEntityType( "Rock.Rest.Controllers.MetricYTDData", "Metric YTD Data", "Rock.Rest.Controllers.MetricYTDData, Rock.Rest, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", true, true, "7C878AFD-DF74-4CDF-8491-31671559BD30" );
            RockMigrationHelper.UpdateEntityType( "Rock.Security.ExternalAuthentication.Google", "Google", "Rock.Security.ExternalAuthentication.Google, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "9E678E8B-D9C4-4772-BED8-390C5E85DA76" );
            RockMigrationHelper.UpdateEntityType( "Rock.Security.ExternalAuthentication.Twitter", "Twitter", "Rock.Security.ExternalAuthentication.Twitter, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "CE5C0844-4020-45E8-9777-1EE13CB890BF" );
            RockMigrationHelper.UpdateEntityType( "Rock.SignNow.SignNow", "Sign Now", "Rock.SignNow.SignNow, Rock.SignNow, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "6A172772-643F-4674-A487-D13A9D9EE9C4" );
            RockMigrationHelper.UpdateEntityType( "Rock.UniversalSearch.IndexComponents.Elasticsearch", "Elasticsearch", "Rock.UniversalSearch.IndexComponents.Elasticsearch, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "97DACCE9-F397-4E7B-9596-783A233FCFCF" );
            RockMigrationHelper.UpdateEntityType( "Rock.Web.Cache.EventCalendarCache", "Event Calendar Cache", "Rock.Web.Cache.EventCalendarCache, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "B52E848A-73C6-4563-A07A-05F7CD2C9F6B" );
            RockMigrationHelper.UpdateEntityType( "Rock.Web.Cache.GroupTypeCache", "Group Type Cache", "Rock.Web.Cache.GroupTypeCache, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "9682152F-6A9C-46BC-A7D1-EFD1CB07CFFE" );
            RockMigrationHelper.UpdateEntityType( "Rock.Web.Cache.NoteTypeCache", "Note Type Cache", "Rock.Web.Cache.NoteTypeCache, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "DAC503A1-9973-4CF3-B273-4D29937E7EBB" );
            RockMigrationHelper.UpdateEntityType( "Rock.Web.Cache.PersonBadgeCache", "Person Badge Cache", "Rock.Web.Cache.PersonBadgeCache, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "FDF8C0D2-19E8-456F-B652-B658C1762A9C" );
            RockMigrationHelper.UpdateEntityType( "Rock.Web.Cache.RestActionCache", "Rest Action Cache", "Rock.Web.Cache.RestActionCache, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "217E5B7B-6734-4F11-87CF-825E0B611B6F" );
            RockMigrationHelper.UpdateEntityType( "Rock.Web.Cache.RestControllerCache", "Rest Controller Cache", "Rock.Web.Cache.RestControllerCache, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "87512AFF-8FF3-4EA6-B019-6A01B48A3004" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.ActivateOtherActivity", "Activate Other Activity", "Rock.Workflow.Action.ActivateOtherActivity, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "DD266CDB-7D60-4312-B727-C2AA95C21128" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.ActivateOtherActivityOnMatch", "Activate Other Activity On Match", "Rock.Workflow.Action.ActivateOtherActivityOnMatch, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "2F192ADD-3222-4BD9-8E2F-CEF338B97EBD" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.ActivateWorkflow", "Activate Workflow", "Rock.Workflow.Action.ActivateWorkflow, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "9E3C42B5-792A-4694-8ACE-B84E5E87C800" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.AddConnectionRequestActivity", "Add Connection Request Activity", "Rock.Workflow.Action.AddConnectionRequestActivity, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "A73CDF27-1B05-45F4-A436-EE6462DB01B5" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.AddNoteToGroupMember", "Add Note To Group Member", "Rock.Workflow.Action.AddNoteToGroupMember, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "019645AD-3BBF-47A0-AEA5-4F0636BDA715" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.AddWorkflowNote", "Add Workflow Note", "Rock.Workflow.Action.AddWorkflowNote, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "A186BDF7-B489-47FE-B11E-1953B0C500F9" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.BenevolenceRequestAdd", "Benevolence Request Add", "Rock.Workflow.Action.BenevolenceRequestAdd, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "22B3C308-2333-4A11-8AEC-1AA7A201B5BB" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.BenevolenceRequestAddDocument", "Benevolence Request Add Document", "Rock.Workflow.Action.BenevolenceRequestAddDocument, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "A965D3CA-D00A-42EC-8097-CF15108B2DB4" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.BenevolenceRequestSetAttribute", "Benevolence Request Set Attribute", "Rock.Workflow.Action.BenevolenceRequestSetAttribute, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "478FEDC6-2AD7-467C-9C02-A41E2EFC4271" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.CheckIn.FilterGroupsByGradeAndAge", "Filter Groups By Grade And Age", "Rock.Workflow.Action.CheckIn.FilterGroupsByGradeAndAge, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "8FCB06EF-2782-4FF3-91DE-24C1122DE2E5" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.CreateConnectionRequest", "Create Connection Request", "Rock.Workflow.Action.CreateConnectionRequest, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F95C376A-714E-41FE-B27A-683F9E9078ED" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.GetPersonFromFields", "Get Person From Fields", "Rock.Workflow.Action.GetPersonFromFields, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "E5E7CA24-7030-4D48-9C39-04B5809E71A8" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.PersonAddressUpdate", "Person Address Update", "Rock.Workflow.Action.PersonAddressUpdate, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "B9C0DDB5-F437-4175-AB32-84AA4E20F788" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.PersonGetSpouse", "Person Get Spouse", "Rock.Workflow.Action.PersonGetSpouse, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "45D48A23-981A-435E-8294-CE212F66BFD1" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.PersonNoteAdd", "Person Note Add", "Rock.Workflow.Action.PersonNoteAdd, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "B2C8B951-C41E-4DFB-9F92-F183223448AA" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.PersonPhoneUpdate", "Person Phone Update", "Rock.Workflow.Action.PersonPhoneUpdate, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "65DFC198-B9F5-45CB-839D-AF30791C4FBF" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.PersonPropertyUpdate", "Person Property Update", "Rock.Workflow.Action.PersonPropertyUpdate, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "65FF3BCF-0F78-46FF-A291-180D0236DD8E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.PostAttendanceToGroup", "Post Attendance To Group", "Rock.Workflow.Action.PostAttendanceToGroup, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "7D939E2E-EBD5-491A-AA9C-FBCC91AAD5D3" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.RemovePersonFromGroup", "Remove Person From Group", "Rock.Workflow.Action.RemovePersonFromGroup, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "E0305041-5F3B-42FD-8E1D-D2BC3224D50E" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.RemovePersonFromGroupAttribute", "Remove Person From Group Attribute", "Rock.Workflow.Action.RemovePersonFromGroupAttribute, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "0F32A101-63E3-4345-B307-5DCEBE31009F" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.RunJob", "Run Job", "Rock.Workflow.Action.RunJob, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "9269DD7C-027B-4032-9F4C-9A3CAB6FF841" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.RunLava", "Run Lava", "Rock.Workflow.Action.RunLava, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "BC21E57A-1477-44B3-A7C2-61A806118945" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SendEmailWithEvents", "Send Email With Events", "Rock.Workflow.Action.SendEmailWithEvents, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "E5DDF7AA-CA76-4236-A8D5-88F66F864FE8" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SetAttributeToGroupLeader", "Set Attribute To Group Leader", "Rock.Workflow.Action.SetAttributeToGroupLeader, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "179BE15E-DA54-4517-BDA9-E3ED339FFC7D" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SetAttributeToRandomGroupMember", "Set Attribute To Random Group Member", "Rock.Workflow.Action.SetAttributeToRandomGroupMember, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "96B57C0E-F84D-4B45-A11F-35F8A7A63689" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SetConnectionRequestState", "Set Connection Request State", "Rock.Workflow.Action.SetConnectionRequestState, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "3C3B389B-BE46-495E-A5AC-2B2C7BA41DBA" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SetConnectionRequestStatus", "Set Connection Request Status", "Rock.Workflow.Action.SetConnectionRequestStatus, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "60AFBB6A-B210-4C56-8AD5-2DA3311EDAA8" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SetGroupMemberAttribute", "Set Group Member Attribute", "Rock.Workflow.Action.SetGroupMemberAttribute, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "5A0885C7-2D6F-4F04-BBE1-78AE61108C51" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SetGroupMemberNote", "Set Group Member Note", "Rock.Workflow.Action.SetGroupMemberNote, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "D54F30CD-8759-45BA-AF05-ABCFB0F21005" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.SetInitiatorFromAttribute", "Set Initiator From Attribute", "Rock.Workflow.Action.SetInitiatorFromAttribute, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "6F623097-2BAB-4BFB-B4E3-E18785C71DA7" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.TransferConnectionRequest", "Transfer Connection Request", "Rock.Workflow.Action.TransferConnectionRequest, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "308B46FD-6D87-471B-AA98-AAE1894B0D49" );
            RockMigrationHelper.UpdateEntityType( "Rock.Workflow.Action.UpdateGroupMemberStatus", "Update Group Member Status", "Rock.Workflow.Action.UpdateGroupMemberStatus, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, true, "F09E2C90-5FB1-4236-B146-848B983CC3A8" );

            RockMigrationHelper.UpdateEntityType( "Rock.UniversalSearch.IndexModels.PersonIndex", "PersonIndex", "Rock.UniversalSearch.IndexModels.PersonIndex, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, false, "F693B821-82A5-F6B5-4BD1-8091252F82CD" );
            RockMigrationHelper.UpdateEntityType( "Rock.UniversalSearch.IndexModels.BusinessIndex", "BusinessIndex", "Rock.UniversalSearch.IndexModels.BusinessIndex, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, false, "AF18D8AA-A3F9-0B81-4F4A-B9C92A54EF3F" );
            RockMigrationHelper.UpdateEntityType( "Rock.UniversalSearch.IndexModels.GroupIndex", "GroupIndex", "Rock.UniversalSearch.IndexModels.GroupIndex, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, false, "F0D0FC68-D3B7-2D81-4E90-061948930DEB" );
            RockMigrationHelper.UpdateEntityType( "Rock.UniversalSearch.IndexModels.ContentChannelItemIndex", "ContentChannelItem", "Rock.UniversalSearch.IndexModels.ContentChannelItem, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, false, "CBF733DC-64F9-6D93-4FBD-5FC06FA8A907" );
            RockMigrationHelper.UpdateEntityType( "Rock.UniversalSearch.IndexModels.SitePageIndex", "SitePageIndex", "Rock.UniversalSearch.IndexModels.SitePageIndex, Rock, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null", false, false, "100C97C5-9A0E-FE87-46F9-CB1B8812A174" );

            // DT: New Defined Type Block Attribute
            RockMigrationHelper.UpdateBlockType( "Defined Type List", "Lists all the defined types and allows for managing them and their values.", "~/Blocks/Core/DefinedTypeList.ascx", "Core", "5470C9C4-09C1-439F-AA56-3524047497EE" );
            RockMigrationHelper.UpdateBlockTypeAttribute( "5470C9C4-09C1-439F-AA56-3524047497EE", "BD53F9C9-EBA9-4D3F-82EA-DE5DD34A8108", "Detail Page", "DetailPage", "", "", 0, @"", "E75A3154-22F5-4E35-BF86-B57EFA460BD6" );
            RockMigrationHelper.UpdateBlockTypeAttribute( "5470C9C4-09C1-439F-AA56-3524047497EE", "775899FB-AC17-4C2C-B809-CF3A1D2AA4E1", "Categories", "Categories", "", "If block should only display Defined Types from specific categories, select the categories here.", 1, @"", "48F799FB-61F0-429E-A6DD-BB14393F18D3" );

        }

        /// <summary>
        /// Operations to be performed during the downgrade process.
        /// </summary>
        public override void Down()
        {
        }
    }
}
