#!/bin/sh

# set all strings to UTF-8
LC_CTYPE=en_US.utf8

# regex to validate the commit message against
commit_regex='(^([+]{1}[ ]{1}(\(API\)|\(CMS\)|\(Check\-in\)|\(Communication\)|\(Connection\)|\(Core\)|\(CRM\)|\(Engagement\)|\(Event\)|\(Farm\)|\(Finance\)|\(Group\)|\(Lava\)|\(Mobile\)|\(Prayer\)|\(Reporting\)|\(Workflow\)|\(Other\)){1}[ ]{1}(Add*|Fix*|Improv*|Updat*){1}[\s\S][^\n]+(\. (\(Fix(es|ed) \#[0-9]+\))$|[\w]\.$){1})|^([-]{1}[ ]{1}[\s\S][^\n]+)){1}|^(Merge+.+)|^(Revert+.+)|^(Cherry+.+)'
error_message_1="Your commit message should be a single-line and in one of the following formats:"
error_message_2=" [Github Issue/PR Fix]: + (Domain) Add/Fix/Improve/Update Text. (Fixes #0000)"
error_message_3=" [Public release note]: + (Domain) Add/Fix/Improve/Update Text."
error_message_4=" [Internal commit msg]: - Text"
guide_link=" See commit guidelines: https://triumph.slab.com/posts/developer-codex-current-orig-y3tqutbv#h5nco-committing-code"

if ! grep -r -n -H -P "$commit_regex" "$1"; then
    echo "${error_message_1}" >&2
    echo "${error_message_2}" >&2
    echo "${error_message_3}" >&2
    echo "${error_message_4}" >&2
    echo "${guide_link}" >&2
    exit 1
fi
