//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** The configuration options required to render the Attribute Values block. */
export type AttributeValuesOptionsBag = {
    /**
     * Gets or sets a value indicating whether the current person may edit
     * at least one of the displayed attributes. Controls the visibility
     * of the edit action.
     */
    isEditAllowed: boolean;

    /**
     * Gets or sets a value indicating whether the attributes are grouped
     * by category with the category names rendered as heading separators.
     */
    isGroupedByCategory: boolean;

    /**
     * Gets or sets a value indicating whether the current person may
     * reorder the displayed attributes. Requires administrate access and
     * is unavailable while attributes are grouped by category.
     */
    isOrderAllowed: boolean;

    /**
     * Gets or sets a value indicating whether the block should be visible.
     * This is false when there is no valid person in context.
     */
    isVisible: boolean;

    /**
     * Gets or sets the panel title. Falls back to the configured category
     * name when a single category is configured and no block title is set.
     */
    title?: string | null;

    /**
     * Gets or sets the CSS class of the panel title icon. Falls back to
     * the configured category icon when a single category is configured
     * and no block icon is set.
     */
    titleIconCssClass?: string | null;
};
