//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** Represents a container for configuration options used to customize the behavior and layout of a file editor. */
export type FileEditorOptionsBag = {
    /**
     * Gets or sets the editor mode, which determines the operational mode of the code editor,
     * based on the type of file being edited.
     */
    editorMode?: string | null;

    /** Gets or sets a value indicating whether this instance is editable. */
    isEditable: boolean;

    /** Gets or sets a value indicating whether the current layout is a worksurface layout. */
    isWorksurfaceLayout: boolean;
};
