//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
using System;
using System.Collections.Generic;


namespace Rock.Client
{
    /// <summary>
    /// Base client model for ConnectionRequest that only includes the non-virtual fields. Use this for PUT/POSTs
    /// </summary>
    public partial class ConnectionRequestEntity
    {
        /// <summary />
        public int Id { get; set; }

        /// <summary />
        public int? AssignedGroupId { get; set; }

        /// <summary />
        public string AssignedGroupMemberAttributeValues { get; set; }

        /// <summary />
        public int? AssignedGroupMemberRoleId { get; set; }

        /// <summary />
        public Rock.Client.Enums.GroupMemberStatus? AssignedGroupMemberStatus { get; set; }

        /// <summary />
        public int? CampusId { get; set; }

        /// <summary />
        public string Comments { get; set; }

        /// <summary />
        public int ConnectionOpportunityId { get; set; }

        /// <summary />
        public int /* ConnectionState*/ ConnectionState { get; set; }

        /// <summary />
        public int ConnectionStatusId { get; set; }

        /// <summary />
        public int? ConnectorPersonAliasId { get; set; }

        /// <summary />
        public AnalyticsSourceDate CreatedSourceDate { get; set; }

        /// <summary />
        public DateTime? FollowupDate { get; set; }

        /// <summary />
        public Guid? ForeignGuid { get; set; }

        /// <summary />
        public string ForeignKey { get; set; }

        /// <summary>
        /// If the ModifiedByPersonAliasId is being set manually and should not be overwritten with current user when saved, set this value to true
        /// </summary>
        public bool ModifiedAuditValuesAlreadyUpdated { get; set; }

        /// <summary />
        public int Order { get; set; }

        /// <summary />
        public int PersonAliasId { get; set; }

        /// <summary>
        /// Leave this as NULL to let Rock set this
        /// </summary>
        public DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// This does not need to be set or changed. Rock will always set this to the current date/time when saved to the database.
        /// </summary>
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Leave this as NULL to let Rock set this
        /// </summary>
        public int? CreatedByPersonAliasId { get; set; }

        /// <summary>
        /// If you need to set this manually, set ModifiedAuditValuesAlreadyUpdated=True to prevent Rock from setting it
        /// </summary>
        public int? ModifiedByPersonAliasId { get; set; }

        /// <summary />
        public Guid Guid { get; set; }

        /// <summary />
        public int? ForeignId { get; set; }

        /// <summary>
        /// Copies the base properties from a source ConnectionRequest object
        /// </summary>
        /// <param name="source">The source.</param>
        public void CopyPropertiesFrom( ConnectionRequest source )
        {
            this.Id = source.Id;
            this.AssignedGroupId = source.AssignedGroupId;
            this.AssignedGroupMemberAttributeValues = source.AssignedGroupMemberAttributeValues;
            this.AssignedGroupMemberRoleId = source.AssignedGroupMemberRoleId;
            this.AssignedGroupMemberStatus = source.AssignedGroupMemberStatus;
            this.CampusId = source.CampusId;
            this.Comments = source.Comments;
            this.ConnectionOpportunityId = source.ConnectionOpportunityId;
            this.ConnectionState = source.ConnectionState;
            this.ConnectionStatusId = source.ConnectionStatusId;
            this.ConnectorPersonAliasId = source.ConnectorPersonAliasId;
            this.CreatedSourceDate = source.CreatedSourceDate;
            this.FollowupDate = source.FollowupDate;
            this.ForeignGuid = source.ForeignGuid;
            this.ForeignKey = source.ForeignKey;
            this.ModifiedAuditValuesAlreadyUpdated = source.ModifiedAuditValuesAlreadyUpdated;
            this.Order = source.Order;
            this.PersonAliasId = source.PersonAliasId;
            this.CreatedDateTime = source.CreatedDateTime;
            this.ModifiedDateTime = source.ModifiedDateTime;
            this.CreatedByPersonAliasId = source.CreatedByPersonAliasId;
            this.ModifiedByPersonAliasId = source.ModifiedByPersonAliasId;
            this.Guid = source.Guid;
            this.ForeignId = source.ForeignId;

        }
    }

    /// <summary>
    /// Client model for ConnectionRequest that includes all the fields that are available for GETs. Use this for GETs (use ConnectionRequestEntity for POST/PUTs)
    /// </summary>
    public partial class ConnectionRequest : ConnectionRequestEntity
    {
        /// <summary />
        public ConnectionOpportunity ConnectionOpportunity { get; set; }

        /// <summary />
        public ConnectionStatus ConnectionStatus { get; set; }

        /// <summary />
        public int? CreatedDateKey { get; set; }

        /// <summary />
        public PersonAlias PersonAlias { get; set; }

        /// <summary>
        /// NOTE: Attributes are only populated when ?loadAttributes is specified. Options for loadAttributes are true, false, 'simple', 'expanded' 
        /// </summary>
        public Dictionary<string, Rock.Client.Attribute> Attributes { get; set; }

        /// <summary>
        /// NOTE: AttributeValues are only populated when ?loadAttributes is specified. Options for loadAttributes are true, false, 'simple', 'expanded' 
        /// </summary>
        public Dictionary<string, Rock.Client.AttributeValue> AttributeValues { get; set; }
    }
}
