//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** Due Date Calculation Mode */
export const DueDateCalculationMode = {
    /** Fixed Days from Start configured on Connection Type */
    FixedDaysFromStartTypeLevel: 0,

    /** Fixed Days from Start configured on Connection Opportunity */
    FixedDaysFromStartOpportunityLevel: 1,

    /** Sets the due date according to the allowed time for the request’s current status, updating each time the status changes. */
    DurationPerStatus: 2
} as const;

/** Due Date Calculation Mode */
export const DueDateCalculationModeDescription: Record<number, string> = {
    0: "Fixed Days From Start (Type Level)",

    1: "Fixed Days From Start (Opportunity Level)",

    2: "Duration Per Status"
};

/** Due Date Calculation Mode */
export type DueDateCalculationMode = typeof DueDateCalculationMode[keyof typeof DueDateCalculationMode];
