//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the T4\Model.tt template.
//
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//
using System;

using Rock.Models.Crm;

namespace Rock.Repository.Crm
{
	/// <summary>
	/// Represents a Address POCO Repository class
	/// </summary>
    public interface IAddressRepository : IRepository<Rock.Models.Crm.Address>
    {
    }
}
