<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>False</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Rock.Tests" />
    <InternalsVisibleTo Include="Rock.Tests.Integration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rock.Common\Rock.Common.csproj" />
    <ProjectReference Include="..\Rock.Enums\Rock.Enums.csproj" />
    <ProjectReference Include="..\Rock\Rock.csproj" />
  </ItemGroup>

</Project>
