//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { PublicAttributeBag } from "@Obsidian/ViewModels/Utility/publicAttributeBag";

/** Report View Model */
export type ReportBag = {
    /** Gets or sets the attributes. */
    attributes?: Record<string, PublicAttributeBag> | null;

    /** Gets or sets the attribute values. */
    attributeValues?: Record<string, string> | null;

    /** Gets or sets the CategoryId of the Rock.Model.Category that the Report belongs to. */
    categoryId?: number | null;

    /** Gets or sets the created by person alias identifier. */
    createdByPersonAliasId?: number | null;

    /** Gets or sets the created date time. */
    createdDateTime?: string | null;

    /** Gets or the DataViewId of the root Rock.Model.DataView that this Report is based on. */
    dataViewId?: number | null;

    /** Gets or sets the Report's Description. */
    description?: string | null;

    /** Gets or sets the EntityTypeId of the Rock.Model.EntityType that is being reported on. */
    entityTypeId?: number | null;

    /** Gets or sets the number of records to fetch in the report.  Null means all records. */
    fetchTop?: number | null;

    /** Gets or sets the identifier key of this entity. */
    idKey?: string | null;

    /** Gets or sets a flag indicating if this Report is part of the Rock core system/framework. This property is required. */
    isSystem: boolean;

    /** Gets or sets the last run date time. */
    lastRunDateTime?: string | null;

    /** Gets or sets the modified by person alias identifier. */
    modifiedByPersonAliasId?: number | null;

    /** Gets or sets the modified date time. */
    modifiedDateTime?: string | null;

    /** Gets or sets the Name of the Report. This property is required. */
    name?: string | null;

    /** Gets or sets the query hint that is included in the SQL that is executed on the database server */
    queryHint?: string | null;

    /** Gets or sets the persisted last run duration in mulliseconds. */
    runCount?: number | null;

    /** The amount of time in milliseconds that it took to run the Rock.Model.Report.DataView */
    timeToRunDurationMilliseconds?: number | null;
};
