// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
namespace Rock.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    /// <summary>
    ///
    /// </summary>
    public partial class AddIconTransitionTable : Rock.Migrations.RockMigration
    {
        /// <summary>
        /// Operations to be performed during the upgrade process.
        /// </summary>
        public override void Up()
        {
            AddIconTransitionTableUp();
        }
        
        /// <summary>
        /// Operations to be performed during the downgrade process.
        /// </summary>
        public override void Down()
        {
            AddIconTranstionTableDown();
        }

        #region KH: Add __IconTransition Table

        private void AddIconTransitionTableUp()
        {
            Sql( @"
IF OBJECT_ID(N'[dbo].[__IconTransition]', N'U') IS NULL
BEGIN
CREATE TABLE [__IconTransition] (
    [FontAwesomeClass] NVARCHAR(50) NULL,
    [FontAwesomeFull] NVARCHAR(75) NULL,
    [TablerClass] NVARCHAR(50) NULL,
    [TablerFull] NVARCHAR(75) NULL
);

INSERT INTO [__IconTransition] ([FontAwesomeClass], [FontAwesomeFull], [TablerClass], [TablerFull])
VALUES
('fa-ad','fa fa-ad','ti-ad','ti ti-ad'),
('fa-address-book','fa fa-address-book','ti-address-book','ti ti-address-book'),
('fa-address-card','fa fa-address-card','ti-id','ti ti-id'),
('fa-adjust','fa fa-adjust','ti-circle-half-2','ti ti-circle-half-2'),
('fa-air-freshener','fa fa-air-freshener','ti-spray','ti ti-spray'),
('fa-align-center','fa fa-align-center','ti-align-center','ti ti-align-center'),
('fa-align-justify','fa fa-align-justify','ti-align-justified','ti ti-align-justified'),
('fa-align-left','fa fa-align-left','ti-align-left','ti ti-align-left'),
('fa-align-right','fa fa-align-right','ti-align-right','ti ti-align-right'),
('fa-allergies','fa fa-allergies','ti-alert-hexagon','ti ti-alert-hexagon'),
('fa-ambulance','fa fa-ambulance','ti-ambulance','ti ti-ambulance'),
('fa-american-sign-language-interpreting','fa fa-american-sign-language-interpreting',null,null),
('fa-anchor','fa fa-anchor','ti-anchor','ti ti-anchor'),
('fa-angle-double-down','fa fa-angle-double-down','ti-chevrons-down','ti ti-chevrons-down'),
('fa-angle-double-left','fa fa-angle-double-left','ti-chevrons-left','ti ti-chevrons-left'),
('fa-angle-double-right','fa fa-angle-double-right','ti-chevrons-right','ti ti-chevrons-right'),
('fa-angle-double-up','fa fa-angle-double-up','ti-chevrons-up','ti ti-chevrons-up'),
('fa-angle-down','fa fa-angle-down','ti-chevron-down','ti ti-chevron-down'),
('fa-angle-left','fa fa-angle-left','ti-chevron-left','ti ti-chevron-left'),
('fa-angle-right','fa fa-angle-right','ti-chevron-right','ti ti-chevron-right'),
('fa-angle-up','fa fa-angle-up','ti-chevron-up','ti ti-chevron-up'),
('fa-angry','fa fa-angry','ti-mood-angry','ti ti-mood-angry'),
('fa-ankh','fa fa-ankh','ti-ankh','ti ti-ankh'),
('fa-apple-alt','fa fa-apple-alt','ti-apple','ti ti-apple'),
('fa-archive','fa fa-archive','ti-archive','ti ti-archive'),
('fa-archway','fa fa-archway','ti-building-arch','ti ti-building-arch'),
('fa-arrow-alt-circle-down','fa fa-arrow-alt-circle-down','ti-circle-arrow-down','ti ti-circle-arrow-down'),
('fa-arrow-alt-circle-left','fa fa-arrow-alt-circle-left','ti-circle-arrow-left','ti ti-circle-arrow-left'),
('fa-arrow-alt-circle-right','fa fa-arrow-alt-circle-right','ti-circle-arrow-right','ti ti-circle-arrow-right'),
('fa-arrow-alt-circle-up','fa fa-arrow-alt-circle-up','ti-circle-arrow-up','ti ti-circle-arrow-up'),
('fa-arrow-circle-down','fa fa-arrow-circle-down','ti-circle-arrow-down','ti ti-circle-arrow-down'),
('fa-arrow-circle-left','fa fa-arrow-circle-left','ti-circle-arrow-left','ti ti-circle-arrow-left'),
('fa-arrow-circle-right','fa fa-arrow-circle-right','ti-circle-arrow-right','ti ti-circle-arrow-right'),
('fa-arrow-circle-up','fa fa-arrow-circle-up','ti-circle-arrow-up','ti ti-circle-arrow-up'),
('fa-arrow-down','fa fa-arrow-down','ti-arrow-down','ti ti-arrow-down'),
('fa-arrow-left','fa fa-arrow-left','ti-arrow-left','ti ti-arrow-left'),
('fa-arrow-right','fa fa-arrow-right','ti-arrow-right','ti ti-arrow-right'),
('fa-arrow-up','fa fa-arrow-up','ti-arrow-up','ti ti-arrow-up'),
('fa-arrows-alt-h','fa fa-arrows-alt-h','ti-arrows-horizontal','ti ti-arrows-horizontal'),
('fa-arrows-alt-v','fa fa-arrows-alt-v','ti-arrows-vertical','ti ti-arrows-vertical'),
('fa-arrows-alt','fa fa-arrows-alt','ti-arrows-move','ti ti-arrows-move'),
('fa-assistive-listening-systems','fa fa-assistive-listening-systems','ti-ear','ti ti-ear'),
('fa-asterisk','fa fa-asterisk','ti-asterisk','ti ti-asterisk'),
('fa-at','fa fa-at','ti-at','ti ti-at'),
('fa-atlas','fa fa-atlas','ti-map-2','ti ti-map-2'),
('fa-atom','fa fa-atom','ti-atom','ti ti-atom'),
('fa-audio-description','fa fa-audio-description','ti-badge-ad','ti ti-badge-ad'),
('fa-award','fa fa-award','ti-award','ti ti-award'),
('fa-baby-carriage','fa fa-baby-carriage','ti-baby-carriage','ti ti-baby-carriage'),
('fa-baby','fa fa-baby','ti-baby-bottle','ti ti-baby-bottle'),
('fa-backspace','fa fa-backspace','ti-backspace','ti ti-backspace'),
('fa-backward','fa fa-backward','ti-player-track-prev','ti ti-player-track-prev'),
('fa-bacon','fa fa-bacon','ti-pig','ti ti-pig'),
('fa-bacteria','fa fa-bacteria','ti-virus','ti ti-virus'),
('fa-bacterium','fa fa-bacterium','ti-virus','ti ti-virus'),
('fa-bahai','fa fa-bahai',null,null),
('fa-balance-scale-left','fa fa-balance-scale-left','ti-scale','ti ti-scale'),
('fa-balance-scale-right','fa fa-balance-scale-right','ti-scale','ti ti-scale'),
('fa-balance-scale','fa fa-balance-scale','ti-scale','ti ti-scale'),
('fa-ban','fa fa-ban','ti-ban','ti ti-ban'),
('fa-band-aid','fa fa-band-aid','ti-bandage','ti ti-bandage'),
('fa-barcode','fa fa-barcode','ti-barcode','ti ti-barcode'),
('fa-bars','fa fa-bars','ti-menu-2','ti ti-menu-2'),
('fa-baseball-ball','fa fa-baseball-ball','ti-ball-baseball','ti ti-ball-baseball'),
('fa-basketball-ball','fa fa-basketball-ball','ti-ball-basketball','ti ti-ball-basketball'),
('fa-bath','fa fa-bath','ti-bath','ti ti-bath'),
('fa-battery-empty','fa fa-battery-empty','ti-battery','ti ti-battery'),
('fa-battery-full','fa fa-battery-full','ti-battery-4','ti ti-battery-4'),
('fa-battery-half','fa fa-battery-half','ti-battery-2','ti ti-battery-2'),
('fa-battery-quarter','fa fa-battery-quarter','ti-battery-1','ti ti-battery-1'),
('fa-battery-three-quarters','fa fa-battery-three-quarters','ti-battery-3','ti ti-battery-3'),
('fa-bed','fa fa-bed','ti-bed','ti ti-bed'),
('fa-beer','fa fa-beer','ti-beer','ti ti-beer'),
('fa-bell-slash','fa fa-bell-slash','ti-bell-off','ti ti-bell-off'),
('fa-bell','fa fa-bell','ti-bell','ti ti-bell'),
('fa-bezier-curve','fa fa-bezier-curve','ti-vector-bezier','ti ti-vector-bezier'),
('fa-bible','fa fa-bible','ti-bible','ti ti-bible'),
('fa-bicycle','fa fa-bicycle','ti-motorbike','ti ti-motorbike'),
('fa-biking','fa fa-biking','ti-bike','ti ti-bike'),
('fa-binoculars','fa fa-binoculars','ti-binoculars','ti ti-binoculars'),
('fa-biohazard','fa fa-biohazard','ti-biohazard','ti ti-biohazard'),
('fa-birthday-cake','fa fa-birthday-cake','ti-cake','ti ti-cake'),
('fa-blender-phone','fa fa-blender-phone',null,null),
('fa-blender','fa fa-blender','ti-blender','ti ti-blender'),
('fa-blind','fa fa-blind',null,null),
('fa-blog','fa fa-blog','ti-rss','ti ti-rss'),
('fa-bold','fa fa-bold','ti-bold','ti ti-bold'),
('fa-bolt','fa fa-bolt','ti-bolt','ti ti-bolt'),
('fa-bomb','fa fa-bomb','ti-bomb','ti ti-bomb'),
('fa-bone','fa fa-bone','ti-bone','ti ti-bone'),
('fa-bong','fa fa-bong','ti-bong','ti ti-bong'),
('fa-book-dead','fa fa-book-dead',null,null),
('fa-book-medical','fa fa-book-medical',null,null),
('fa-book-open','fa fa-book-open','ti-book','ti ti-book'),
('fa-book-reader','fa fa-book-reader','ti-book','ti ti-book'),
('fa-book','fa fa-book','ti-book','ti ti-book'),
('fa-bookmark','fa fa-bookmark','ti-bookmark','ti ti-bookmark'),
('fa-border-all','fa fa-border-all','ti-border-all','ti ti-border-all'),
('fa-border-none','fa fa-border-none','ti-border-none','ti ti-border-none'),
('fa-border-style','fa fa-border-style','ti-border-style','ti ti-border-style'),
('fa-bowling-ball','fa fa-bowling-ball','ti-ball-bowling','ti ti-ball-bowling'),
('fa-box-open','fa fa-box-open',null,null),
('fa-box-tissue','fa fa-box-tissue',null,null),
('fa-box','fa fa-box','ti-box','ti ti-box'),
('fa-boxes','fa fa-boxes','ti-packages','ti ti-packages'),
('fa-braille','fa fa-braille','ti-braille','ti ti-braille'),
('fa-brain','fa fa-brain','ti-brain','ti ti-brain'),
('fa-bread-slice','fa fa-bread-slice','ti-bread','ti ti-bread'),
('fa-briefcase-medical','fa fa-briefcase-medical','ti-first-aid-kit','ti ti-first-aid-kit'),
('fa-briefcase','fa fa-briefcase','ti-briefcase','ti ti-briefcase'),
('fa-broadcast-tower','fa fa-broadcast-tower','ti-building-broadcast','ti ti-building-broadcast'),
('fa-broom','fa fa-broom',null,null),
('fa-brush','fa fa-brush','ti-brush','ti ti-brush'),
('fa-bug','fa fa-bug','ti-bug','ti ti-bug'),
('fa-building','fa fa-building','ti-building','ti ti-building'),
('fa-bullhorn','fa fa-bullhorn','ti-speakerphone','ti ti-speakerphone'),
('fa-bullseye','fa fa-bullseye','ti-target','ti ti-target'),
('fa-burn','fa fa-burn','ti-flame','ti ti-flame'),
('fa-bus-alt','fa fa-bus-alt','ti-bus','ti ti-bus'),
('fa-bus','fa fa-bus','ti-bus','ti ti-bus'),
('fa-business-time','fa fa-business-time','ti-timezone','ti ti-timezone'),
('fa-calculator','fa fa-calculator','ti-calculator','ti ti-calculator'),
('fa-calendar-alt','fa fa-calendar-alt','ti-calendar-month','ti ti-calendar-month'),
('fa-calendar-check','fa fa-calendar-check','ti-calendar-check','ti ti-calendar-check'),
('fa-calendar-day','fa fa-calendar-day','ti-calendar-event','ti ti-calendar-event'),
('fa-calendar-minus','fa fa-calendar-minus','ti-calendar-minus','ti ti-calendar-minus'),
('fa-calendar-plus','fa fa-calendar-plus','ti-calendar-plus','ti ti-calendar-plus'),
('fa-calendar-times','fa fa-calendar-times','ti-calendar-x','ti ti-calendar-x'),
('fa-calendar-week','fa fa-calendar-week','ti-calendar-week','ti ti-calendar-week'),
('fa-calendar','fa fa-calendar','ti-calendar','ti ti-calendar'),
('fa-camera-retro','fa fa-camera-retro','ti-camera','ti ti-camera'),
('fa-camera','fa fa-camera','ti-camera','ti ti-camera'),
('fa-campground','fa fa-campground','ti-tent','ti ti-tent'),
('fa-candy-cane','fa fa-candy-cane','ti-cane','ti ti-cane'),
('fa-cannabis','fa fa-cannabis','ti-cannabis','ti ti-cannabis'),
('fa-capsules','fa fa-capsules','ti-pill','ti ti-pill'),
('fa-car-alt','fa fa-car-alt','ti-car','ti ti-car'),
('fa-car-battery','fa fa-car-battery','ti-battery-automotive','ti ti-battery-automotive'),
('fa-car-crash','fa fa-car-crash','ti-car-crash','ti ti-car-crash'),
('fa-car-side','fa fa-car-side','ti-car','ti ti-car'),
('fa-car','fa fa-car','ti-car','ti ti-car'),
('fa-caravan','fa fa-caravan','ti-caravan','ti ti-caravan'),
('fa-caret-down','fa fa-caret-down','ti-caret-down','ti ti-caret-down'),
('fa-caret-left','fa fa-caret-left','ti-caret-left','ti ti-caret-left'),
('fa-caret-right','fa fa-caret-right','ti-caret-right','ti ti-caret-right'),
('fa-caret-square-down','fa fa-caret-square-down','ti-circle-caret-down','ti ti-circle-caret-down'),
('fa-caret-square-left','fa fa-caret-square-left','ti-circle-caret-left','ti ti-circle-caret-left'),
('fa-caret-square-right','fa fa-caret-square-right','ti-circle-caret-right','ti ti-circle-caret-right'),
('fa-caret-square-up','fa fa-caret-square-up','ti-circle-caret-up','ti ti-circle-caret-up'),
('fa-caret-up','fa fa-caret-up','ti-caret-up','ti ti-caret-up'),
('fa-carrot','fa fa-carrot','ti-carrot','ti ti-carrot'),
('fa-cart-arrow-down','fa fa-cart-arrow-down','ti-shopping-cart-down','ti ti-shopping-cart-down'),
('fa-cart-plus','fa fa-cart-plus','ti-shopping-cart-plus','ti ti-shopping-cart-plus'),
('fa-cash-register','fa fa-cash-register','ti-cash-register','ti ti-cash-register'),
('fa-cat','fa fa-cat','ti-cat','ti ti-cat'),
('fa-certificate','fa fa-certificate','ti-certificate','ti ti-certificate'),
('fa-chair','fa fa-chair','ti-armchair','ti ti-armchair'),
('fa-chalkboard-teacher','fa fa-chalkboard-teacher','ti-chaulkboard-teacher','ti ti-chaulkboard-teacher'),
('fa-chalkboard','fa fa-chalkboard','ti-chalkboard','ti ti-chalkboard'),
('fa-charging-station','fa fa-charging-station','ti-battery-charging','ti ti-battery-charging'),
('fa-chart-area','fa fa-chart-area','ti-chart-area','ti ti-chart-area'),
('fa-chart-bar','fa fa-chart-bar','ti-chart-bar','ti ti-chart-bar'),
('fa-chart-line','fa fa-chart-line','ti-chart-line','ti ti-chart-line'),
('fa-chart-pie','fa fa-chart-pie','ti-chart-pie','ti ti-chart-pie'),
('fa-check-circle','fa fa-check-circle','ti-circle-check','ti ti-circle-check'),
('fa-check-double','fa fa-check-double','ti-checks','ti ti-checks'),
('fa-check-square','fa fa-check-square','ti-checkbox','ti ti-checkbox'),
('fa-check','fa fa-check','ti-check','ti ti-check'),
('fa-cheese','fa fa-cheese','ti-cheese','ti ti-cheese'),
('fa-chess-bishop','fa fa-chess-bishop','ti-chess-bishop','ti ti-chess-bishop'),
('fa-chess-board','fa fa-chess-board',null,null),
('fa-chess-king','fa fa-chess-king','ti-chess-king','ti ti-chess-king'),
('fa-chess-knight','fa fa-chess-knight','ti-chess-knight','ti ti-chess-knight'),
('fa-chess-pawn','fa fa-chess-pawn','ti-chess','ti ti-chess'),
('fa-chess-queen','fa fa-chess-queen','ti-chess-queen','ti ti-chess-queen'),
('fa-chess-rook','fa fa-chess-rook','ti-chess-rook','ti ti-chess-rook'),
('fa-chess','fa fa-chess','ti-chess','ti ti-chess'),
('fa-chevron-circle-down','fa fa-chevron-circle-down','ti-circle-chevron-down','ti ti-circle-chevron-down'),
('fa-chevron-circle-left','fa fa-chevron-circle-left','ti-circle-chevron-left','ti ti-circle-chevron-left'),
('fa-chevron-circle-right','fa fa-chevron-circle-right','ti-circle-chevron-right','ti ti-circle-chevron-right'),
('fa-chevron-circle-up','fa fa-chevron-circle-up','ti-circle-chevron-up','ti ti-circle-chevron-up'),
('fa-chevron-down','fa fa-chevron-down','ti-chevron-down','ti ti-chevron-down'),
('fa-chevron-left','fa fa-chevron-left','ti-chevron-left','ti ti-chevron-left'),
('fa-chevron-right','fa fa-chevron-right','ti-chevron-right','ti ti-chevron-right'),
('fa-chevron-up','fa fa-chevron-up','ti-chevron-up','ti ti-chevron-up'),
('fa-child','fa fa-child',null,null),
('fa-church','fa fa-church','ti-building-church','ti ti-building-church'),
('fa-circle-notch','fa fa-circle-notch',null,null),
('fa-circle','fa fa-circle','ti-circle','ti ti-circle'),
('fa-city','fa fa-city','ti-building-skyscraper','ti ti-building-skyscraper'),
('fa-clinic-medical','fa fa-clinic-medical',null,null),
('fa-clipboard-check','fa fa-clipboard-check','ti-clipboard-check','ti ti-clipboard-check'),
('fa-clipboard-list','fa fa-clipboard-list','ti-clipboard-list','ti ti-clipboard-list'),
('fa-clipboard','fa fa-clipboard','ti-clipboard','ti ti-clipboard'),
('fa-clock','fa fa-clock','ti-clock','ti ti-clock'),
('fa-clone','fa fa-clone','ti-copy','ti ti-copy'),
('fa-closed-captioning','fa fa-closed-captioning','ti-badge-cc','ti ti-badge-cc'),
('fa-cloud-download-alt','fa fa-cloud-download-alt','ti-cloud-down','ti ti-cloud-down'),
('fa-cloud-meatball','fa fa-cloud-meatball',null,null),
('fa-cloud-moon-rain','fa fa-cloud-moon-rain',null,null),
('fa-cloud-moon','fa fa-cloud-moon',null,null),
('fa-cloud-rain','fa fa-cloud-rain','ti-cloud-rain','ti ti-cloud-rain'),
('fa-cloud-showers-heavy','fa fa-cloud-showers-heavy',null,null),
('fa-cloud-sun-rain','fa fa-cloud-sun-rain',null,null),
('fa-cloud-sun','fa fa-cloud-sun',null,null),
('fa-cloud-upload-alt','fa fa-cloud-upload-alt','ti-cloud-upload','ti ti-cloud-upload'),
('fa-cloud','fa fa-cloud','ti-cloud','ti ti-cloud'),
('fa-cocktail','fa fa-cocktail','ti-glass-cocktail','ti ti-glass-cocktail'),
('fa-code-branch','fa fa-code-branch','ti-git-branch','ti ti-git-branch'),
('fa-code','fa fa-code','ti-code','ti ti-code'),
('fa-coffee','fa fa-coffee','ti-coffee','ti ti-coffee'),
('fa-cog','fa fa-cog','ti-setting','ti ti-setting'),
('fa-cogs','fa fa-cogs',null,null),
('fa-coins','fa fa-coins','ti-coins','ti ti-coins'),
('fa-columns','fa fa-columns','ti-columns','ti ti-columns'),
('fa-comment-alt','fa fa-comment-alt','ti-message','ti ti-message'),
('fa-comment-dollar','fa fa-comment-dollar','ti-message-dollar','ti ti-message-dollar'),
('fa-comment-dots','fa fa-comment-dots','ti-message-dots','ti ti-message-dots'),
('fa-comment-medical','fa fa-comment-medical','ti-message-plus','ti ti-message-plus'),
('fa-comment-slash','fa fa-comment-slash','ti-message-off','ti ti-message-off'),
('fa-comment','fa fa-comment','ti-message','ti ti-message'),
('fa-comments-dollar','fa fa-comments-dollar',null,null),
('fa-comments','fa fa-comments','ti-messages','ti ti-messages'),
('fa-compact-disc','fa fa-compact-disc','ti-disc','ti ti-disc'),
('fa-compass','fa fa-compass','ti-compass','ti ti-compass'),
('fa-compress-alt','fa fa-compress-alt','ti-arrows-diagonal-minimize-2','ti ti-arrows-diagonal-minimize-2'),
('fa-compress-arrows-alt','fa fa-compress-arrows-alt','ti-arrows-minimize','ti ti-arrows-minimize'),
('fa-compress','fa fa-compress','ti-minimize','ti ti-minimize'),
('fa-concierge-bell','fa fa-concierge-bell','ti-bell','ti ti-bell'),
('fa-cookie-bite','fa fa-cookie-bite','ti-cookie','ti ti-cookie'),
('fa-cookie','fa fa-cookie','ti-cookie','ti ti-cookie'),
('fa-copy','fa fa-copy','ti-copy','ti ti-copy'),
('fa-copyright','fa fa-copyright','ti-copyright','ti ti-copyright'),
('fa-couch','fa fa-couch','ti-sofa','ti ti-sofa'),
('fa-credit-card','fa fa-credit-card','ti-credit-card','ti ti-credit-card'),
('fa-crop-alt','fa fa-crop-alt','ti-crop','ti ti-crop'),
('fa-crop','fa fa-crop','ti-crop','ti ti-crop'),
('fa-cross','fa fa-cross','ti-cross','ti ti-cross'),
('fa-crosshairs','fa fa-crosshairs','ti-viewfinder','ti ti-viewfinder'),
('fa-crow','fa fa-crow',null,null),
('fa-crown','fa fa-crown','ti-crown','ti ti-crown'),
('fa-crutch','fa fa-crutch','ti-crutches','ti ti-crutches'),
('fa-cube','fa fa-cube','ti-cube','ti ti-cube'),
('fa-cubes','fa fa-cubes','ti-packages','ti ti-packages'),
('fa-cut','fa fa-cut','ti-cut','ti ti-cut'),
('fa-database','fa fa-database','ti-database','ti ti-database'),
('fa-deaf','fa fa-deaf','ti-ear-off','ti ti-ear-off'),
('fa-democrat','fa fa-democrat','ti-horse','ti ti-horse'),
('fa-desktop','fa fa-desktop','ti-device-desktop','ti ti-device-desktop'),
('fa-dharmachakra','fa fa-dharmachakra','ti-wheel','ti ti-wheel'),
('fa-diagnoses','fa fa-diagnoses',null,null),
('fa-dice-d20','fa fa-dice-d20',null,null),
('fa-dice-d6','fa fa-dice-d6',null,null),
('fa-dice-five','fa fa-dice-five','ti-dice-5','ti ti-dice-5'),
('fa-dice-four','fa fa-dice-four','ti-dice-4','ti ti-dice-4'),
('fa-dice-one','fa fa-dice-one','ti-dice-1','ti ti-dice-1'),
('fa-dice-six','fa fa-dice-six','ti-dice-6','ti ti-dice-6'),
('fa-dice-three','fa fa-dice-three','ti-dice-3','ti ti-dice-3'),
('fa-dice-two','fa fa-dice-two','ti-dice-2','ti ti-dice-2'),
('fa-dice','fa fa-dice','ti-dice','ti ti-dice'),
('fa-digital-tachograph','fa fa-digital-tachograph','ti-radio','ti ti-radio'),
('fa-directions','fa fa-directions','ti-directions','ti ti-directions'),
('fa-disease','fa fa-disease','ti-virus','ti ti-virus'),
('fa-divide','fa fa-divide','ti-divide','ti ti-divide'),
('fa-dizzy','fa fa-dizzy','ti-mood-sad-dizzy','ti ti-mood-sad-dizzy'),
('fa-dna','fa fa-dna','ti-dna','ti ti-dna'),
('fa-dog','fa fa-dog','ti-dog','ti ti-dog'),
('fa-dollar-sign','fa fa-dollar-sign','ti-currency-dollar','ti ti-currency-dollar'),
('fa-dolly-flatbed','fa fa-dolly-flatbed',null,null),
('fa-dolly','fa fa-dolly',null,null),
('fa-donate','fa fa-donate','ti-coin','ti ti-coin'),
('fa-door-closed','fa fa-door-closed','ti-door','ti ti-door'),
('fa-door-open','fa fa-door-open','ti-door-enter','ti ti-door-enter'),
('fa-dot-circle','fa fa-dot-circle','ti-circle-dot','ti ti-circle-dot'),
('fa-dove','fa fa-dove',null,null),
('fa-download','fa fa-download','ti-download','ti ti-download'),
('fa-drafting-compass','fa fa-drafting-compass','ti-geometry','ti ti-geometry'),
('fa-dragon','fa fa-dragon',null,null),
('fa-draw-polygon','fa fa-draw-polygon','ti-polygon','ti ti-polygon'),
('fa-drum-steelpan','fa fa-drum-steelpan',null,null),
('fa-drum','fa fa-drum',null,null),
('fa-drumstick-bite','fa fa-drumstick-bite','ti-meat','ti ti-meat'),
('fa-dumbbell','fa fa-dumbbell','ti-barbell','ti ti-barbell'),
('fa-dumpster-fire','fa fa-dumpster-fire',null,null),
('fa-dumpster','fa fa-dumpster','ti-trash','ti ti-trash'),
('fa-dungeon','fa fa-dungeon','ti-prison','ti ti-prison'),
('fa-edit','fa fa-edit','ti-edit','ti ti-edit'),
('fa-egg','fa fa-egg','ti-egg','ti ti-egg'),
('fa-eject','fa fa-eject','ti-player-eject','ti ti-player-eject'),
('fa-ellipsis-h','fa fa-ellipsis-h','ti-dots','ti ti-dots'),
('fa-ellipsis-v','fa fa-ellipsis-v','ti-dots-vertical','ti ti-dots-vertical'),
('fa-envelope-open-text','fa fa-envelope-open-text','ti-mail-opened','ti ti-mail-opened'),
('fa-envelope-open','fa fa-envelope-open','ti-mail-opened','ti ti-mail-opened'),
('fa-envelope-square','fa fa-envelope-square','ti-inbox','ti ti-inbox'),
('fa-envelope','fa fa-envelope','ti-mail','ti ti-mail'),
('fa-equals','fa fa-equals','ti-equal','ti ti-equal'),
('fa-eraser','fa fa-eraser','ti-eraser','ti ti-eraser'),
('fa-ethernet','fa fa-ethernet',null,null),
('fa-euro-sign','fa fa-euro-sign','ti-currency-euro','ti ti-currency-euro'),
('fa-exchange-alt','fa fa-exchange-alt','ti-arrows-right-left','ti ti-arrows-right-left'),
('fa-exclamation-circle','fa fa-exclamation-circle','ti-exclamation-circle','ti ti-exclamation-circle'),
('fa-exclamation-triangle','fa fa-exclamation-triangle','ti-alert-triangle','ti ti-alert-triangle'),
('fa-exclamation','fa fa-exclamation','ti-exclamation-mark','ti ti-exclamation-mark'),
('fa-expand-alt','fa fa-expand-alt','ti-arrows-diagonal','ti ti-arrows-diagonal'),
('fa-expand-arrows-alt','fa fa-expand-arrows-alt','ti-arrows-maximize','ti ti-arrows-maximize'),
('fa-expand','fa fa-expand','ti-maximize','ti ti-maximize'),
('fa-external-link-alt','fa fa-external-link-alt','ti-external-link','ti ti-external-link'),
('fa-external-link-square-alt','fa fa-external-link-square-alt','ti-external-link','ti ti-external-link'),
('fa-eye-dropper','fa fa-eye-dropper','ti-color-swatch','ti ti-color-swatch'),
('fa-eye-slash','fa fa-eye-slash','ti-eye-off','ti ti-eye-off'),
('fa-eye','fa fa-eye','ti-eye','ti ti-eye'),
('fa-fan','fa fa-fan','ti-car-fan','ti ti-car-fan'),
('fa-fast-backward','fa fa-fast-backward','ti-player-skip-back','ti ti-player-skip-back'),
('fa-fast-forward','fa fa-fast-forward','ti-player-skip-forward','ti ti-player-skip-forward'),
('fa-faucet','fa fa-faucet','ti-droplets','ti ti-droplets'),
('fa-fax','fa fa-fax','ti-landline','ti ti-landline'),
('fa-feather-alt','fa fa-feather-alt',null,null),
('fa-feather','fa fa-feather','ti-feather','ti ti-feather'),
('fa-female','fa fa-female','ti-woman','ti ti-woman'),
('fa-fighter-jet','fa fa-fighter-jet','ti-plane','ti ti-plane'),
('fa-file-alt','fa fa-file-alt','ti-file','ti ti-file'),
('fa-file-archive','fa fa-file-archive','ti-file-zip','ti ti-file-zip'),
('fa-file-audio','fa fa-file-audio','ti-file-music','ti ti-file-music'),
('fa-file-code','fa fa-file-code','ti-file-code','ti ti-file-code'),
('fa-file-contract','fa fa-file-contract','ti-file-dollar','ti ti-file-dollar'),
('fa-file-csv','fa fa-file-csv','ti-file-spreadsheet','ti ti-file-spreadsheet'),
('fa-file-download','fa fa-file-download','ti-file-download','ti ti-file-download'),
('fa-file-excel','fa fa-file-excel','ti-file-excel','ti ti-file-excel'),
('fa-file-export','fa fa-file-export','ti-file-export','ti ti-file-export'),
('fa-file-image','fa fa-file-image','ti-file-pencil','ti ti-file-pencil'),
('fa-file-import','fa fa-file-import','ti-file-import','ti ti-file-import'),
('fa-file-invoice-dollar','fa fa-file-invoice-dollar','ti-file-dollar','ti ti-file-dollar'),
('fa-file-invoice','fa fa-file-invoice','ti-file-invoice','ti ti-file-invoice'),
('fa-file-medical-alt','fa fa-file-medical-alt',null,null),
('fa-file-medical','fa fa-file-medical','ti-file-plus','ti ti-file-plus'),
('fa-file-pdf','fa fa-file-pdf','ti-file-description','ti ti-file-description'),
('fa-file-powerpoint','fa fa-file-powerpoint','ti-file-power','ti ti-file-power'),
('fa-file-prescription','fa fa-file-prescription','ti-file-plus','ti ti-file-plus'),
('fa-file-signature','fa fa-file-signature','ti-file-invoice','ti ti-file-invoice'),
('fa-file-upload','fa fa-file-upload','ti-file-upload','ti ti-file-upload'),
('fa-file-video','fa fa-file-video','ti-video','ti ti-video'),
('fa-file-word','fa fa-file-word','ti-file-word','ti ti-file-word'),
('fa-file','fa fa-file','ti-file','ti ti-file'),
('fa-fill-drip','fa fa-fill-drip','ti-bucket-droplet','ti ti-bucket-droplet'),
('fa-fill','fa fa-fill','ti-bucket-droplet','ti ti-bucket-droplet'),
('fa-film','fa fa-film','ti-movie','ti ti-movie'),
('fa-filter','fa fa-filter','ti-filter','ti ti-filter'),
('fa-fingerprint','fa fa-fingerprint','ti-fingerprint','ti ti-fingerprint'),
('fa-fire-alt','fa fa-fire-alt','ti-flame','ti ti-flame'),
('fa-fire-extinguisher','fa fa-fire-extinguisher','ti-fire-extinguisher','ti ti-fire-extinguisher'),
('fa-fire','fa fa-fire','ti-flame','ti ti-flame'),
('fa-first-aid','fa fa-first-aid','ti-first-aid-kit','ti ti-first-aid-kit'),
('fa-fish','fa fa-fish','ti-fish','ti ti-fish'),
('fa-fist-raised','fa fa-fist-raised','ti-hand-grab','ti ti-hand-grab'),
('fa-flag-checkered','fa fa-flag-checkered','ti-flag-2','ti ti-flag-2'),
('fa-flag-usa','fa fa-flag-usa','ti-flag','ti ti-flag'),
('fa-flag','fa fa-flag','ti-flag','ti ti-flag'),
('fa-flask','fa fa-flask','ti-flask','ti ti-flask'),
('fa-flushed','fa fa-flushed','ti-mood-silence','ti ti-mood-silence'),
('fa-folder-minus','fa fa-folder-minus','ti-folder-minus','ti ti-folder-minus'),
('fa-folder-open','fa fa-folder-open','ti-folder-open','ti ti-folder-open'),
('fa-folder-plus','fa fa-folder-plus','ti-folder-plus','ti ti-folder-plus'),
('fa-folder','fa fa-folder','ti-folder','ti ti-folder'),
('fa-font-awesome-logo-full','fa fa-font-awesome-logo-full','ti-flag','ti ti-flag'),
('fa-font','fa fa-font','ti-typography','ti ti-typography'),
('fa-football-ball','fa fa-football-ball','ti-ball-american-football','ti ti-ball-american-football'),
('fa-forward','fa fa-forward','ti-player-track-next','ti ti-player-track-next'),
('fa-frog','fa fa-frog',null,null),
('fa-frown-open','fa fa-frown-open','ti-mood-sad','ti ti-mood-sad'),
('fa-frown','fa fa-frown','ti-mood-sad','ti ti-mood-sad'),
('fa-funnel-dollar','fa fa-funnel-dollar','ti-filter-dollar','ti ti-filter-dollar'),
('fa-futbol','fa fa-futbol','ti-ball-football','ti ti-ball-football'),
('fa-gamepad','fa fa-gamepad','ti-device-gamepad','ti ti-device-gamepad'),
('fa-gas-pump','fa fa-gas-pump','ti-gas-station','ti ti-gas-station'),
('fa-gavel','fa fa-gavel','ti-gavel','ti ti-gavel'),
('fa-gem','fa fa-gem','ti-diamond','ti ti-diamond'),
('fa-genderless','fa fa-genderless','ti-gender-agender','ti ti-gender-agender'),
('fa-ghost','fa fa-ghost','ti-ghost','ti ti-ghost'),
('fa-gift','fa fa-gift','ti-gift','ti ti-gift'),
('fa-gifts','fa fa-gifts',null,null),
('fa-glass-cheers','fa fa-glass-cheers',null,null),
('fa-glass-martini-alt','fa fa-glass-martini-alt','ti-glass-cocktail','ti ti-glass-cocktail'),
('fa-glass-martini','fa fa-glass-martini','ti-glass-cocktail','ti ti-glass-cocktail'),
('fa-glass-whiskey','fa fa-glass-whiskey','ti-glass-gin','ti ti-glass-gin'),
('fa-glasses','fa fa-glasses','ti-eyeglass','ti ti-eyeglass'),
('fa-globe-africa','fa fa-globe-africa','ti-globe','ti ti-globe'),
('fa-globe-americas','fa fa-globe-americas','ti-globe','ti ti-globe'),
('fa-globe-asia','fa fa-globe-asia','ti-globe','ti ti-globe'),
('fa-globe-europe','fa fa-globe-europe','ti-globe','ti ti-globe'),
('fa-globe','fa fa-globe','ti-globe','ti ti-globe'),
('fa-golf-ball','fa fa-golf-ball','ti-golf','ti ti-golf'),
('fa-gopuram','fa fa-gopuram','ti-building-pavilion','ti ti-building-pavilion'),
('fa-graduation-cap','fa fa-graduation-cap',null,null),
('fa-greater-than-equal','fa fa-greater-than-equal','ti-math-equal-greater','ti ti-math-equal-greater'),
('fa-greater-than','fa fa-greater-than','ti-math-greater','ti ti-math-greater'),
('fa-grimace','fa fa-grimace','ti-mood-sick','ti ti-mood-sick'),
('fa-grin-alt','fa fa-grin-alt','ti-mood-happy','ti ti-mood-happy'),
('fa-grin-beam-sweat','fa fa-grin-beam-sweat',null,null),
('fa-grin-beam','fa fa-grin-beam',null,null),
('fa-grin-hearts','fa fa-grin-hearts',null,null),
('fa-grin-squint-tears','fa fa-grin-squint-tears','ti-mood-xd','ti ti-mood-xd'),
('fa-grin-squint','fa fa-grin-squint',null,null),
('fa-grin-stars','fa fa-grin-stars',null,null),
('fa-grin-tears','fa fa-grin-tears',null,null),
('fa-grin-tongue-squint','fa fa-grin-tongue-squint',null,null),
('fa-grin-tongue-wink','fa fa-grin-tongue-wink','ti-mood-tongue-wink','ti ti-mood-tongue-wink'),
('fa-grin-tongue','fa fa-grin-tongue','ti-mood-tongue','ti ti-mood-tongue'),
('fa-grin-wink','fa fa-grin-wink','ti-mood-wink','ti ti-mood-wink'),
('fa-grin','fa fa-grin',null,null),
('fa-grip-horizontal','fa fa-grip-horizontal','ti-grip-horizontal','ti ti-grip-horizontal'),
('fa-grip-lines-vertical','fa fa-grip-lines-vertical','ti-tallymark-2','ti ti-tallymark-2'),
('fa-grip-lines','fa fa-grip-lines','ti-equal','ti ti-equal'),
('fa-grip-vertical','fa fa-grip-vertical','ti-grip-vertical','ti ti-grip-vertical'),
('fa-guitar','fa fa-guitar',null,null),
('fa-h-square','fa fa-h-square','ti-hospital','ti ti-hospital'),
('fa-hamburger','fa fa-hamburger','ti-burger','ti ti-burger'),
('fa-hammer','fa fa-hammer','ti-hammer','ti ti-hammer'),
('fa-hamsa','fa fa-hamsa',null,null),
('fa-hand-holding-heart','fa fa-hand-holding-heart',null,null),
('fa-hand-holding-medical','fa fa-hand-holding-medical',null,null),
('fa-hand-holding-usd','fa fa-hand-holding-usd',null,null),
('fa-hand-holding-water','fa fa-hand-holding-water',null,null),
('fa-hand-holding','fa fa-hand-holding',null,null),
('fa-hand-lizard','fa fa-hand-lizard',null,null),
('fa-hand-middle-finger','fa fa-hand-middle-finger','ti-hand-middle-finger','ti ti-hand-middle-finger'),
('fa-hand-paper','fa fa-hand-paper','ti-hand-stop','ti ti-hand-stop'),
('fa-hand-peace','fa fa-hand-peace','ti-hand-two-fingers','ti ti-hand-two-fingers'),
('fa-hand-point-down','fa fa-hand-point-down',null,null),
('fa-hand-point-left','fa fa-hand-point-left',null,null),
('fa-hand-point-right','fa fa-hand-point-right',null,null),
('fa-hand-point-up','fa fa-hand-point-up','ti-hand-finger','ti ti-hand-finger'),
('fa-hand-pointer','fa fa-hand-pointer','ti-hand-finger','ti ti-hand-finger'),
('fa-hand-rock','fa fa-hand-rock','ti-hand-grab','ti ti-hand-grab'),
('fa-hand-scissors','fa fa-hand-scissors',null,null),
('fa-hand-sparkles','fa fa-hand-sparkles',null,null),
('fa-hand-spock','fa fa-hand-spock',null,null),
('fa-hands-helping','fa fa-hands-helping','ti-heart-handshake','ti ti-heart-handshake'),
('fa-hands-wash','fa fa-hands-wash','ti-wash-hand','ti ti-wash-hand'),
('fa-hands','fa fa-hands',null,null),
('fa-handshake-alt-slash','fa fa-handshake-alt-slash',null,null),
('fa-handshake-slash','fa fa-handshake-slash',null,null),
('fa-handshake','fa fa-handshake',null,null),
('fa-hanukiah','fa fa-hanukiah','ti-menorah','ti ti-menorah'),
('fa-hard-hat','fa fa-hard-hat','ti-helmet','ti ti-helmet'),
('fa-hashtag','fa fa-hashtag','ti-hash','ti ti-hash'),
('fa-hat-cowboy-side','fa fa-hat-cowboy-side',null,null),
('fa-hat-cowboy','fa fa-hat-cowboy',null,null),
('fa-hat-wizard','fa fa-hat-wizard',null,null),
('fa-l.','fa fa-l.',null,null),
('fa-head-side-cough-slash','fa fa-head-side-cough-slash',null,null),
('fa-head-side-cough','fa fa-head-side-cough',null,null),
('fa-head-side-mask','fa fa-head-side-mask',null,null),
('fa-head-side-virus','fa fa-head-side-virus',null,null),
('fa-heading','fa fa-heading','ti-heading','ti ti-heading'),
('fa-headphones-alt','fa fa-headphones-alt','ti-headphones','ti ti-headphones'),
('fa-headphones','fa fa-headphones','ti-headphones','ti ti-headphones'),
('fa-headset','fa fa-headset','ti-headset','ti ti-headset'),
('fa-heart-broken','fa fa-heart-broken','ti-heart-broken','ti ti-heart-broken'),
('fa-heart','fa fa-heart','ti-heart','ti ti-heart'),
('fa-heartbeat','fa fa-heartbeat','ti-heartbeat','ti ti-heartbeat'),
('fa-helicopter','fa fa-helicopter','ti-helicopter','ti ti-helicopter'),
('fa-highlighter','fa fa-highlighter','ti-highlight','ti ti-highlight'),
('fa-hiking','fa fa-hiking','ti-trekking','ti ti-trekking'),
('fa-hippo','fa fa-hippo',null,null),
('fa-history','fa fa-history','ti-history','ti ti-history'),
('fa-hockey-puck','fa fa-hockey-puck',null,null),
('fa-holly-berry','fa fa-holly-berry',null,null),
('fa-home','fa fa-home','ti-home','ti ti-home'),
('fa-horse-head','fa fa-horse-head',null,null),
('fa-horse','fa fa-horse','ti-horse','ti ti-horse'),
('fa-hospital-alt','fa fa-hospital-alt','ti-building-hospital','ti ti-building-hospital'),
('fa-hospital-symbol','fa fa-hospital-symbol','ti-hospital-circle','ti ti-hospital-circle'),
('fa-hospital-user','fa fa-hospital-user',null,null),
('fa-hospital','fa fa-hospital','ti-hospital','ti ti-hospital'),
('fa-hot-tub','fa fa-hot-tub',null,null),
('fa-hotdog','fa fa-hotdog',null,null),
('fa-hotel','fa fa-hotel','ti-building','ti ti-building'),
('fa-hourglass-end','fa fa-hourglass-end','ti-hourglass-low','ti ti-hourglass-low'),
('fa-hourglass-half','fa fa-hourglass-half','ti-hourglass','ti ti-hourglass'),
('fa-hourglass-start','fa fa-hourglass-start','ti-hourglass-high','ti ti-hourglass-high'),
('fa-hourglass','fa fa-hourglass','ti-hourglass','ti ti-hourglass'),
('fa-house-damage','fa fa-house-damage',null,null),
('fa-house-user','fa fa-house-user',null,null),
('fa-hryvnia','fa fa-hryvnia','ti-currency-hryvnia','ti ti-currency-hryvnia'),
('fa-i-cursor','fa fa-i-cursor','ti-cursor-text','ti ti-cursor-text'),
('fa-ice-cream','fa fa-ice-cream','ti-ice-cream-2','ti ti-ice-cream-2'),
('fa-icicles','fa fa-icicles',null,null),
('fa-icons','fa fa-icons','ti-icons','ti ti-icons'),
('fa-id-badge','fa fa-id-badge','ti-id-badge','ti ti-id-badge'),
('fa-id-card-alt','fa fa-id-card-alt','ti-id-badge-2','ti ti-id-badge-2'),
('fa-id-card','fa fa-id-card','ti-id','ti ti-id'),
('fa-igloo','fa fa-igloo',null,null),
('fa-image','fa fa-image','ti-photo','ti ti-photo'),
('fa-images','fa fa-images',null,null),
('fa-inbox','fa fa-inbox','ti-inbox','ti ti-inbox'),
('fa-indent','fa fa-indent','ti-indent-increase','ti ti-indent-increase'),
('fa-industry','fa fa-industry','ti-building-factory-2','ti ti-building-factory-2'),
('fa-infinity','fa fa-infinity','ti-infinity','ti ti-infinity'),
('fa-info-circle','fa fa-info-circle','ti-info-circle','ti ti-info-circle'),
('fa-info','fa fa-info','ti-info-small','ti ti-info-small'),
('fa-italic','fa fa-italic','ti-italic','ti ti-italic'),
('fa-jedi','fa fa-jedi',null,null),
('fa-joint','fa fa-joint','ti-smoking','ti ti-smoking'),
('fa-journal-whills','fa fa-journal-whills',null,null),
('fa-kaaba','fa fa-kaaba','ti-cube','ti ti-cube'),
('fa-key','fa fa-key','ti-key','ti ti-key'),
('fa-keyboard','fa fa-keyboard','ti-keyboard','ti ti-keyboard'),
('fa-khanda','fa fa-khanda',null,null),
('fa-kiss-beam','fa fa-kiss-beam',null,null),
('fa-kiss-wink-heart','fa fa-kiss-wink-heart',null,null),
('fa-kiss','fa fa-kiss',null,null),
('fa-kiwi-bird','fa fa-kiwi-bird',null,null),
('fa-landmark','fa fa-landmark','ti-building-arch','ti ti-building-arch'),
('fa-language','fa fa-language','ti-language','ti ti-language'),
('fa-laptop-code','fa fa-laptop-code',null,null),
('fa-laptop-house','fa fa-laptop-house',null,null),
('fa-laptop-medical','fa fa-laptop-medical',null,null),
('fa-laptop','fa fa-laptop','ti-device-laptop','ti ti-device-laptop'),
('fa-laugh-beam','fa fa-laugh-beam','ti-mood-happy','ti ti-mood-happy'),
('fa-laugh-squint','fa fa-laugh-squint',null,null),
('fa-laugh-wink','fa fa-laugh-wink',null,null),
('fa-laugh','fa fa-laugh',null,null),
('fa-layer-group','fa fa-layer-group','ti-stack','ti ti-stack'),
('fa-leaf','fa fa-leaf','ti-leaf','ti ti-leaf'),
('fa-lemon','fa fa-lemon','ti-lemon','ti ti-lemon'),
('fa-less-than-equal','fa fa-less-than-equal','ti-math-equal-lower','ti ti-math-equal-lower'),
('fa-less-than','fa fa-less-than','ti-math-lower','ti ti-math-lower'),
('fa-level-down-alt','fa fa-level-down-alt','ti-arrow-narrow-down','ti ti-arrow-narrow-down'),
('fa-level-up-alt','fa fa-level-up-alt','ti-arrow-narrow-up','ti ti-arrow-narrow-up'),
('fa-life-ring','fa fa-life-ring','ti-lifebuoy','ti ti-lifebuoy'),
('fa-lightbulb','fa fa-lightbulb','ti-bulb','ti ti-bulb'),
('fa-link','fa fa-link','ti-link','ti ti-link'),
('fa-lira-sign','fa fa-lira-sign','ti-currency-lira','ti ti-currency-lira'),
('fa-list-alt','fa fa-list-alt','ti-list-details','ti ti-list-details'),
('fa-list-ol','fa fa-list-ol','ti-list-numbers','ti ti-list-numbers'),
('fa-list-ul','fa fa-list-ul','ti-list','ti ti-list'),
('fa-list','fa fa-list','ti-list','ti ti-list'),
('fa-location-arrow','fa fa-location-arrow','ti-location','ti ti-location'),
('fa-lock-open','fa fa-lock-open','ti-lock-open','ti ti-lock-open'),
('fa-lock','fa fa-lock','ti-lock','ti ti-lock'),
('fa-long-arrow-alt-down','fa fa-long-arrow-alt-down','ti-arrow-narrow-down','ti ti-arrow-narrow-down'),
('fa-long-arrow-alt-left','fa fa-long-arrow-alt-left','ti-arrow-narrow-left','ti ti-arrow-narrow-left'),
('fa-long-arrow-alt-right','fa fa-long-arrow-alt-right','ti-arrow-narrow-right','ti ti-arrow-narrow-right'),
('fa-long-arrow-alt-up','fa fa-long-arrow-alt-up','ti-arrow-narrow-up','ti ti-arrow-narrow-up'),
('fa-low-vision','fa fa-low-vision','ti-eye-off','ti ti-eye-off'),
('fa-luggage-cart','fa fa-luggage-cart','ti-luggage','ti ti-luggage'),
('fa-lungs-virus','fa fa-lungs-virus','ti-lungs-off','ti ti-lungs-off'),
('fa-lungs','fa fa-lungs','ti-lungs','ti ti-lungs'),
('fa-magic','fa fa-magic','ti-wand','ti ti-wand'),
('fa-magnet','fa fa-magnet','ti-magnet','ti ti-magnet'),
('fa-mail-bulk','fa fa-mail-bulk',null,null),
('fa-male','fa fa-male','ti-man','ti ti-man'),
('fa-map-marked-alt','fa fa-map-marked-alt','ti-map-2','ti ti-map-2'),
('fa-map-marked','fa fa-map-marked',null,null),
('fa-map-marker-alt','fa fa-map-marker-alt','ti-map-pin','ti ti-map-pin'),
('fa-map-marker','fa fa-map-marker',null,null),
('fa-map-pin','fa fa-map-pin','ti-map-pin','ti ti-map-pin'),
('fa-map-signs','fa fa-map-signs','ti-directions','ti ti-directions'),
('fa-map','fa fa-map','ti-map','ti ti-map'),
('fa-marker','fa fa-marker','ti-writing','ti ti-writing'),
('fa-mars-double','fa fa-mars-double',null,null),
('fa-mars-stroke-h','fa fa-mars-stroke-h',null,null),
('fa-mars-stroke-v','fa fa-mars-stroke-v',null,null),
('fa-mars-stroke','fa fa-mars-stroke','ti-gender-androgyne','ti ti-gender-androgyne'),
('fa-mars','fa fa-mars','ti-mars','ti ti-mars'),
('fa-mask','fa fa-mask','ti-mask','ti ti-mask'),
('fa-medal','fa fa-medal','ti-medal','ti ti-medal'),
('fa-medkit','fa fa-medkit','ti-first-aid-kit','ti ti-first-aid-kit'),
('fa-meh-blank','fa fa-meh-blank','ti-mood-neutral','ti ti-mood-neutral'),
('fa-meh-rolling-eyes','fa fa-meh-rolling-eyes','ti-mood-look-up','ti ti-mood-look-up'),
('fa-meh','fa fa-meh','ti-mood-empty','ti ti-mood-empty'),
('fa-memory','fa fa-memory','ti-cpu','ti ti-cpu'),
('fa-menorah','fa fa-menorah','ti-menorah','ti ti-menorah'),
('fa-mercury','fa fa-mercury','ti-gender-hermaphrodite','ti ti-gender-hermaphrodite'),
('fa-meteor','fa fa-meteor','ti-meteor','ti ti-meteor'),
('fa-microchip','fa fa-microchip','ti-cpu-2','ti ti-cpu-2'),
('fa-microphone-alt-slash','fa fa-microphone-alt-slash','ti-microphone-off','ti ti-microphone-off'),
('fa-microphone-alt','fa fa-microphone-alt','ti-microphone','ti ti-microphone'),
('fa-microphone-slash','fa fa-microphone-slash','ti-microphone-2-off','ti ti-microphone-2-off'),
('fa-microphone','fa fa-microphone','ti-microphone-2','ti ti-microphone-2'),
('fa-microscope','fa fa-microscope','ti-microscope','ti ti-microscope'),
('fa-minus-circle','fa fa-minus-circle','ti-circle-minus','ti ti-circle-minus'),
('fa-minus-square','fa fa-minus-square','ti-square-rounded-minus','ti ti-square-rounded-minus'),
('fa-minus','fa fa-minus','ti-minus','ti ti-minus'),
('fa-mitten','fa fa-mitten',null,null),
('fa-mobile-alt','fa fa-mobile-alt','ti-device-mobile','ti ti-device-mobile'),
('fa-mobile','fa fa-mobile','ti-device-mobile','ti ti-device-mobile'),
('fa-money-bill-alt','fa fa-money-bill-alt','ti-cash-banknote','ti ti-cash-banknote'),
('fa-money-bill-wave-alt','fa fa-money-bill-wave-alt',null,null),
('fa-money-bill-wave','fa fa-money-bill-wave',null,null),
('fa-money-bill','fa fa-money-bill','ti-cash','ti ti-cash'),
('fa-money-check-alt','fa fa-money-check-alt',null,null),
('fa-money-check','fa fa-money-check',null,null),
('fa-monument','fa fa-monument','ti-building-monument','ti ti-building-monument'),
('fa-moon','fa fa-moon','ti-moon','ti ti-moon'),
('fa-mortar-pestle','fa fa-mortar-pestle','ti-bowl-spoon','ti ti-bowl-spoon'),
('fa-mosque','fa fa-mosque','ti-building-mosque','ti ti-building-mosque'),
('fa-motorcycle','fa fa-motorcycle','ti-motorbike','ti ti-motorbike'),
('fa-mountain','fa fa-mountain','ti-mountain','ti ti-mountain'),
('fa-mouse-pointer','fa fa-mouse-pointer','ti-pointer','ti ti-pointer'),
('fa-mouse','fa fa-mouse','ti-mouse','ti ti-mouse'),
('fa-mug-hot','fa fa-mug-hot','ti-coffee','ti ti-coffee'),
('fa-music','fa fa-music','ti-music','ti ti-music'),
('fa-network-wired','fa fa-network-wired','ti-schema','ti ti-schema'),
('fa-neuter','fa fa-neuter','ti-gender-neutrois','ti ti-gender-neutrois'),
('fa-newspaper','fa fa-newspaper','ti-news','ti ti-news'),
('fa-not-equal','fa fa-not-equal','ti-equal-not','ti ti-equal-not'),
('fa-notes-medical','fa fa-notes-medical','ti-clipboard-plus','ti ti-clipboard-plus'),
('fa-object-group','fa fa-object-group','ti-squares','ti ti-squares'),
('fa-object-ungroup','fa fa-object-ungroup','ti-squares','ti ti-squares'),
('fa-oil-can','fa fa-oil-can','ti-gas-station','ti ti-gas-station'),
('fa-om','fa fa-om','ti-om','ti ti-om'),
('fa-otter','fa fa-otter',null,null),
('fa-outdent','fa fa-outdent','ti-indent-decrease','ti ti-indent-decrease'),
('fa-pager','fa fa-pager',null,null),
('fa-paint-brush','fa fa-paint-brush','ti-brush','ti ti-brush'),
('fa-paint-roller','fa fa-paint-roller',null,null),
('fa-palette','fa fa-palette','ti-palette','ti ti-palette'),
('fa-pallet','fa fa-pallet',null,null),
('fa-paper-plane','fa fa-paper-plane','ti-send','ti ti-send'),
('fa-paperclip','fa fa-paperclip','ti-paperclip','ti ti-paperclip'),
('fa-parachute-box','fa fa-parachute-box','ti-parachute','ti ti-parachute'),
('fa-paragraph','fa fa-paragraph','ti-pilcrow','ti ti-pilcrow'),
('fa-parking','fa fa-parking','ti-parking','ti ti-parking'),
('fa-passport','fa fa-passport','ti-e-passport','ti ti-e-passport'),
('fa-pastafarianism','fa fa-pastafarianism',null,null),
('fa-paste','fa fa-paste','ti-clipboard-text','ti ti-clipboard-text'),
('fa-pause-circle','fa fa-pause-circle',null,null),
('fa-pause','fa fa-pause','ti-player-pause','ti ti-player-pause'),
('fa-paw','fa fa-paw','ti-paw','ti ti-paw'),
('fa-peace','fa fa-peace','ti-peace','ti ti-peace'),
('fa-pen-alt','fa fa-pen-alt','ti-ballpen','ti ti-ballpen'),
('fa-pen-fancy','fa fa-pen-fancy',null,null),
('fa-pen-nib','fa fa-pen-nib',null,null),
('fa-pen-square','fa fa-pen-square',null,null),
('fa-pen','fa fa-pen','ti-pencil','ti ti-pencil'),
('fa-pencil-alt','fa fa-pencil-alt','ti-pencil','ti ti-pencil'),
('fa-pencil-ruler','fa fa-pencil-ruler','ti-edit','ti ti-edit'),
('fa-people-arrows','fa fa-people-arrows','ti-friends','ti ti-friends'),
('fa-people-carry','fa fa-people-carry',null,null),
('fa-pepper-hot','fa fa-pepper-hot','ti-pepper','ti ti-pepper'),
('fa-percent','fa fa-percent',null,null),
('fa-percentage','fa fa-percentage','ti-percentage','ti ti-percentage'),
('fa-person-booth','fa fa-person-booth',null,null),
('fa-phone-alt','fa fa-phone-alt','ti-phone','ti ti-phone'),
('fa-phone-slash','fa fa-phone-slash','ti-phone-off','ti ti-phone-off'),
('fa-phone-square-alt','fa fa-phone-square-alt',null,null),
('fa-phone-square','fa fa-phone-square',null,null),
('fa-phone-volume','fa fa-phone-volume','ti-phone-call','ti ti-phone-call'),
('fa-phone','fa fa-phone','ti-phone','ti ti-phone'),
('fa-photo-video','fa fa-photo-video','ti-photo-video','ti ti-photo-video'),
('fa-piggy-bank','fa fa-piggy-bank',null,null),
('fa-pills','fa fa-pills','ti-pills','ti ti-pills'),
('fa-pizza-slice','fa fa-pizza-slice','ti-pizza','ti ti-pizza'),
('fa-place-of-worship','fa fa-place-of-worship',null,null),
('fa-plane-arrival','fa fa-plane-arrival','ti-plane-arrival','ti ti-plane-arrival'),
('fa-plane-departure','fa fa-plane-departure','ti-plane-departure','ti ti-plane-departure'),
('fa-plane-slash','fa fa-plane-slash','ti-plane-off','ti ti-plane-off'),
('fa-plane','fa fa-plane','ti-plane','ti ti-plane'),
('fa-play-circle','fa fa-play-circle',null,null),
('fa-play','fa fa-play','ti-player-play','ti ti-player-play'),
('fa-plug','fa fa-plug','ti-plug','ti ti-plug'),
('fa-plus-circle','fa fa-plus-circle','ti-circle-plus','ti ti-circle-plus'),
('fa-plus-square','fa fa-plus-square','ti-square-plus','ti ti-square-plus'),
('fa-plus','fa fa-plus','ti-plus','ti ti-plus'),
('fa-podcast','fa fa-podcast','ti-brand-apple-podcast','ti ti-brand-apple-podcast'),
('fa-poll-h','fa fa-poll-h','ti-notes','ti ti-notes'),
('fa-poll','fa fa-poll','ti-chart-bar','ti ti-chart-bar'),
('fa-poo-storm','fa fa-poo-storm',null,null),
('fa-poo','fa fa-poo','ti-poo','ti ti-poo'),
('fa-poop','fa fa-poop',null,null),
('fa-portrait','fa fa-portrait','ti-user','ti ti-user'),
('fa-pound-sign','fa fa-pound-sign','ti-currency-pound','ti ti-currency-pound'),
('fa-power-off','fa fa-power-off','ti-power','ti ti-power'),
('fa-pray','fa fa-pray','ti-pray','ti ti-pray'),
('fa-praying-hands','fa fa-praying-hands',null,null),
('fa-prescription-bottle-alt','fa fa-prescription-bottle-alt','ti-medicine-syrup','ti ti-medicine-syrup'),
('fa-prescription-bottle','fa fa-prescription-bottle','ti-medicine-syrup','ti ti-medicine-syrup'),
('fa-prescription','fa fa-prescription','ti-prescription','ti ti-prescription'),
('fa-print','fa fa-print','ti-printer','ti ti-printer'),
('fa-procedures','fa fa-procedures',null,null),
('fa-project-diagram','fa fa-project-diagram','ti-chart-dots-3','ti ti-chart-dots-3'),
('fa-pump-medical','fa fa-pump-medical','ti-medicine-syrup','ti ti-medicine-syrup'),
('fa-pump-soap','fa fa-pump-soap',null,null),
('fa-puzzle-piece','fa fa-puzzle-piece','ti-puzzle','ti ti-puzzle'),
('fa-qrcode','fa fa-qrcode','ti-qrcode','ti ti-qrcode'),
('fa-question-circle','fa fa-question-circle','ti-zoom-question','ti ti-zoom-question'),
('fa-question','fa fa-question','ti-question-mark','ti ti-question-mark'),
('fa-quidditch','fa fa-quidditch',null,null),
('fa-quote-left','fa fa-quote-left',null,null),
('fa-quote-right','fa fa-quote-right','ti-quote','ti ti-quote'),
('fa-quran','fa fa-quran',null,null),
('fa-radiation-alt','fa fa-radiation-alt',null,null),
('fa-radiation','fa fa-radiation','ti-radioactive','ti ti-radioactive'),
('fa-rainbow','fa fa-rainbow','ti-rainbow','ti ti-rainbow'),
('fa-random','fa fa-random','ti-arrows-shuffle','ti ti-arrows-shuffle'),
('fa-receipt','fa fa-receipt','ti-receipt','ti ti-receipt'),
('fa-record-vinyl','fa fa-record-vinyl','ti-vinyl','ti ti-vinyl'),
('fa-recycle','fa fa-recycle','ti-recycle','ti ti-recycle'),
('fa-redo-alt','fa fa-redo-alt',null,null),
('fa-redo','fa fa-redo','ti-reload','ti ti-reload'),
('fa-registered','fa fa-registered','ti-registered','ti ti-registered'),
('fa-remove-format','fa fa-remove-format','ti-clear-formatting','ti ti-clear-formatting'),
('fa-reply-all','fa fa-reply-all','ti-arrow-back-up-double','ti ti-arrow-back-up-double'),
('fa-reply','fa fa-reply','ti-arrow-back-up','ti ti-arrow-back-up'),
('fa-republican','fa fa-republican',null,null),
('fa-restroom','fa fa-restroom',null,null),
('fa-retweet','fa fa-retweet','ti-repeat','ti ti-repeat'),
('fa-ribbon','fa fa-ribbon','ti-ribbon-health','ti ti-ribbon-health'),
('fa-ring','fa fa-ring',null,null),
('fa-road','fa fa-road','ti-road','ti ti-road'),
('fa-robot','fa fa-robot','ti-robot','ti ti-robot'),
('fa-rocket','fa fa-rocket','ti-rocket','ti ti-rocket'),
('fa-route','fa fa-route','ti-route','ti ti-route'),
('fa-rss-square','fa fa-rss-square','ti-file-rss','ti ti-file-rss'),
('fa-rss','fa fa-rss','ti-rss','ti ti-rss'),
('fa-ruble-sign','fa fa-ruble-sign','ti-currency-rubel','ti ti-currency-rubel'),
('fa-ruler-combined','fa fa-ruler-combined','ti-ruler','ti ti-ruler'),
('fa-ruler-horizontal','fa fa-ruler-horizontal','ti-ruler-3','ti ti-ruler-3'),
('fa-ruler-vertical','fa fa-ruler-vertical','ti-ruler-2','ti ti-ruler-2'),
('fa-ruler','fa fa-ruler','ti-ruler','ti ti-ruler'),
('fa-running','fa fa-running','ti-run','ti ti-run'),
('fa-rupee-sign','fa fa-rupee-sign','ti-currency-rupee','ti ti-currency-rupee'),
('fa-sad-cry','fa fa-sad-cry',null,null),
('fa-sad-tear','fa fa-sad-tear','ti-mood-cry','ti ti-mood-cry'),
('fa-satellite-dish','fa fa-satellite-dish',null,null),
('fa-satellite','fa fa-satellite','ti-satellite','ti ti-satellite'),
('fa-save','fa fa-save','ti-device-floppy','ti ti-device-floppy'),
('fa-school','fa fa-school','ti-school','ti ti-school'),
('fa-screwdriver','fa fa-screwdriver',null,null),
('fa-scroll','fa fa-scroll','ti-contract','ti ti-contract'),
('fa-sd-card','fa fa-sd-card','ti-device-sd-card','ti ti-device-sd-card'),
('fa-search-dollar','fa fa-search-dollar','ti-zoom-money','ti ti-zoom-money'),
('fa-search-location','fa fa-search-location',null,null),
('fa-search-minus','fa fa-search-minus','ti-zoom-out','ti ti-zoom-out'),
('fa-search-plus','fa fa-search-plus','ti-zoom-in','ti ti-zoom-in'),
('fa-search','fa fa-search','ti-search','ti ti-search'),
('fa-seedling','fa fa-seedling','ti-seedling','ti ti-seedling'),
('fa-server','fa fa-server','ti-server','ti ti-server'),
('fa-shapes','fa fa-shapes','ti-icons','ti ti-icons'),
('fa-share-alt-square','fa fa-share-alt-square',null,null),
('fa-share-alt','fa fa-share-alt','ti-share','ti ti-share'),
('fa-share-square','fa fa-share-square',null,null),
('fa-share','fa fa-share','ti-share','ti ti-share'),
('fa-shekel-sign','fa fa-shekel-sign','ti-currency-shekel','ti ti-currency-shekel'),
('fa-shield-alt','fa fa-shield-alt','ti-shield-half','ti ti-shield-half'),
('fa-shield-virus','fa fa-shield-virus',null,null),
('fa-ship','fa fa-ship','ti-ship','ti ti-ship'),
('fa-shipping-fast','fa fa-shipping-fast','ti-truck-delivery','ti ti-truck-delivery'),
('fa-shoe-prints','fa fa-shoe-prints',null,null),
('fa-shopping-bag','fa fa-shopping-bag','ti-shopping-bag','ti ti-shopping-bag'),
('fa-shopping-basket','fa fa-shopping-basket','ti-basket','ti ti-basket'),
('fa-shopping-cart','fa fa-shopping-cart','ti-shopping-cart','ti ti-shopping-cart'),
('fa-shower','fa fa-shower',null,null),
('fa-shuttle-van','fa fa-shuttle-van',null,null),
('fa-sign-in-alt','fa fa-sign-in-alt',null,null),
('fa-sign-language','fa fa-sign-language',null,null),
('fa-sign-out-alt','fa fa-sign-out-alt',null,null),
('fa-sign','fa fa-sign','ti-sign-right','ti ti-sign-right'),
('fa-signal','fa fa-signal','ti-antenna-bars-5','ti ti-antenna-bars-5'),
('fa-signature','fa fa-signature','ti-signature','ti ti-signature'),
('fa-sim-card','fa fa-sim-card','ti-device-sim','ti ti-device-sim'),
('fa-sink','fa fa-sink',null,null),
('fa-sitemap','fa fa-sitemap','ti-sitemap','ti ti-sitemap'),
('fa-skating','fa fa-skating','ti-ice-skating','ti ti-ice-skating'),
('fa-skiing-nordic','fa fa-skiing-nordic',null,null),
('fa-skiing','fa fa-skiing',null,null),
('fa-skull-crossbones','fa fa-skull-crossbones',null,null),
('fa-skull','fa fa-skull','ti-skull','ti ti-skull'),
('fa-slash','fa fa-slash','ti-slash','ti ti-slash'),
('fa-sleigh','fa fa-sleigh','ti-sleigh','ti ti-sleigh'),
('fa-sliders-h','fa fa-sliders-h','ti-adjustments-horizontal','ti ti-adjustments-horizontal'),
('fa-smile-beam','fa fa-smile-beam','ti-mood-smile-beam','ti ti-mood-smile-beam'),
('fa-smile-wink','fa fa-smile-wink','ti-mood-wink','ti ti-mood-wink'),
('fa-smile','fa fa-smile','ti-mood-smile','ti ti-mood-smile'),
('fa-smog','fa fa-smog','ti-cloud-fog','ti ti-cloud-fog'),
('fa-smoking-ban','fa fa-smoking-ban','ti-smoking-no','ti ti-smoking-no'),
('fa-smoking','fa fa-smoking','ti-smoking','ti ti-smoking'),
('fa-sms','fa fa-sms','ti-device-mobile-message','ti ti-device-mobile-message'),
('fa-snowboarding','fa fa-snowboarding','ti-snowboarding','ti ti-snowboarding'),
('fa-snowflake','fa fa-snowflake','ti-snowflake','ti ti-snowflake'),
('fa-snowman','fa fa-snowman','ti-snowman','ti ti-snowman'),
('fa-snowplow','fa fa-snowplow',null,null),
('fa-soap','fa fa-soap',null,null),
('fa-socks','fa fa-socks','ti-sock','ti ti-sock'),
('fa-solar-panel','fa fa-solar-panel','ti-solar-panel','ti ti-solar-panel'),
('fa-sort-alpha-down-alt','fa fa-sort-alpha-down-alt','ti-sort-descending-letters','ti ti-sort-descending-letters'),
('fa-sort-alpha-down','fa fa-sort-alpha-down','ti-sort-ascending-letters','ti ti-sort-ascending-letters'),
('fa-sort-alpha-up-alt','fa fa-sort-alpha-up-alt',null,null),
('fa-sort-alpha-up','fa fa-sort-alpha-up',null,null),
('fa-sort-amount-down-alt','fa fa-sort-amount-down-alt',null,null),
('fa-sort-amount-down','fa fa-sort-amount-down','ti-sort-descending','ti ti-sort-descending'),
('fa-sort-amount-up-alt','fa fa-sort-amount-up-alt','ti-sort-ascending','ti ti-sort-ascending'),
('fa-sort-amount-up','fa fa-sort-amount-up',null,null),
('fa-sort-down','fa fa-sort-down',null,null),
('fa-sort-numeric-down-alt','fa fa-sort-numeric-down-alt','ti-sort-descending-numbers','ti ti-sort-descending-numbers'),
('fa-sort-numeric-down','fa fa-sort-numeric-down','ti-sort-ascending-numbers','ti ti-sort-ascending-numbers'),
('fa-sort-numeric-up-alt','fa fa-sort-numeric-up-alt',null,null),
('fa-sort-numeric-up','fa fa-sort-numeric-up',null,null),
('fa-sort-up','fa fa-sort-up','ti-caret-up','ti ti-caret-up'),
('fa-sort','fa fa-sort','ti-caret-up-down','ti ti-caret-up-down'),
('fa-spa','fa fa-spa','ti-flower','ti ti-flower'),
('fa-space-shuttle','fa fa-space-shuttle','ti-rocket','ti ti-rocket'),
('fa-spell-check','fa fa-spell-check','ti-text-spellcheck','ti ti-text-spellcheck'),
('fa-spider','fa fa-spider','ti-spider','ti ti-spider'),
('fa-spinner','fa fa-spinner','ti-rotate-2','ti ti-rotate-2'),
('fa-splotch','fa fa-splotch',null,null),
('fa-spray-can','fa fa-spray-can','ti-spray','ti ti-spray'),
('fa-square-full','fa fa-square-full','ti-square','ti ti-square'),
('fa-square-root-alt','fa fa-square-root-alt','ti-square-root-2','ti ti-square-root-2'),
('fa-square','fa fa-square','ti-square','ti ti-square'),
('fa-stamp','fa fa-stamp','ti-rubber-stamp','ti ti-rubber-stamp'),
('fa-star-and-crescent','fa fa-star-and-crescent',null,null),
('fa-star-half-alt','fa fa-star-half-alt','ti-star-half','ti ti-star-half'),
('fa-star-half','fa fa-star-half','ti-star-half','ti ti-star-half'),
('fa-star-of-david','fa fa-star-of-david','ti-jewish-star','ti ti-jewish-star'),
('fa-star-of-life','fa fa-star-of-life','ti-asterisk','ti ti-asterisk'),
('fa-star','fa fa-star','ti-star','ti ti-star'),
('fa-step-backward','fa fa-step-backward','ti-player-skip-back','ti ti-player-skip-back'),
('fa-step-forward','fa fa-step-forward','ti-player-skip-forward','ti ti-player-skip-forward'),
('fa-stethoscope','fa fa-stethoscope','ti-stethoscope','ti ti-stethoscope'),
('fa-sticky-note','fa fa-sticky-note','ti-sticker-2','ti ti-sticker-2'),
('fa-stop-circle','fa fa-stop-circle',null,null),
('fa-stop','fa fa-stop','ti-player-stop','ti ti-player-stop'),
('fa-stopwatch-20','fa fa-stopwatch-20',null,null),
('fa-stopwatch','fa fa-stopwatch','ti-alarm','ti ti-alarm'),
('fa-store-alt-slash','fa fa-store-alt-slash',null,null),
('fa-store-alt','fa fa-store-alt',null,null),
('fa-store-slash','fa fa-store-slash','ti-building-off','ti ti-building-off'),
('fa-store','fa fa-store','ti-building-store','ti ti-building-store'),
('fa-stream','fa fa-stream',null,null),
('fa-street-view','fa fa-street-view',null,null),
('fa-strikethrough','fa fa-strikethrough','ti-strikethrough','ti ti-strikethrough'),
('fa-stroopwafel','fa fa-stroopwafel',null,null),
('fa-subscript','fa fa-subscript','ti-subscript','ti ti-subscript'),
('fa-subway','fa fa-subway','ti-train','ti ti-train'),
('fa-suitcase-rolling','fa fa-suitcase-rolling','ti-luggage','ti ti-luggage'),
('fa-suitcase','fa fa-suitcase',null,null),
('fa-sun','fa fa-sun','ti-sun','ti ti-sun'),
('fa-superscript','fa fa-superscript','ti-superscript','ti ti-superscript'),
('fa-surprise','fa fa-surprise','ti-mood-surprised','ti ti-mood-surprised'),
('fa-swatchbook','fa fa-swatchbook','ti-color-swatch','ti ti-color-swatch'),
('fa-swimmer','fa fa-swimmer','ti-swimming','ti ti-swimming'),
('fa-swimming-pool','fa fa-swimming-pool','ti-pool','ti ti-pool'),
('fa-synagogue','fa fa-synagogue',null,null),
('fa-sync-alt','fa fa-sync-alt','ti-refresh','ti ti-refresh'),
('fa-sync','fa fa-sync',null,null),
('fa-syringe','fa fa-syringe','ti-vaccine','ti ti-vaccine'),
('fa-table-tennis','fa fa-table-tennis','ti-ping-pong','ti ti-ping-pong'),
('fa-table','fa fa-table','ti-table','ti ti-table'),
('fa-tablet-alt','fa fa-tablet-alt',null,null),
('fa-tablet','fa fa-tablet','ti-device-ipad','ti ti-device-ipad'),
('fa-tablets','fa fa-tablets','ti-pills','ti ti-pills'),
('fa-tachometer-alt','fa fa-tachometer-alt','ti-brand-speedtest','ti ti-brand-speedtest'),
('fa-tag','fa fa-tag','ti-tag','ti ti-tag'),
('fa-tags','fa fa-tags','ti-tags','ti ti-tags'),
('fa-tape','fa fa-tape',null,null),
('fa-tasks','fa fa-tasks','ti-list-check','ti ti-list-check'),
('fa-taxi','fa fa-taxi',null,null),
('fa-teeth-open','fa fa-teeth-open',null,null),
('fa-teeth','fa fa-teeth',null,null),
('fa-temperature-high','fa fa-temperature-high','ti-temperature-sun','ti ti-temperature-sun'),
('fa-temperature-low','fa fa-temperature-low','ti-temperature-snow','ti ti-temperature-snow'),
('fa-tenge','fa fa-tenge','ti-currency-tenge','ti ti-currency-tenge'),
('fa-terminal','fa fa-terminal','ti-terminal','ti ti-terminal'),
('fa-text-height','fa fa-text-height','ti-text-size','ti ti-text-size'),
('fa-text-width','fa fa-text-width',null,null),
('fa-th-large','fa fa-th-large','ti-border-all','ti ti-border-all'),
('fa-th-list','fa fa-th-list','ti-table','ti ti-table'),
('fa-th','fa fa-th',null,null),
('fa-theater-masks','fa fa-theater-masks','ti-masks-theater','ti ti-masks-theater'),
('fa-thermometer-empty','fa fa-thermometer-empty','ti-temperature-off','ti ti-temperature-off'),
('fa-thermometer-full','fa fa-thermometer-full',null,null),
('fa-thermometer-half','fa fa-thermometer-half','ti-temperature','ti ti-temperature'),
('fa-thermometer-quarter','fa fa-thermometer-quarter',null,null),
('fa-thermometer-three-quarters','fa fa-thermometer-three-quarters',null,null),
('fa-thermometer','fa fa-thermometer','ti-thermometer','ti ti-thermometer'),
('fa-thumbs-down','fa fa-thumbs-down','ti-thumb-down','ti ti-thumb-down'),
('fa-thumbs-up','fa fa-thumbs-up','ti-thumb-up','ti ti-thumb-up'),
('fa-thumbtack','fa fa-thumbtack','ti-pinned','ti ti-pinned'),
('fa-ticket-alt','fa fa-ticket-alt','ti-ticket','ti ti-ticket'),
('fa-times-circle','fa fa-times-circle','ti-circle-x','ti ti-circle-x'),
('fa-times','fa fa-times','ti-x','ti ti-x'),
('fa-tint-slash','fa fa-tint-slash','ti-droplet-off','ti ti-droplet-off'),
('fa-tint','fa fa-tint','ti-droplet','ti ti-droplet'),
('fa-tired','fa fa-tired','ti-mood-wrrr','ti ti-mood-wrrr'),
('fa-toggle-off','fa fa-toggle-off','ti-toggle-left','ti ti-toggle-left'),
('fa-toggle-on','fa fa-toggle-on','ti-toggle-righ','ti ti-toggle-righ')

INSERT INTO [__IconTransition] ([FontAwesomeClass], [FontAwesomeFull], [TablerClass], [TablerFull])
VALUES
('fa-toilet-paper-slash','fa fa-toilet-paper-slash','ti-toilet-paper-off','ti ti-toilet-paper-off'),
('fa-toilet-paper','fa fa-toilet-paper','ti-toilet-paper','ti ti-toilet-paper'),
('fa-toilet','fa fa-toilet',null,null),
('fa-toolbox','fa fa-toolbox',null,null),
('fa-tools','fa fa-tools','ti-tools','ti ti-tools'),
('fa-tooth','fa fa-tooth','ti-dental','ti ti-dental'),
('fa-torah','fa fa-torah',null,null),
('fa-torii-gate','fa fa-torii-gate','ti-torii','ti ti-torii'),
('fa-tractor','fa fa-tractor','ti-tractor','ti ti-tractor'),
('fa-trademark','fa fa-trademark','ti-trademark','ti ti-trademark'),
('fa-traffic-light','fa fa-traffic-light','ti-traffic-lights','ti ti-traffic-lights'),
('fa-trailer','fa fa-trailer','ti-caravan','ti ti-caravan'),
('fa-train','fa fa-train','ti-train','ti ti-train'),
('fa-tram','fa fa-tram','ti-aerial-lift','ti ti-aerial-lift'),
('fa-transgender-alt','fa fa-transgender-alt','ti-gender-transgender','ti ti-gender-transgender'),
('fa-transgender','fa fa-transgender','ti-gender-bigender','ti ti-gender-bigender'),
('fa-trash-alt','fa fa-trash-alt','ti-trash','ti ti-trash'),
('fa-trash-restore-alt','fa fa-trash-restore-alt',null,null),
('fa-trash-restore','fa fa-trash-restore',null,null),
('fa-trash','fa fa-trash','ti-trash','ti ti-trash'),
('fa-tree','fa fa-tree','ti-tree','ti ti-tree'),
('fa-trophy','fa fa-trophy','ti-trophy','ti ti-trophy'),
('fa-truck-loading','fa fa-truck-loading','ti-truck-loading','ti ti-truck-loading'),
('fa-truck-monster','fa fa-truck-monster',null,null),
('fa-truck-moving','fa fa-truck-moving','ti-truck','ti ti-truck'),
('fa-truck-pickup','fa fa-truck-pickup',null,null),
('fa-truck','fa fa-truck','ti-truck','ti ti-truck'),
('fa-tshirt','fa fa-tshirt','ti-shirt','ti ti-shirt'),
('fa-tty','fa fa-tty',null,null),
('fa-tv','fa fa-tv','ti-device-tv','ti ti-device-tv'),
('fa-umbrella-beach','fa fa-umbrella-beach','ti-beach','ti ti-beach'),
('fa-umbrella','fa fa-umbrella','ti-umbrella','ti ti-umbrella'),
('fa-underline','fa fa-underline','ti-underline','ti ti-underline'),
('fa-undo-alt','fa fa-undo-alt','ti-arrow-back-up','ti ti-arrow-back-up'),
('fa-undo','fa fa-undo',null,null),
('fa-universal-access','fa fa-universal-access',null,null),
('fa-university','fa fa-university','ti-building-bank','ti ti-building-bank'),
('fa-unlink','fa fa-unlink','ti-unlink','ti ti-unlink'),
('fa-unlock-alt','fa fa-unlock-alt','ti-lock-open','ti ti-lock-open'),
('fa-unlock','fa fa-unlock',null,null),
('fa-upload','fa fa-upload','ti-upload','ti ti-upload'),
('fa-user-alt-slash','fa fa-user-alt-slash','ti-user-off','ti ti-user-off'),
('fa-user-alt','fa fa-user-alt','ti-user','ti ti-user'),
('fa-user-astronaut','fa fa-user-astronaut',null,null),
('fa-user-check','fa fa-user-check','ti-user-check','ti ti-user-check'),
('fa-user-circle','fa fa-user-circle','ti-user-circle','ti ti-user-circle'),
('fa-user-clock','fa fa-user-clock',null,null),
('fa-user-cog','fa fa-user-cog','ti-user-cog','ti ti-user-cog'),
('fa-user-edit','fa fa-user-edit','ti-user-edit','ti ti-user-edit'),
('fa-user-friends','fa fa-user-friends','ti-users','ti ti-users'),
('fa-user-graduate','fa fa-user-graduate',null,null),
('fa-user-injured','fa fa-user-injured',null,null),
('fa-user-lock','fa fa-user-lock','ti-user-shield','ti ti-user-shield'),
('fa-user-md','fa fa-user-md',null,null),
('fa-user-minus','fa fa-user-minus','ti-user-minus','ti ti-user-minus'),
('fa-user-ninja','fa fa-user-ninja',null,null),
('fa-user-nurse','fa fa-user-nurse','ti-nurse','ti ti-nurse'),
('fa-user-plus','fa fa-user-plus','ti-user-plus','ti ti-user-plus'),
('fa-user-secret','fa fa-user-secret','ti-spy','ti ti-spy'),
('fa-user-shield','fa fa-user-shield','ti-user-shield','ti ti-user-shield'),
('fa-user-slash','fa fa-user-slash','ti-user-off','ti ti-user-off'),
('fa-user-tag','fa fa-user-tag','ti-user-dollar','ti ti-user-dollar'),
('fa-user-tie','fa fa-user-tie',null,null),
('fa-user-times','fa fa-user-times','ti-user-x','ti ti-user-x'),
('fa-user','fa fa-user','ti-user','ti ti-user'),
('fa-users-cog','fa fa-users-cog',null,null),
('fa-users-slash','fa fa-users-slash',null,null),
('fa-users','fa fa-users','ti-users','ti ti-users'),
('fa-utensil-spoon','fa fa-utensil-spoon',null,null),
('fa-utensils','fa fa-utensils','ti-tools-kitchen-2','ti ti-tools-kitchen-2'),
('fa-vector-square','fa fa-vector-square','ti-vector','ti ti-vector'),
('fa-venus-double','fa fa-venus-double',null,null),
('fa-venus-mars','fa fa-venus-mars',null,null),
('fa-venus','fa fa-venus','ti-venus','ti ti-venus'),
('fa-vest-patches','fa fa-vest-patches',null,null),
('fa-vest','fa fa-vest',null,null),
('fa-vial','fa fa-vial','ti-test-pipe','ti ti-test-pipe'),
('fa-vials','fa fa-vials',null,null),
('fa-video-slash','fa fa-video-slash','ti-video-off','ti ti-video-off'),
('fa-video','fa fa-video','ti-video','ti ti-video'),
('fa-vihara','fa fa-vihara','ti-building-pavilion','ti ti-building-pavilion'),
('fa-virus-slash','fa fa-virus-slash','ti-virus-off','ti ti-virus-off'),
('fa-virus','fa fa-virus','ti-virus','ti ti-virus'),
('fa-viruses','fa fa-viruses',null,null),
('fa-voicemail','fa fa-voicemail','ti-record-mail','ti ti-record-mail'),
('fa-volleyball-ball','fa fa-volleyball-ball','ti-ball-volleyball','ti ti-ball-volleyball'),
('fa-volume-down','fa fa-volume-down','ti-volume-2','ti ti-volume-2'),
('fa-volume-mute','fa fa-volume-mute','ti-volume-3','ti ti-volume-3'),
('fa-volume-off','fa fa-volume-off','ti-volume-off','ti ti-volume-off'),
('fa-volume-up','fa fa-volume-up','ti-volume','ti ti-volume'),
('fa-vote-yea','fa fa-vote-yea','ti-checkbox','ti ti-checkbox'),
('fa-vr-cardboard','fa fa-vr-cardboard','ti-cardboards','ti ti-cardboards'),
('fa-walking','fa fa-walking','ti-walk','ti ti-walk'),
('fa-wallet','fa fa-wallet','ti-wallet','ti ti-wallet'),
('fa-warehouse','fa fa-warehouse','ti-building-warehouse','ti ti-building-warehouse'),
('fa-water','fa fa-water','ti-ripple','ti ti-ripple'),
('fa-wave-square','fa fa-wave-square','ti-wave-square','ti ti-wave-square'),
('fa-weight-hanging','fa fa-weight-hanging','ti-weight','ti ti-weight'),
('fa-weight','fa fa-weight','ti-weight','ti ti-weight'),
('fa-wheelchair','fa fa-wheelchair','ti-wheelchair','ti ti-wheelchair'),
('fa-wifi','fa fa-wifi','ti-wifi','ti ti-wifi'),
('fa-wind','fa fa-wind','ti-wind','ti ti-wind'),
('fa-window-close','fa fa-window-close','ti-square-x','ti ti-square-x'),
('fa-window-maximize','fa fa-window-maximize','ti-window-maximize','ti ti-window-maximize'),
('fa-window-minimize','fa fa-window-minimize','ti-window-minimize','ti ti-window-minimize'),
('fa-window-restore','fa fa-window-restore','ti-restore','ti ti-restore'),
('fa-wine-bottle','fa fa-wine-bottle','ti-bottle','ti ti-bottle'),
('fa-wine-glass-alt','fa fa-wine-glass-alt',null,null),
('fa-wine-glass','fa fa-wine-glass','ti-glass-full','ti ti-glass-full'),
('fa-won-sign','fa fa-won-sign','ti-currency-won','ti ti-currency-won'),
('fa-wrench','fa fa-wrench','ti-tool','ti ti-tool'),
('fa-x-ray','fa fa-x-ray',null,null),
('fa-yen-sign','fa fa-yen-sign','ti-currency-yen','ti ti-currency-yen'),
('fa-yin-yang','fa fa-yin-yang','ti-yin-yang','ti ti-yin-yang')
END" );
        }

        private void AddIconTranstionTableDown()
        {
            Sql( @"
IF OBJECT_ID(N'[dbo].[__IconTransition]', N'U') IS NOT NULL
BEGIN
    DROP TABLE [__IconTransition]
END
" );
        }

        #endregion
    }
}
