<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rock.Blocks\Rock.Blocks.csproj" />
    <ProjectReference Include="..\Rock.Tests.Shared\Rock.Tests.Shared.csproj" />
  </ItemGroup>

</Project>
