name: Bug Report
description: File a bug report
labels: [bug, triage, unverified]
body:
  - type: markdown
    attributes:
      value: |
        > Before opening your first issue we highly recommend reading [this blog post](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers). Also, please ensure your Github account is configured with your name, organization and a profile photo. This helps us to build community and communicate.
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: Please write a clear and concise description *and* **include screenshots**.
      placeholder: Tell us what you see!
      value: "Tell us what you see!"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Please provide a brief description of the actual behavior or the bug that you see along with the screenshots.
      placeholder: Actual Behavior
      value: "Actual Behavior"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Please provide a brief description of the expected behavior of the system.
      placeholder: Expected Behavior
      value: "Expected Behavior"
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the detailed steps to reproduce the issue. Do include all relevant screenshots wherever needed.
      value: |
        - Go to '...'
        - Click on '....'
        - Scroll down to '....'
        - See error
    validations:
      required: true
  - type: checkboxes
    id: issue-confirmation
    attributes:
      label: Issue Confirmation
      description: Check the boxes below to confirm each task has been completed.
      options:
        - label: Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
          required: true
        - label: Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).
          required: true
  - type: input
    id: version
    attributes:
      label: Rock Version
      description: Which version of Rock is this happening on?
      placeholder: 
    validations:
      required: true
  - type: input
    id: client-culture-settings
    attributes:
      label: Client Culture Setting
      description: This is found in your Rock System Information ⓘ toolbar popup. ![As seen in the ](https://rockrms.blob.core.windows.net/public-images/githubdocs/01_bug_report.system_information_popup.png)
      placeholder: 
    validations:
      required: true
