<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rock.AI.Agent\Rock.AI.Agent.csproj" />
    <ProjectReference Include="..\Rock.Lava.Fluid\Rock.Lava.Fluid.csproj" />
    <ProjectReference Include="..\Rock.Tests.Shared\Rock.Tests.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Rock.Common.Mobile">
      <HintPath>..\RockWeb\Bin\Rock.Common.Mobile.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="app.TestSettings.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CreateDefaultConfigFiles" BeforeTargets="PrepareForBuild">
    <Copy Condition="!Exists('$(ProjectDir)app.TestSettings.config')" SourceFiles="$(ProjectDir)app.TestSettings.config.example" DestinationFiles="$(ProjectDir)app.TestSettings.config" />
  </Target>

</Project>
