<!--Based on v1.0 20200917 -->
<p>As a leader, it is important to understand what Lakepointe Church believes on certain doctrinal issues. Please read and acknowledge below.</p>
<h2 style="text-align: center;">What We Believe</h2>
<h3>Jesus Christ</h3>
<p>We believe during His First Advent, our Lord Jesus Christ voluntarily left the glories of Heaven, taking upon Himself full and perfect humanity in His Incarnation.</p>
<h3>Salvation</h3>
<p>We believe salvation in our Lord Jesus Christ is a redemptive process wholly of God, in which believers participate solely on the basis of His grace through their faith in Jesus.</p>
<h3>Baptism</h3>
<p>Baptism is a public proclamation of faith and new life in Jesus Christ. It is an outward public testimony of an inward invisible transformation.</p>
<h3>People</h3>
<p>We believe God created humans, both male and female, in His perfect image.</p>
<h3>The Bible</h3>
<p>We believe the 66 books, which compose the canon of Holy Scripture, to be the sole authority of our faith and practice.</p>
<h3>The Holy Spirit</h3>
<p>We believe the Holy Spirit permanently indwells all believers, fulfilling His regenerating work of the new birth unto eternal life.</p>