<!--Based on v1.0 20200917 -->
<p>Como líder, es importante entender lo que Lakepointe Church cree en ciertos temas doctrinales. Por favor lee y reconoce lo siguiente.</p>
<h2 style="text-align: center;">Lo que Creemos</h2>
<h3>Jesucristo</h3>
<p>Creemos que durante Su Primera Venida, nuestro Señor Jesucristo dejó el Cielo voluntariamente, cargando Su humanidad completa y perfecta en Su Encarnación.</p>
<h3>Salvación</h3>
<p>Creemos que la salvación en nuestro Señor Jesucristo es un proceso de redención completamente de Dios, en el cual los creyentes participan solo en base de Su gracia a través de su fe en Jesús.</p>
<h3>Bautismo</h3>
<p>Creemos que el bautismo es una declaración pública de fe y una nueva vida en Jesucristo. Es un testimonio público de una transformación interna invisible.</p>
<h3>Personas</h3>
<p>Creemos que Dios creó a los humanos, hombres y mujeres, a Su perfecta imagen.</p>
<h3>La Biblia</h3>
<p>Creemos que los 66 libros, que componen el canon de las Santas Escrituras, son la única autoridad de nuestra fe y práctica.</p>
<h3>El Espíritu Santo</h3>
<p>Creemos que el Espíritu Santo mora permanentemente en todos los creyentes, cumpliendo Su obra regeneradora del nuevo nacimiento a una vida eterna.</p>