<!--Based on v1.x 20210915 -->
<h3><center>PURPOSE</center></h3>
<p>The purpose of the Safety Policy for Minors is to ensure a safe environment for protecting all minors, staff members, and volunteers, as well as the mission of Lakepointe Church.</p>
<h2><center>REPORTING RESPONSIBITILITIES & ENFORCEMENT</center></h2>
<h3><center>ABUSE TOLERANCE POLICY</center></h3>
<p>Lakepointe Church has a <b>zero tolerance for abuse</b> in ministry programs and ministry activities. It is the responsibility of every staff member and volunteer at Lakepointe Church to act in the best interest of all minors in every program.</p>
<p>In the event a leader observes inappropriate behavior (i.e. policy violations, neglectful supervision, poor role-modeling, etc.) or suspected abuse or neglect (physical, emotional, or sexual), it is that individual’s responsibility to immediately report their observations to an immediate supervisor, ministry leader, or the Campus Pastor.</p>
<h3><center>REPORTING SUSPICIOUS OR INAPPROPRIATE BEHAVIORS</center></h3>
<p>Lakepointe Church is committed to providing a safe, secure environment for minors and their families. As such, any report of inappropriate behavior or suspicion of abuse or neglect will be taken seriously and will be reported by a ministry leader, in accordance with this policy and state law, to Child Protective Services or another appropriate agency, when required by law.</p>
<h2><center>POLICY FOR INTERACTION WITH MINORS</center></h2>
<p>The purpose of the Policy for Interaction with Minors is to establish guidelines and policy expectations of leaders when interacting with minors to ensure the physical and emotional safety of minors and protect leaders.</p>
<h3><center>DISCIPLINE</center></h3>
<p>Lakepointe Church leaders are prohibited from using physical discipline in any manner for behavioral management of minors. <b>No form of physical discipline is acceptable.</b> This prohibition includes spanking, slapping, pinching, hitting, biting or any other physical force as retaliation or correction for inappropriate behaviors by children. Minors are to be disciplined using time-outs and other non-physical methods of behavior management.  Uncontrollable or unusual behavior should be reported immediately to parents and an immediate supervisor, ministry leader, or the Campus Pastor.</p>
<h3><center>ONE-TO-ONE INTERACTIONS</center></h3>
<p>Leaders should never conduct one-to-one, unobserved meetings or interactions with minors while participating in ministry activities or programs.</p>
<h3><center>TWO ADULT RULE AND RULE OF THREE</center></h3>
<p>For ministry activities involving minors 5th grade and below in a classroom setting, a minimum of two approved unrelated adults must be present.  For programming in public spaces (i.e. sports or outdoor camp activities), it is best to have two approved, unrelated adults present. When this is not possible, there must be at least one approved adult and a minimum of three unrelated individuals present (for example, one adult and 2 minors).</p>
<p>For ministry activities involving minors 6th-12th grade in a classroom setting, it is best to have two approved, unrelated adults present.  When this is not possible, there must be at least one approved adult and a minimum of three unrelated individuals present (for example, one adult and 2 minors).</p>