<!-- Opportunities for Minors (Spanish) -->
<p>In order for your student/child to have the best possible experience in his or her volunteer role, we have specified ages at which an individual becomes eligible for specific roles.  There are no volunteer opportunities for 3rd grade and below.</p>
<div class="container-fluid">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#general">9-12 Años</a></h4>
            </div>
            <div id="general" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        <li>Equipo de Alabanza de Niños</li>
                        <li>The Village (Grupo Grande de Preescolar)</li>
                        <li>Carrito de Bebidas para voluntarios</li>
                        <li>Voluntario de Media/Producción</li>
                        <li>Ayudante en el Salón de Clases de Preescolar; se requiere servir con un padre o adulto (puede dar los snacks o jugar con los niños)</li>
                        <li>Ayudante en el Salón de Clases de SOAR; se requiere servir con un padre o adulto</li>
                        <li>Ayudante de Mesa en el Salón de Clases de Kindergarten – 3˚ grado; se requiere servir con un padre o adulto (puede dar materiales y ayudar a los niños con sus actividades)</li>
                        <li>Viaje Misionero</li>
                        <li>KidQuest</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#first">13-17 Años</a></h4>
            </div>
            <div id="first" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        <li>Todas las Posiciones Anteriores</li>
                        <li>Ayudante en el Salón de Clases de Preescolar (puede dirigir actividades)</li> 
                        <li>Ayudante en el Salón de Clases de SOAR (puede dirigir actividades)</li>
                        <li>Líder de Mesa en el Salón de Clases de Primaria</li>
                        <li>Líder de Grupo Grande o Anfitrión en el Escenario (se requiere audición)</li>
                        <li>Voluntario en United de LP Students (8˚ grado completado)</li>
                        <li>Líder de Grupos de Middle School (8˚ grado completado)</li>
                        <li>Voluntario en Student Connect (8˚ grado completado)</li>
                        <li>Líder de Estudiantes en Trek (9˚ grado completado)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#second">Los Estudiantes Voluntarios no están permitidos:</a></h4>
            </div>
            <div id="second" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        <li>Los estudiantes entre 9-12 años nunca deberían estar en un "Papel de Supervisión" sobre los niños.</li>
                        <li>Cambiar un pañal.</li>
                        <li>Llevar a un niño al baño.</li>
                        <li>Registrar de entrada o salida a un niño.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>