<!-- Opportunities for Minors (English) -->
<p>In order for your student/child to have the best possible experience in his or her volunteer role, we have specified ages at which an individual becomes eligible for specific roles.  There are no volunteer opportunities for 3rd grade and below.</p>
<div class="container-fluid">
    <div class="panel-group" id="accordion">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#general">9-12 Years Old</a></h4>
            </div>
            <div id="general" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        <li>Kids Worship Music Team</li>
                        <li>Kids Worship Junior Shepherd</li>
                        <li>The Village (Preschool Large Group)</li>
                        <li>Media Volunteer</li>
                        <li>Classroom Assistant in Preschool Classrooms; required to serve with parent or another related adult (Can pass out snacks or supplies and play with children)</li>
                        <li>Classroom Assistant in SOAR Classrooms; required to serve with parent or another related adult</li>
                        <li>Table Assistant in Kindergarten – 3rd Grade Classrooms; required to serve with parent or another related adult (Can pass out supplies and assist kids in putting together activities)</li>
                        <li>Mission Trip</li>
                        <li>KidQuest</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#first">13-17 Years Old</a></h4>
            </div>
            <div id="first" class="panel-collapse collapse">
                <div class="panel-body">
                    <ul>
                        <li>All Above Positions</li>
                        <li>Classroom Assistant in Preschool Classrooms (Can lead activities)</li> 
                        <li>Classroom Assistant in SOAR Classrooms (Can lead activities)</li>
                        <li>Table Leader in Grade School Classrooms</li>
                        <li>Large Group Leader or Stage Host (Audition Required)</li>
                        <li>LP Student United Volunteer (Completed 8th grade)</li>
                        <li>Middle School Groups Leader (Completed 8th grade)</li>
                        <li>LP Student Connect Volunteer (Completed 8th grade)</li>
                        <li>Trek Student Leader (Completed 9th grade)</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#second">Student Volunteers Are Not Allowed To</a></h4>
            </div>
            <div id="second" class="panel-collapse collapse.show">
                <div class="panel-body">
                    <ul>
                        <li>Students age 9-12 should never be placed in a “Supervisory Role” over children.</li>
                        <li>Serve directly with non-verbal individuals.</li>
                        <li>Change a diaper.</li>
                        <li>Take a child to the restroom.</li>
                        <li>Check children in or out.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>