//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";
import { ListItemBag } from "@Obsidian/ViewModels/Utility/listItemBag";

/** The initialization options for the Check-in Context Setter block. */
export type CheckInContextSetterOptionsBag = {
    /** The list of campuses to display in the dropdown. */
    campuses?: ListItemBag[] | null;

    /**
     * When a context item changes, this will cause the page to redirect
     * back to itself so that the new context can be applied to legacy
     * WebForms blocks.
     */
    isRedirectRequired: boolean;

    /** The root locations to use for the location picker. */
    rootLocations?: Record<Guid, Guid> | null;

    /**
     * The list of schedules that are valid for the currently selected
     * location.
     */
    schedules?: ListItemBag[] | null;

    /** The security grant token to use when loading additional data. */
    securityGrantToken?: string | null;

    /** The selected campus when the block loaded. */
    selectedCampus?: ListItemBag | null;

    /** The selected location when the block loaded. */
    selectedLocation?: ListItemBag | null;

    /** The selected schedule when the block loaded. */
    selectedSchedule?: ListItemBag | null;
};
