//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the T4\Model.tt template.
//
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//
using System;
using System.Collections.Generic;
using System.Linq;

using Rock.Data;

namespace Rock.Core
{
	/// <summary>
	/// Entity Change Repository class
	/// </summary>
    public partial class EntityChangeRepository : Repository<Rock.Core.EntityChange>
    {
		/// <summary>
		/// Gets Entity Changes by Change Set
		/// </summary>
		/// <param name="changeSet">Change Set.</param>
		/// <returns>An enumerable list of EntityChange objects.</returns>
	    public IEnumerable<Rock.Core.EntityChange> GetByChangeSet( Guid changeSet )
        {
            return Find( t => t.ChangeSet == changeSet );
        }
		
    }
}
