//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//
using System;
using System.Collections.Generic;
using System.Dynamic;

using Rock.Data;

namespace Rock.Crm
{
    /// <summary>
    /// Data Transfer Object for PersonViewed object
    /// </summary>
    public partial class PersonViewedDto : IDto
    {

#pragma warning disable 1591
        public int? ViewerPersonId { get; set; }
        public int? TargetPersonId { get; set; }
        public DateTime? ViewDateTime { get; set; }
        public string IpAddress { get; set; }
        public string Source { get; set; }
        public int Id { get; set; }
        public Guid Guid { get; set; }
#pragma warning restore 1591

        /// <summary>
        /// Instantiates a new DTO object
        /// </summary>
        public PersonViewedDto ()
        {
        }

        /// <summary>
        /// Instantiates a new DTO object from the entity
        /// </summary>
        /// <param name="personViewed"></param>
        public PersonViewedDto ( PersonViewed personViewed )
        {
            CopyFromModel( personViewed );
        }

        /// <summary>
        /// Creates a dictionary object.
        /// </summary>
        /// <returns></returns>
        public virtual Dictionary<string, object> ToDictionary()
        {
            var dictionary = new Dictionary<string, object>();
            dictionary.Add( "ViewerPersonId", this.ViewerPersonId );
            dictionary.Add( "TargetPersonId", this.TargetPersonId );
            dictionary.Add( "ViewDateTime", this.ViewDateTime );
            dictionary.Add( "IpAddress", this.IpAddress );
            dictionary.Add( "Source", this.Source );
            dictionary.Add( "Id", this.Id );
            dictionary.Add( "Guid", this.Guid );
            return dictionary;
        }

        /// <summary>
        /// Creates a dynamic object.
        /// </summary>
        /// <returns></returns>
        public virtual dynamic ToDynamic()
        {
            dynamic expando = new ExpandoObject();
            expando.ViewerPersonId = this.ViewerPersonId;
            expando.TargetPersonId = this.TargetPersonId;
            expando.ViewDateTime = this.ViewDateTime;
            expando.IpAddress = this.IpAddress;
            expando.Source = this.Source;
            expando.Id = this.Id;
            expando.Guid = this.Guid;
            return expando;
        }

        /// <summary>
        /// Copies the model property values to the DTO properties
        /// </summary>
        /// <param name="model">The model.</param>
        public void CopyFromModel( IEntity model )
        {
            if ( model is PersonViewed )
            {
                var personViewed = (PersonViewed)model;
                this.ViewerPersonId = personViewed.ViewerPersonId;
                this.TargetPersonId = personViewed.TargetPersonId;
                this.ViewDateTime = personViewed.ViewDateTime;
                this.IpAddress = personViewed.IpAddress;
                this.Source = personViewed.Source;
                this.Id = personViewed.Id;
                this.Guid = personViewed.Guid;
            }
        }

        /// <summary>
        /// Copies the DTO property values to the entity properties
        /// </summary>
        /// <param name="model">The model.</param>
        public void CopyToModel ( IEntity model )
        {
            if ( model is PersonViewed )
            {
                var personViewed = (PersonViewed)model;
                personViewed.ViewerPersonId = this.ViewerPersonId;
                personViewed.TargetPersonId = this.TargetPersonId;
                personViewed.ViewDateTime = this.ViewDateTime;
                personViewed.IpAddress = this.IpAddress;
                personViewed.Source = this.Source;
                personViewed.Id = this.Id;
                personViewed.Guid = this.Guid;
            }
        }
    }
}
