SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME='cmsFile_sp_getByID' AND TYPE='P')
BEGIN
	DROP PROC cmsFile_sp_getByID
END
GO

CREATE PROCEDURE cmsFile_sp_getByID
	@Id int,
	@Guid uniqueidentifier
AS
BEGIN
	SET NOCOUNT ON;

	IF @Id > -1
	BEGIN
		SELECT Data, FileName, MimeType FROM cmsFile WHERE Id = @Id
	END
	ELSE
	BEGIN
		SELECT Data, FileName, MimeType FROM cmsFile WHERE [Guid] = @Guid
	END
END
GO
