//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { GridDataBag } from "@Obsidian/ViewModels/Core/Grid/gridDataBag";
import { GridDefinitionBag } from "@Obsidian/ViewModels/Core/Grid/gridDefinitionBag";
import { PublicAttributeBag } from "@Obsidian/ViewModels/Utility/publicAttributeBag";

/**
 * The response data for the grid in the Content Channel Navigation block.
 * Contains both the grid definition and data since columns change per channel.
 */
export type ContentChannelNavigationGetGridDataResponseBag = {
    /** Gets or sets the URL for adding a new item to this channel. */
    addItemUrl?: string | null;

    /**
     * Gets or sets the attribute definitions for filters in the grid settings modal.
     * These change per channel based on attributes qualified by channel type or channel ID.
     */
    attributeFilters?: PublicAttributeBag[] | null;

    /**
     * Gets or sets a value indicating whether the current person can edit items in this channel.
     * Controls visibility of the add button, delete column, and security column.
     */
    canEdit: boolean;

    /** Gets or sets the display name of the selected content channel. */
    channelName?: string | null;

    /** Gets or sets the grid data containing the rows of content channel items. */
    gridData?: GridDataBag | null;

    /**
     * Gets or sets the grid definition describing the columns for the selected channel.
     * This changes dynamically based on the channel's type configuration.
     */
    gridDefinition?: GridDefinitionBag | null;

    /**
     * Gets or sets a value indicating whether any user-applied filters
     * are active for the current grid data request. This is determined
     * server-side after converting filter values to their internal
     * representation, so it is the authoritative source for whether
     * the grid settings indicator should appear active.
     */
    hasActiveFilters: boolean;

    /**
     * Gets or sets a value indicating whether any items have event
     * occurrences. Controls the event occurrences column.
     */
    hasEventOccurrences: boolean;

    /**
     * Gets or sets a value indicating whether any items have a future
     * start date (are scheduled). Controls the date status icon column.
     */
    hasScheduledItems: boolean;

    /**
     * Gets or sets a value indicating whether the date columns should
     * include time in addition to the date. When false, only the date
     * portion is displayed.
     */
    isIncludeTime: boolean;

    /**
     * Gets or sets a value indicating whether item reordering is currently enabled.
     * True when items are manually ordered and no filters are active.
     */
    isReorderEnabled: boolean;
};
