//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { AgeClassification } from "@Obsidian/Enums/Crm/ageClassification";
import { Gender } from "@Obsidian/Enums/Crm/gender";

/** Bag for person-related data in the Volunteer Generosity Analysis block. */
export type VolunteerGenerosityDataBag = {
    /** Gets or sets the person's age */
    age?: number | null;

    /** Gets or sets the person's age classification */
    ageClassification?: AgeClassification | null;

    /** Gets or sets the Campus ID. */
    campusId?: string | null;

    /** Gets or sets the Campus Short Code */
    campusShortCode?: string | null;

    /** Gets or sets the person's connection status */
    connectionStatus?: string | null;

    /** Gets or sets the person's bit mask */
    donationDateKeys?: string | null;

    /** Gets or sets the person's donation months */
    donationMonths?: string | null;

    /** Gets or sets the person's gender */
    gender: Gender;

    /** Gets or sets the person's giving identifier. */
    givingId?: string | null;

    /** Gets or sets the Group ID. */
    groupId?: string | null;

    /** Gets or sets the Group Name. */
    groupName?: string | null;

    /** Gets or sets the IsActive flag. */
    isActive: boolean;

    /** Gets or sets the person's last attendance date. */
    lastAttendanceDate?: string | null;

    /** Gets or sets the person's last name. */
    lastName?: string | null;

    /** Gets or sets the person's nickname. */
    nickName?: string | null;

    /** Gets or sets the person group key. */
    personGroupKey?: string | null;

    /** Gets or sets the person identifier. */
    personId: number;

    /** Gets or sets the person's photo Id. */
    photoId?: number | null;

    /** Gets or sets the person's photo URL. */
    photoUrl?: string | null;
};
