//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the T4\Model.tt template.
//
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//
using System.ComponentModel.Composition;
using System.ServiceModel;
using System.ServiceModel.Activation;
using System.ServiceModel.Web;

using Rock.Cms.Security;

namespace Rock.Api.Cms
{
	/// <summary>
	/// REST WCF service for Sites
	/// </summary>
    [Export(typeof(IService))]
    [ExportMetadata("RouteName", "api/Cms/Site")]
	[AspNetCompatibilityRequirements( RequirementsMode = AspNetCompatibilityRequirementsMode.Allowed )]
    public partial class SiteService : ISiteService, IService
    {
		/// <summary>
		/// Gets a Site object
		/// </summary>
		[WebGet( UriTemplate = "{id}" )]
        public Rock.Models.Cms.SiteDTO Get( string id )
        {
            var currentUser = System.Web.Security.Membership.GetUser();
            if ( currentUser == null )
                throw new FaultException( "Must be logged in" );

            using (Rock.Helpers.UnitOfWorkScope uow = new Rock.Helpers.UnitOfWorkScope())
            {
                uow.objectContext.Configuration.ProxyCreationEnabled = false;
				Rock.Services.Cms.SiteService SiteService = new Rock.Services.Cms.SiteService();
                Rock.Models.Cms.Site Site = SiteService.Get( int.Parse( id ) );
                if ( Site.Authorized( "View", currentUser ) )
                    return Site.DataTransferObject;
                else
                    throw new FaultException( "Unauthorized" );
            }
        }
		
		/// <summary>
		/// Updates a Site object
		/// </summary>
		[WebInvoke( Method = "PUT", UriTemplate = "{id}" )]
        public void UpdateSite( string id, Rock.Models.Cms.SiteDTO Site )
        {
            var currentUser = System.Web.Security.Membership.GetUser();
            if ( currentUser == null )
                throw new FaultException( "Must be logged in" );

            using ( Rock.Helpers.UnitOfWorkScope uow = new Rock.Helpers.UnitOfWorkScope() )
            {
                uow.objectContext.Configuration.ProxyCreationEnabled = false;

                Rock.Services.Cms.SiteService SiteService = new Rock.Services.Cms.SiteService();
                Rock.Models.Cms.Site existingSite = SiteService.Get( int.Parse( id ) );
                if ( existingSite.Authorized( "Edit", currentUser ) )
                {
                    uow.objectContext.Entry(existingSite).CurrentValues.SetValues(Site);
                    SiteService.Save( existingSite, currentUser.PersonId() );
                }
                else
                    throw new FaultException( "Unauthorized" );
            }
        }

		/// <summary>
		/// Creates a new Site object
		/// </summary>
		[WebInvoke( Method = "POST", UriTemplate = "" )]
        public void CreateSite( Rock.Models.Cms.SiteDTO Site )
        {
            var currentUser = System.Web.Security.Membership.GetUser();
            if ( currentUser == null )
                throw new FaultException( "Must be logged in" );

            using ( Rock.Helpers.UnitOfWorkScope uow = new Rock.Helpers.UnitOfWorkScope() )
            {
                uow.objectContext.Configuration.ProxyCreationEnabled = false;

                Rock.Services.Cms.SiteService SiteService = new Rock.Services.Cms.SiteService();
                Rock.Models.Cms.Site existingSite = new Rock.Models.Cms.Site();
				SiteService.Add( existingSite, currentUser.PersonId() );
                uow.objectContext.Entry(existingSite).CurrentValues.SetValues(Site);
                SiteService.Save( existingSite, currentUser.PersonId() );
            }
        }

		/// <summary>
		/// Deletes a Site object
		/// </summary>
		[WebInvoke( Method = "DELETE", UriTemplate = "{id}" )]
        public void DeleteSite( string id )
        {
            var currentUser = System.Web.Security.Membership.GetUser();
            if ( currentUser == null )
                throw new FaultException( "Must be logged in" );

            using ( Rock.Helpers.UnitOfWorkScope uow = new Rock.Helpers.UnitOfWorkScope() )
            {
                uow.objectContext.Configuration.ProxyCreationEnabled = false;

                Rock.Services.Cms.SiteService SiteService = new Rock.Services.Cms.SiteService();
                Rock.Models.Cms.Site Site = SiteService.Get( int.Parse( id ) );
                if ( Site.Authorized( "Edit", currentUser ) )
                {
                    SiteService.Delete( Site, currentUser.PersonId() );
                }
                else
                    throw new FaultException( "Unauthorized" );
            }
        }

    }
}
