namespace Rock.Migrations
    
    using System;
    using System.Data.Entity.Migrations;

#pragma warning disable 1591
    
    public partial class AddAuditFunctionality : DbMigration
        
        public override void Up()
            
            CreateTable(
                "dbo.coreAudit",
                c => new
                        
                        Id = c.Int(nullable: false, identity: true),
                        EntityType = c.String(nullable: false, maxLength: 100),
                        EntityId = c.Int(nullable: false),
                        EntityName = c.String(nullable: false, maxLength: 200),
                        AuditType = c.Int(nullable: false),
                        Properties = c.String(),
                        DateTime = c.DateTimeOffset(),
                        PersonId = c.Int(),
                        Guid = c.Guid(nullable: false),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.crmPerson", t => t.PersonId, cascadeDelete: true)
                .Index(t => t.PersonId);
            
            AddColumn("dbo.cmsFile", "LastModifiedTime", c => c.DateTimeOffset());
            AddForeignKey("dbo.coreEntityChange", "CreatedByPersonId", "dbo.crmPerson", "Id", cascadeDelete: true);
            AddForeignKey("dbo.coreExceptionLog", "CreatedByPersonId", "dbo.crmPerson", "Id", cascadeDelete: true);
            CreateIndex("dbo.coreEntityChange", "CreatedByPersonId");
            CreateIndex("dbo.coreExceptionLog", "CreatedByPersonId");
            DropColumn("dbo.cmsAuth", "CreatedDateTime");
            DropColumn("dbo.cmsAuth", "ModifiedDateTime");
            DropColumn("dbo.cmsAuth", "CreatedByPersonId");
            DropColumn("dbo.cmsAuth", "ModifiedByPersonId");
            DropColumn("dbo.groupsGroup", "CreatedDateTime");
            DropColumn("dbo.groupsGroup", "ModifiedDateTime");
            DropColumn("dbo.groupsGroup", "CreatedByPersonId");
            DropColumn("dbo.groupsGroup", "ModifiedByPersonId");
            DropColumn("dbo.groupsMember", "CreatedDateTime");
            DropColumn("dbo.groupsMember", "ModifiedDateTime");
            DropColumn("dbo.groupsMember", "CreatedByPersonId");
            DropColumn("dbo.groupsMember", "ModifiedByPersonId");
            DropColumn("dbo.crmPerson", "CreatedDateTime");
            DropColumn("dbo.crmPerson", "ModifiedDateTime");
            DropColumn("dbo.crmPerson", "CreatedByPersonId");
            DropColumn("dbo.crmPerson", "ModifiedByPersonId");
            DropColumn("dbo.cmsUser", "CreatedDateTime");
            DropColumn("dbo.cmsUser", "ModifiedDateTime");
            DropColumn("dbo.cmsUser", "CreatedByPersonId");
            DropColumn("dbo.cmsUser", "ModifiedByPersonId");
            DropColumn("dbo.crmEmailTemplate", "CreatedDateTime");
            DropColumn("dbo.crmEmailTemplate", "ModifiedDateTime");
            DropColumn("dbo.crmEmailTemplate", "CreatedByPersonId");
            DropColumn("dbo.crmEmailTemplate", "ModifiedByPersonId");
            DropColumn("dbo.crmPhoneNumber", "CreatedDateTime");
            DropColumn("dbo.crmPhoneNumber", "ModifiedDateTime");
            DropColumn("dbo.crmPhoneNumber", "CreatedByPersonId");
            DropColumn("dbo.crmPhoneNumber", "ModifiedByPersonId");
            DropColumn("dbo.coreDefinedValue", "CreatedDateTime");
            DropColumn("dbo.coreDefinedValue", "ModifiedDateTime");
            DropColumn("dbo.coreDefinedValue", "CreatedByPersonId");
            DropColumn("dbo.coreDefinedValue", "ModifiedByPersonId");
            DropColumn("dbo.coreDefinedType", "CreatedDateTime");
            DropColumn("dbo.coreDefinedType", "ModifiedDateTime");
            DropColumn("dbo.coreDefinedType", "CreatedByPersonId");
            DropColumn("dbo.coreDefinedType", "ModifiedByPersonId");
            DropColumn("dbo.coreFieldType", "CreatedDateTime");
            DropColumn("dbo.coreFieldType", "ModifiedDateTime");
            DropColumn("dbo.coreFieldType", "CreatedByPersonId");
            DropColumn("dbo.coreFieldType", "ModifiedByPersonId");
            DropColumn("dbo.coreAttribute", "CreatedDateTime");
            DropColumn("dbo.coreAttribute", "ModifiedDateTime");
            DropColumn("dbo.coreAttribute", "CreatedByPersonId");
            DropColumn("dbo.coreAttribute", "ModifiedByPersonId");
            DropColumn("dbo.coreAttributeQualifier", "CreatedDateTime");
            DropColumn("dbo.coreAttributeQualifier", "ModifiedDateTime");
            DropColumn("dbo.coreAttributeQualifier", "CreatedByPersonId");
            DropColumn("dbo.coreAttributeQualifier", "ModifiedByPersonId");
            DropColumn("dbo.coreAttributeValue", "CreatedDateTime");
            DropColumn("dbo.coreAttributeValue", "ModifiedDateTime");
            DropColumn("dbo.coreAttributeValue", "CreatedByPersonId");
            DropColumn("dbo.coreAttributeValue", "ModifiedByPersonId");
            DropColumn("dbo.financialPledge", "ModifiedDateTime");
            DropColumn("dbo.financialPledge", "CreatedDateTime");
            DropColumn("dbo.financialPledge", "CreatedByPersonId");
            DropColumn("dbo.financialPledge", "ModifiedByPersonId");
            DropColumn("dbo.financialFund", "ModifiedDateTime");
            DropColumn("dbo.financialFund", "CreatedDateTime");
            DropColumn("dbo.financialFund", "CreatedByPersonId");
            DropColumn("dbo.financialFund", "ModifiedByPersonId");
            DropColumn("dbo.financialTransaction", "ModifiedDateTime");
            DropColumn("dbo.financialTransaction", "CreatedDateTime");
            DropColumn("dbo.financialTransaction", "CreatedByPersonId");
            DropColumn("dbo.financialTransaction", "ModifiedByPersonId");
            DropColumn("dbo.financialBatch", "ModifiedDateTime");
            DropColumn("dbo.financialBatch", "CreatedDateTime");
            DropColumn("dbo.financialBatch", "CreatedByPersonId");
            DropColumn("dbo.financialBatch", "ModifiedByPersonId");
            DropColumn("dbo.financialGateway", "ModifiedDateTime");
            DropColumn("dbo.financialGateway", "CreatedDateTime");
            DropColumn("dbo.financialGateway", "CreatedByPersonId");
            DropColumn("dbo.financialGateway", "ModifiedByPersonId");
            DropColumn("dbo.financialTransactionDetail", "ModifiedDateTime");
            DropColumn("dbo.financialTransactionDetail", "CreatedDateTime");
            DropColumn("dbo.financialTransactionDetail", "CreatedByPersonId");
            DropColumn("dbo.financialTransactionDetail", "ModifiedByPersonId");
            DropColumn("dbo.cmsFile", "CreatedDateTime");
            DropColumn("dbo.cmsFile", "ModifiedDateTime");
            DropColumn("dbo.cmsFile", "CreatedByPersonId");
            DropColumn("dbo.cmsFile", "ModifiedByPersonId");
            DropColumn("dbo.groupsGroupRole", "CreatedDateTime");
            DropColumn("dbo.groupsGroupRole", "ModifiedDateTime");
            DropColumn("dbo.groupsGroupRole", "CreatedByPersonId");
            DropColumn("dbo.groupsGroupRole", "ModifiedByPersonId");
            DropColumn("dbo.groupsGroupType", "CreatedDateTime");
            DropColumn("dbo.groupsGroupType", "ModifiedDateTime");
            DropColumn("dbo.groupsGroupType", "CreatedByPersonId");
            DropColumn("dbo.groupsGroupType", "ModifiedByPersonId");
            DropColumn("dbo.crmLocation", "CreatedDateTime");
            DropColumn("dbo.crmLocation", "ModifiedDateTime");
            DropColumn("dbo.crmLocation", "CreatedByPersonId");
            DropColumn("dbo.crmLocation", "ModifiedByPersonId");
            DropColumn("dbo.crmCampus", "CreatedDateTime");
            DropColumn("dbo.crmCampus", "ModifiedDateTime");
            DropColumn("dbo.crmCampus", "CreatedByPersonId");
            DropColumn("dbo.crmCampus", "ModifiedByPersonId");
            DropColumn("dbo.cmsBlockType", "CreatedDateTime");
            DropColumn("dbo.cmsBlockType", "ModifiedDateTime");
            DropColumn("dbo.cmsBlockType", "CreatedByPersonId");
            DropColumn("dbo.cmsBlockType", "ModifiedByPersonId");
            DropColumn("dbo.cmsBlock", "CreatedDateTime");
            DropColumn("dbo.cmsBlock", "ModifiedDateTime");
            DropColumn("dbo.cmsBlock", "CreatedByPersonId");
            DropColumn("dbo.cmsBlock", "ModifiedByPersonId");
            DropColumn("dbo.cmsHtmlContent", "CreatedDateTime");
            DropColumn("dbo.cmsHtmlContent", "ModifiedDateTime");
            DropColumn("dbo.cmsHtmlContent", "CreatedByPersonId");
            DropColumn("dbo.cmsHtmlContent", "ModifiedByPersonId");
            DropColumn("dbo.cmsPage", "CreatedDateTime");
            DropColumn("dbo.cmsPage", "ModifiedDateTime");
            DropColumn("dbo.cmsPage", "CreatedByPersonId");
            DropColumn("dbo.cmsPage", "ModifiedByPersonId");
            DropColumn("dbo.cmsPageRoute", "CreatedDateTime");
            DropColumn("dbo.cmsPageRoute", "ModifiedDateTime");
            DropColumn("dbo.cmsPageRoute", "CreatedByPersonId");
            DropColumn("dbo.cmsPageRoute", "ModifiedByPersonId");
            DropColumn("dbo.cmsPageContext", "ModifiedDateTime");
            DropColumn("dbo.cmsPageContext", "CreatedByPersonId");
            DropColumn("dbo.cmsPageContext", "ModifiedByPersonId");
            DropColumn("dbo.cmsSite", "CreatedDateTime");
            DropColumn("dbo.cmsSite", "ModifiedDateTime");
            DropColumn("dbo.cmsSite", "CreatedByPersonId");
            DropColumn("dbo.cmsSite", "ModifiedByPersonId");
            DropColumn("dbo.cmsSiteDomain", "CreatedDateTime");
            DropColumn("dbo.cmsSiteDomain", "ModifiedDateTime");
            DropColumn("dbo.cmsSiteDomain", "CreatedByPersonId");
            DropColumn("dbo.cmsSiteDomain", "ModifiedByPersonId");
            DropColumn("dbo.coreMetric", "CreatedDateTime");
            DropColumn("dbo.coreMetric", "ModifiedDateTime");
            DropColumn("dbo.coreMetric", "CreatedByPersonId");
            DropColumn("dbo.coreMetric", "ModifiedByPersonId");
            DropColumn("dbo.coreMetricValue", "CreatedDateTime");
            DropColumn("dbo.coreMetricValue", "ModifiedDateTime");
            DropColumn("dbo.coreMetricValue", "CreatedByPersonId");
            DropColumn("dbo.coreMetricValue", "ModifiedByPersonId");
            DropColumn("dbo.coreTag", "CreatedDateTime");
            DropColumn("dbo.coreTag", "ModifiedDateTime");
            DropColumn("dbo.coreTag", "CreatedByPersonId");
            DropColumn("dbo.coreTag", "ModifiedByPersonId");
            DropColumn("dbo.coreTaggedItem", "CreatedDateTime");
            DropColumn("dbo.coreTaggedItem", "ModifiedDateTime");
            DropColumn("dbo.coreTaggedItem", "CreatedByPersonId");
            DropColumn("dbo.coreTaggedItem", "ModifiedByPersonId");
            DropColumn("dbo.crmPersonMerged", "CreatedDateTime");
            DropColumn("dbo.crmPersonMerged", "CreatedByPersonId");
            DropColumn("dbo.utilJob", "CreatedDateTime");
            DropColumn("dbo.utilJob", "ModifiedDateTime");
            DropColumn("dbo.utilJob", "CreatedByPersonId");
            DropColumn("dbo.utilJob", "ModifiedByPersonId");
        }
        
        public override void Down()
            
            AddColumn("dbo.utilJob", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.utilJob", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.utilJob", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.utilJob", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.crmPersonMerged", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.crmPersonMerged", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreTaggedItem", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreTaggedItem", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreTaggedItem", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreTaggedItem", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreTag", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreTag", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreTag", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreTag", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreMetricValue", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreMetricValue", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreMetricValue", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreMetricValue", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreMetric", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreMetric", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreMetric", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreMetric", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsSiteDomain", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsSiteDomain", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsSiteDomain", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsSiteDomain", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsSite", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsSite", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsSite", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsSite", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsPageContext", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsPageContext", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsPageContext", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsPageRoute", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsPageRoute", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsPageRoute", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsPageRoute", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsPage", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsPage", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsPage", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsPage", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsHtmlContent", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsHtmlContent", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsHtmlContent", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsHtmlContent", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsBlock", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsBlock", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsBlock", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsBlock", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsBlockType", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsBlockType", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsBlockType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsBlockType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.crmCampus", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.crmCampus", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.crmCampus", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.crmCampus", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.crmLocation", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.crmLocation", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.crmLocation", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.crmLocation", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsGroupType", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.groupsGroupType", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.groupsGroupType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsGroupType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsGroupRole", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.groupsGroupRole", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.groupsGroupRole", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsGroupRole", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsFile", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsFile", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsFile", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsFile", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.financialTransactionDetail", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.financialTransactionDetail", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.financialTransactionDetail", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.financialTransactionDetail", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.financialGateway", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.financialGateway", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.financialGateway", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.financialGateway", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.financialBatch", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.financialBatch", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.financialBatch", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.financialBatch", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.financialTransaction", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.financialTransaction", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.financialTransaction", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.financialTransaction", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.financialFund", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.financialFund", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.financialFund", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.financialFund", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.financialPledge", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.financialPledge", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.financialPledge", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.financialPledge", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreAttributeValue", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreAttributeValue", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreAttributeValue", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreAttributeValue", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreAttributeQualifier", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreAttributeQualifier", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreAttributeQualifier", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreAttributeQualifier", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreAttribute", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreAttribute", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreAttribute", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreAttribute", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreFieldType", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreFieldType", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreFieldType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreFieldType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreDefinedType", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreDefinedType", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreDefinedType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreDefinedType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.coreDefinedValue", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.coreDefinedValue", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.coreDefinedValue", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.coreDefinedValue", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.crmPhoneNumber", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.crmPhoneNumber", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.crmPhoneNumber", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.crmPhoneNumber", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.crmEmailTemplate", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.crmEmailTemplate", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.crmEmailTemplate", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.crmEmailTemplate", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsUser", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsUser", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsUser", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsUser", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.crmPerson", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.crmPerson", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.crmPerson", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.crmPerson", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsMember", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.groupsMember", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.groupsMember", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsMember", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsGroup", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.groupsGroup", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.groupsGroup", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.groupsGroup", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsAuth", "ModifiedByPersonId", c => c.Int());
            AddColumn("dbo.cmsAuth", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.cmsAuth", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.cmsAuth", "CreatedDateTime", c => c.DateTime());
            DropIndex("dbo.coreExceptionLog", new[]      "CreatedByPersonId" });
            DropIndex("dbo.coreEntityChange", new[]      "CreatedByPersonId" });
            DropIndex("dbo.coreAudit", new[]      "PersonId" });
            DropForeignKey("dbo.coreExceptionLog", "CreatedByPersonId", "dbo.crmPerson");
            DropForeignKey("dbo.coreEntityChange", "CreatedByPersonId", "dbo.crmPerson");
            DropForeignKey("dbo.coreAudit", "PersonId", "dbo.crmPerson");
            DropColumn("dbo.cmsFile", "LastModifiedTime");
            DropTable("dbo.coreAudit");
        }
    }
}
