// <auto-generated />
namespace Rock.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AttributeQualifierValueNotRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttributeQualifierValueNotRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201209242038385_AttributeQualifierValueNotRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
