// <auto-generated />
namespace Rock.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MarketingCampaignTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MarketingCampaignTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201210302321525_MarketingCampaignTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
