//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";

/** Represents a connection status and its display properties for use in the Connections Hub. */
export type ConnectionStatusBag = {
    /** Gets or sets whether this status is disabled. (This is used when editing a request in sequential status mode) */
    disabled: boolean;

    /** Gets or sets the unique identifier of this connection status. */
    guid: Guid;

    /** Gets or sets the highlight color used to visually distinguish this status in the UI. */
    highlightColor?: string | null;

    /** Gets or sets a value indicating whether this status is the default status. */
    isDefaultStatus: boolean;

    /** Gets or sets a value indicating whether a note is required when completing a request with this status. */
    isNoteRequiredOnCompletion: boolean;

    /** Gets or sets the display name of this connection status. */
    name?: string | null;

    /** Gets or sets the sort order of this connection status relative to others in the same Connection Type. */
    order: number;
};
