//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using System;
using System.Linq;
using Rock.Attribute;
using Rock.Model;
using Rock.Web.Cache;

namespace Rock.ViewModel
{
    /// <summary>
    /// BinaryFileType View Model
    /// </summary>
    [ViewModelOf( typeof( Rock.Model.BinaryFileType ) )]
    public partial class BinaryFileTypeViewModel : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the CacheControlHeaderSettings.
        /// </summary>
        /// <value>
        /// The CacheControlHeaderSettings.
        /// </value>
        public string CacheControlHeaderSettings { get; set; }

        /// <summary>
        /// Gets or sets the CacheToServerFileSystem.
        /// </summary>
        /// <value>
        /// The CacheToServerFileSystem.
        /// </value>
        public bool CacheToServerFileSystem { get; set; }

        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        /// <value>
        /// The Description.
        /// </value>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the IconCssClass.
        /// </summary>
        /// <value>
        /// The IconCssClass.
        /// </value>
        public string IconCssClass { get; set; }

        /// <summary>
        /// Gets or sets the IsSystem.
        /// </summary>
        /// <value>
        /// The IsSystem.
        /// </value>
        public bool IsSystem { get; set; }

        /// <summary>
        /// Gets or sets the MaxHeight.
        /// </summary>
        /// <value>
        /// The MaxHeight.
        /// </value>
        public int? MaxHeight { get; set; }

        /// <summary>
        /// Gets or sets the MaxWidth.
        /// </summary>
        /// <value>
        /// The MaxWidth.
        /// </value>
        public int? MaxWidth { get; set; }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        /// <value>
        /// The Name.
        /// </value>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the PreferredColorDepth.
        /// </summary>
        /// <value>
        /// The PreferredColorDepth.
        /// </value>
        public int PreferredColorDepth { get; set; }

        /// <summary>
        /// Gets or sets the PreferredFormat.
        /// </summary>
        /// <value>
        /// The PreferredFormat.
        /// </value>
        public int PreferredFormat { get; set; }

        /// <summary>
        /// Gets or sets the PreferredRequired.
        /// </summary>
        /// <value>
        /// The PreferredRequired.
        /// </value>
        public bool PreferredRequired { get; set; }

        /// <summary>
        /// Gets or sets the PreferredResolution.
        /// </summary>
        /// <value>
        /// The PreferredResolution.
        /// </value>
        public int PreferredResolution { get; set; }

        /// <summary>
        /// Gets or sets the RequiresViewSecurity.
        /// </summary>
        /// <value>
        /// The RequiresViewSecurity.
        /// </value>
        public bool RequiresViewSecurity { get; set; }

        /// <summary>
        /// Gets or sets the StorageEntityTypeId.
        /// </summary>
        /// <value>
        /// The StorageEntityTypeId.
        /// </value>
        public int? StorageEntityTypeId { get; set; }

        /// <summary>
        /// Gets or sets the CreatedDateTime.
        /// </summary>
        /// <value>
        /// The CreatedDateTime.
        /// </value>
        public DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// Gets or sets the ModifiedDateTime.
        /// </summary>
        /// <value>
        /// The ModifiedDateTime.
        /// </value>
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Gets or sets the CreatedByPersonAliasId.
        /// </summary>
        /// <value>
        /// The CreatedByPersonAliasId.
        /// </value>
        public int? CreatedByPersonAliasId { get; set; }

        /// <summary>
        /// Gets or sets the ModifiedByPersonAliasId.
        /// </summary>
        /// <value>
        /// The ModifiedByPersonAliasId.
        /// </value>
        public int? ModifiedByPersonAliasId { get; set; }

        /// <summary>
        /// Sets the properties from.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <param name="currentPerson">The current person.</param>
        /// <param name="loadAttributes">if set to <c>true</c> [load attributes].</param>
        public virtual void SetPropertiesFrom( Rock.Model.BinaryFileType model, Person currentPerson = null, bool loadAttributes = true )
        {
            if ( model == null )
            {
                return;
            }

            if ( loadAttributes && model is IHasAttributes hasAttributes )
            {
                if ( hasAttributes.Attributes == null )
                {
                    hasAttributes.LoadAttributes();
                }

                Attributes = hasAttributes.AttributeValues.Where( av =>
                {
                    var attribute = AttributeCache.Get( av.Value.AttributeId );
                    return attribute?.IsAuthorized( Rock.Security.Authorization.EDIT, currentPerson ) ?? false;
                } ).ToDictionary(
                    kvp => kvp.Key,
                    kvp => kvp.Value.ToViewModel<AttributeValueViewModel>() as object );
            }

            Id = model.Id;
            Guid = model.Guid;
            CacheControlHeaderSettings = model.CacheControlHeaderSettings;
            CacheToServerFileSystem = model.CacheToServerFileSystem;
            Description = model.Description;
            IconCssClass = model.IconCssClass;
            IsSystem = model.IsSystem;
            MaxHeight = model.MaxHeight;
            MaxWidth = model.MaxWidth;
            Name = model.Name;
            PreferredColorDepth = ( int ) model.PreferredColorDepth;
            PreferredFormat = ( int ) model.PreferredFormat;
            PreferredRequired = model.PreferredRequired;
            PreferredResolution = ( int ) model.PreferredResolution;
            RequiresViewSecurity = model.RequiresViewSecurity;
            StorageEntityTypeId = model.StorageEntityTypeId;
            CreatedDateTime = model.CreatedDateTime;
            ModifiedDateTime = model.ModifiedDateTime;
            CreatedByPersonAliasId = model.CreatedByPersonAliasId;
            ModifiedByPersonAliasId = model.ModifiedByPersonAliasId;

            SetAdditionalPropertiesFrom( model, currentPerson, loadAttributes );
        }

        /// <summary>
        /// Creates a view model from the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <param name="currentPerson" >The current person.</param>
        /// <param name="loadAttributes" >if set to <c>true</c> [load attributes].</param>
        /// <returns></returns>
        public static BinaryFileTypeViewModel From( Rock.Model.BinaryFileType model, Person currentPerson = null, bool loadAttributes = true )
        {
            var viewModel = new BinaryFileTypeViewModel();
            viewModel.SetPropertiesFrom( model, currentPerson, loadAttributes );
            return viewModel;
        }
    }
}
