//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using System;
using System.Linq;

namespace Rock.ViewModel
{
    /// <summary>
    /// FinancialTransactionAlertType View Model
    /// </summary>
    public partial class FinancialTransactionAlertTypeViewModel : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the AccountParticipantSystemCommunicationId.
        /// </summary>
        /// <value>
        /// The AccountParticipantSystemCommunicationId.
        /// </value>
        public int? AccountParticipantSystemCommunicationId { get; set; }

        /// <summary>
        /// Gets or sets the AlertSummaryNotificationGroupId.
        /// </summary>
        /// <value>
        /// The AlertSummaryNotificationGroupId.
        /// </value>
        public int? AlertSummaryNotificationGroupId { get; set; }

        /// <summary>
        /// Gets or sets the AlertType.
        /// </summary>
        /// <value>
        /// The AlertType.
        /// </value>
        public int AlertType { get; set; }

        /// <summary>
        /// Gets or sets the AmountSensitivityScale.
        /// </summary>
        /// <value>
        /// The AmountSensitivityScale.
        /// </value>
        public decimal? AmountSensitivityScale { get; set; }

        /// <summary>
        /// Gets or sets the CampusId.
        /// </summary>
        /// <value>
        /// The CampusId.
        /// </value>
        public int? CampusId { get; set; }

        /// <summary>
        /// Gets or sets the ConnectionOpportunityId.
        /// </summary>
        /// <value>
        /// The ConnectionOpportunityId.
        /// </value>
        public int? ConnectionOpportunityId { get; set; }

        /// <summary>
        /// Gets or sets the ContinueIfMatched.
        /// </summary>
        /// <value>
        /// The ContinueIfMatched.
        /// </value>
        public bool ContinueIfMatched { get; set; }

        /// <summary>
        /// Gets or sets the DataViewId.
        /// </summary>
        /// <value>
        /// The DataViewId.
        /// </value>
        public int? DataViewId { get; set; }

        /// <summary>
        /// Gets or sets the FinancialAccountId.
        /// </summary>
        /// <value>
        /// The FinancialAccountId.
        /// </value>
        public int? FinancialAccountId { get; set; }

        /// <summary>
        /// Gets or sets the FrequencySensitivityScale.
        /// </summary>
        /// <value>
        /// The FrequencySensitivityScale.
        /// </value>
        public decimal? FrequencySensitivityScale { get; set; }

        /// <summary>
        /// Gets or sets the IncludeChildFinancialAccounts.
        /// </summary>
        /// <value>
        /// The IncludeChildFinancialAccounts.
        /// </value>
        public bool IncludeChildFinancialAccounts { get; set; }

        /// <summary>
        /// Gets or sets the MaximumDaysSinceLastGift.
        /// </summary>
        /// <value>
        /// The MaximumDaysSinceLastGift.
        /// </value>
        public int? MaximumDaysSinceLastGift { get; set; }

        /// <summary>
        /// Gets or sets the MaximumGiftAmount.
        /// </summary>
        /// <value>
        /// The MaximumGiftAmount.
        /// </value>
        public decimal? MaximumGiftAmount { get; set; }

        /// <summary>
        /// Gets or sets the MaximumMedianGiftAmount.
        /// </summary>
        /// <value>
        /// The MaximumMedianGiftAmount.
        /// </value>
        public decimal? MaximumMedianGiftAmount { get; set; }

        /// <summary>
        /// Gets or sets the MinimumGiftAmount.
        /// </summary>
        /// <value>
        /// The MinimumGiftAmount.
        /// </value>
        public decimal? MinimumGiftAmount { get; set; }

        /// <summary>
        /// Gets or sets the MinimumMedianGiftAmount.
        /// </summary>
        /// <value>
        /// The MinimumMedianGiftAmount.
        /// </value>
        public decimal? MinimumMedianGiftAmount { get; set; }

        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        /// <value>
        /// The Name.
        /// </value>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Order.
        /// </summary>
        /// <value>
        /// The Order.
        /// </value>
        public int Order { get; set; }

        /// <summary>
        /// Gets or sets the RepeatPreventionDuration.
        /// </summary>
        /// <value>
        /// The RepeatPreventionDuration.
        /// </value>
        public int? RepeatPreventionDuration { get; set; }

        /// <summary>
        /// Gets or sets the RunDays.
        /// </summary>
        /// <value>
        /// The RunDays.
        /// </value>
        public int? RunDays { get; set; }

        /// <summary>
        /// Gets or sets the SendBusEvent.
        /// </summary>
        /// <value>
        /// The SendBusEvent.
        /// </value>
        public bool SendBusEvent { get; set; }

        /// <summary>
        /// Gets or sets the SystemCommunicationId.
        /// </summary>
        /// <value>
        /// The SystemCommunicationId.
        /// </value>
        public int? SystemCommunicationId { get; set; }

        /// <summary>
        /// Gets or sets the WorkflowTypeId.
        /// </summary>
        /// <value>
        /// The WorkflowTypeId.
        /// </value>
        public int? WorkflowTypeId { get; set; }

        /// <summary>
        /// Gets or sets the CreatedDateTime.
        /// </summary>
        /// <value>
        /// The CreatedDateTime.
        /// </value>
        public DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// Gets or sets the ModifiedDateTime.
        /// </summary>
        /// <value>
        /// The ModifiedDateTime.
        /// </value>
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Gets or sets the CreatedByPersonAliasId.
        /// </summary>
        /// <value>
        /// The CreatedByPersonAliasId.
        /// </value>
        public int? CreatedByPersonAliasId { get; set; }

        /// <summary>
        /// Gets or sets the ModifiedByPersonAliasId.
        /// </summary>
        /// <value>
        /// The ModifiedByPersonAliasId.
        /// </value>
        public int? ModifiedByPersonAliasId { get; set; }

    }
}
