//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

using System;
using System.Linq;

namespace Rock.ViewModel
{
    /// <summary>
    /// RegistrationTemplateDiscount View Model
    /// </summary>
    public partial class RegistrationTemplateDiscountViewModel : ViewModelBase
    {
        /// <summary>
        /// Gets or sets the AutoApplyDiscount.
        /// </summary>
        /// <value>
        /// The AutoApplyDiscount.
        /// </value>
        public bool AutoApplyDiscount { get; set; }

        /// <summary>
        /// Gets or sets the Code.
        /// </summary>
        /// <value>
        /// The Code.
        /// </value>
        public string Code { get; set; }

        /// <summary>
        /// Gets or sets the DiscountAmount.
        /// </summary>
        /// <value>
        /// The DiscountAmount.
        /// </value>
        public decimal DiscountAmount { get; set; }

        /// <summary>
        /// Gets or sets the DiscountPercentage.
        /// </summary>
        /// <value>
        /// The DiscountPercentage.
        /// </value>
        public decimal DiscountPercentage { get; set; }

        /// <summary>
        /// Gets or sets the EndDate.
        /// </summary>
        /// <value>
        /// The EndDate.
        /// </value>
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// Gets or sets the MaxRegistrants.
        /// </summary>
        /// <value>
        /// The MaxRegistrants.
        /// </value>
        public int? MaxRegistrants { get; set; }

        /// <summary>
        /// Gets or sets the MaxUsage.
        /// </summary>
        /// <value>
        /// The MaxUsage.
        /// </value>
        public int? MaxUsage { get; set; }

        /// <summary>
        /// Gets or sets the MinRegistrants.
        /// </summary>
        /// <value>
        /// The MinRegistrants.
        /// </value>
        public int? MinRegistrants { get; set; }

        /// <summary>
        /// Gets or sets the Order.
        /// </summary>
        /// <value>
        /// The Order.
        /// </value>
        public int Order { get; set; }

        /// <summary>
        /// Gets or sets the RegistrationTemplateId.
        /// </summary>
        /// <value>
        /// The RegistrationTemplateId.
        /// </value>
        public int RegistrationTemplateId { get; set; }

        /// <summary>
        /// Gets or sets the StartDate.
        /// </summary>
        /// <value>
        /// The StartDate.
        /// </value>
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// Gets or sets the CreatedDateTime.
        /// </summary>
        /// <value>
        /// The CreatedDateTime.
        /// </value>
        public DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// Gets or sets the ModifiedDateTime.
        /// </summary>
        /// <value>
        /// The ModifiedDateTime.
        /// </value>
        public DateTime? ModifiedDateTime { get; set; }

        /// <summary>
        /// Gets or sets the CreatedByPersonAliasId.
        /// </summary>
        /// <value>
        /// The CreatedByPersonAliasId.
        /// </value>
        public int? CreatedByPersonAliasId { get; set; }

        /// <summary>
        /// Gets or sets the ModifiedByPersonAliasId.
        /// </summary>
        /// <value>
        /// The ModifiedByPersonAliasId.
        /// </value>
        public int? ModifiedByPersonAliasId { get; set; }

    }
}
