<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>Rock.Blocks</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">$(DefineConstants);WEBFORMS</DefineConstants>
    <DefineConstants Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">$(DefineConstants);REVIEW_WEBFORMS</DefineConstants>
    <DefineConstants Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">$(DefineConstants);REVIEW_NET5_0_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Crm\AttributeValues.cs" />
    <Compile Remove="Example\LargeDatasetGrid.cs" />
    <Compile Remove="Example\PersonDetail.cs" />
    <Compile Remove="Example\PersonSecondary.cs" />
    <Compile Remove="Finance\TransactionEntry.cs" />
    <Compile Remove="Security\Login.cs" />
    <Compile Remove="Utility\StarkDetail.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rock.Common\Rock.Common.csproj" />
    <ProjectReference Include="..\Rock.ViewModels\Rock.ViewModels.csproj" />
    <ProjectReference Include="..\Rock\Rock.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Crm\" />
    <Folder Include="Finance\" />
    <Folder Include="Security\" />
    <Folder Include="Utility\" />
  </ItemGroup>

</Project>
