//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//

using System;
using System.Linq;

using Rock.Data;

namespace Rock.Model
{
    /// <summary>
    /// Attribute Service class
    /// </summary>
    public partial class AttributeService : Service<Attribute>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AttributeService"/> class
        /// </summary>
        public AttributeService()
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AttributeService"/> class
        /// </summary>
        public AttributeService(IRepository<Attribute> repository) : base(repository)
        {
        }

        /// <summary>
        /// Determines whether this instance can delete the specified item.
        /// </summary>
        /// <param name="item">The item.</param>
        /// <param name="errorMessage">The error message.</param>
        /// <returns>
        ///   <c>true</c> if this instance can delete the specified item; otherwise, <c>false</c>.
        /// </returns>
        public bool CanDelete( Attribute item, out string errorMessage )
        {
            errorMessage = string.Empty;
            return true;
        }
    }

    /// <summary>
    /// Generated Extension Methods
    /// </summary>
    public static class AttributeExtensionMethods
    {
        /// <summary>
        /// Copies all the entity properties from another Attribute entity
        /// </summary>
        public static void CopyPropertiesFrom( this Attribute target, Attribute source )
        {
            target.IsSystem = source.IsSystem;
            target.FieldTypeId = source.FieldTypeId;
            target.EntityTypeId = source.EntityTypeId;
            target.EntityTypeQualifierColumn = source.EntityTypeQualifierColumn;
            target.EntityTypeQualifierValue = source.EntityTypeQualifierValue;
            target.Key = source.Key;
            target.Name = source.Name;
            target.Category = source.Category;
            target.Description = source.Description;
            target.Order = source.Order;
            target.IsGridColumn = source.IsGridColumn;
            target.DefaultValue = source.DefaultValue;
            target.IsMultiValue = source.IsMultiValue;
            target.IsRequired = source.IsRequired;
            target.Id = source.Id;
            target.Guid = source.Guid;

        }
    }
}
