//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//

using System;
using System.Linq;

using Rock.Data;

namespace Rock.Model
{
    /// <summary>
    /// MarketingCampaignAd Service class
    /// </summary>
    public partial class MarketingCampaignAdService : Service<MarketingCampaignAd>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MarketingCampaignAdService"/> class
        /// </summary>
        public MarketingCampaignAdService()
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MarketingCampaignAdService"/> class
        /// </summary>
        public MarketingCampaignAdService(IRepository<MarketingCampaignAd> repository) : base(repository)
        {
        }

        /// <summary>
        /// Determines whether this instance can delete the specified item.
        /// </summary>
        /// <param name="item">The item.</param>
        /// <param name="errorMessage">The error message.</param>
        /// <returns>
        ///   <c>true</c> if this instance can delete the specified item; otherwise, <c>false</c>.
        /// </returns>
        public bool CanDelete( MarketingCampaignAd item, out string errorMessage )
        {
            errorMessage = string.Empty;
            return true;
        }
    }

    /// <summary>
    /// Generated Extension Methods
    /// </summary>
    public static class MarketingCampaignAdExtensionMethods
    {
        /// <summary>
        /// Copies all the entity properties from another MarketingCampaignAd entity
        /// </summary>
        public static void CopyPropertiesFrom( this MarketingCampaignAd target, MarketingCampaignAd source )
        {
            target.MarketingCampaignId = source.MarketingCampaignId;
            target.MarketingCampaignAdTypeId = source.MarketingCampaignAdTypeId;
            target.Priority = source.Priority;
            target.MarketingCampaignAdStatus = source.MarketingCampaignAdStatus;
            target.MarketingCampaignStatusPersonId = source.MarketingCampaignStatusPersonId;
            target.StartDate = source.StartDate;
            target.EndDate = source.EndDate;
            target.Url = source.Url;
            target.Id = source.Id;
            target.Guid = source.Guid;

        }
    }
}
