//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { Guid } from "@Obsidian/Types";

/** The runtime data the Account Tree View block ships to its Obsidian component. */
export type AccountTreeViewBag = {
    /** Gets or sets an error message to display in place of the tree. */
    errorMessage?: string | null;

    /** Gets or sets the accounts to expand on load. */
    expandedAccountGuids?: Guid[] | null;

    /**
     * Gets or sets whether inactive accounts are hidden, reflecting the person's saved preference
     * (or the block's initial active setting when no preference is stored).
     */
    hideInactiveAccounts: boolean;

    /** Gets or sets whether the add-account chrome is shown (block edit or elevated child-add auth). */
    isAddAccountVisible: boolean;

    /** Gets or sets whether the Add Child To Selected action is enabled for the current selection. */
    isAddChildEnabled: boolean;

    /** Gets or sets whether the Add Top-Level action is enabled. */
    isAddRootEnabled: boolean;

    /** Gets or sets the accounts selected on load, resolved from the page parameter for deep-linking. */
    selectedAccountGuids?: Guid[] | null;
};
