// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//
namespace Rock.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    /// <summary>
    ///
    /// </summary>
    public partial class AddCreatedModifiedFields : Rock.Migrations.RockMigration3
    {
        /// <summary>
        /// Operations to be performed during the upgrade process.
        /// </summary>
        public override void Up()
        {
            DropForeignKey("dbo.History", "CreatedByPersonId", "dbo.Person");
            DropForeignKey("dbo.HtmlContent", "LastModifiedPersonId", "dbo.Person");
            DropIndex("dbo.History", new[] { "CreatedByPersonId" });
            DropIndex("dbo.HtmlContent", new[] { "LastModifiedPersonId" });
            AddColumn("dbo.Attendance", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Attendance", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Attendance", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Attendance", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Device", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Device", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Device", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Device", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DefinedValue", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.DefinedValue", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.DefinedValue", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DefinedValue", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DefinedType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.DefinedType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.DefinedType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DefinedType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FieldType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FieldType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FieldType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FieldType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Location", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Location", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Location", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Location", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupLocation", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupLocation", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupLocation", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupLocation", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Group", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Group", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Group", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Group", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Campus", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Campus", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Campus", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Campus", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupTypeRole", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupTypeRole", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupTypeRole", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupTypeRole", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupMember", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupMember", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.GroupMember", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.GroupMember", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Person", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Person", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Person", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Person", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.EmailTemplate", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.EmailTemplate", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.EmailTemplate", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.EmailTemplate", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PhoneNumber", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.PhoneNumber", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.PhoneNumber", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PhoneNumber", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BinaryFile", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.BinaryFile", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.BinaryFile", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BinaryFile", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BinaryFileType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.BinaryFileType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.BinaryFileType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BinaryFileType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BinaryFileData", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.BinaryFileData", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.BinaryFileData", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BinaryFileData", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.UserLogin", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.UserLogin", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.UserLogin", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.UserLogin", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Schedule", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Schedule", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Schedule", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Schedule", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Category", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Category", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Category", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Category", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Attribute", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Attribute", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Attribute", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Attribute", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.AttributeValue", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.AttributeValue", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.AttributeValue", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.AttributeValue", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Auth", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Auth", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Auth", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Auth", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Block", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Block", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Block", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Block", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BlockType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.BlockType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.BlockType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.BlockType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Layout", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Layout", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Layout", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Layout", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Page", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Page", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Page", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Page", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PageContext", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.PageContext", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PageContext", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PageRoute", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.PageRoute", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.PageRoute", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PageRoute", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Site", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Site", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Site", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Site", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.SiteDomain", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.SiteDomain", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.SiteDomain", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.SiteDomain", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.CommunicationRecipient", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.CommunicationRecipient", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.CommunicationRecipient", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.CommunicationRecipient", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Communication", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Communication", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Communication", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Communication", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DataViewFilter", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.DataViewFilter", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.DataViewFilter", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DataViewFilter", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DataView", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.DataView", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.DataView", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.DataView", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ExceptionLog", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.ExceptionLog", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.ExceptionLog", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ExceptionLog", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialAccount", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialAccount", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialAccount", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialAccount", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialBatch", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialBatch", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialBatch", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialBatch", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransaction", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransaction", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransaction", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransaction", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransactionImage", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransactionImage", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransactionImage", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransactionImage", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransactionRefund", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransactionRefund", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransactionRefund", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransactionRefund", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialScheduledTransaction", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialScheduledTransaction", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialScheduledTransaction", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialScheduledTransaction", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialScheduledTransactionDetail", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialScheduledTransactionDetail", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialScheduledTransactionDetail", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialScheduledTransactionDetail", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransactionDetail", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransactionDetail", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialTransactionDetail", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialTransactionDetail", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialPersonBankAccount", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialPersonBankAccount", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialPersonBankAccount", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialPersonBankAccount", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialPersonSavedAccount", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialPersonSavedAccount", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialPersonSavedAccount", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialPersonSavedAccount", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialPledge", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialPledge", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.FinancialPledge", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.FinancialPledge", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.History", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.History", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.History", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.History", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.HtmlContent", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.HtmlContent", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.HtmlContent", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.HtmlContent", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignAd", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignAd", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignAd", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignAd", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaign", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaign", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaign", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaign", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignAudience", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignAudience", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignAudience", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignAudience", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignCampus", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignCampus", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignCampus", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignCampus", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignAdType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignAdType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.MarketingCampaignAdType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MarketingCampaignAdType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Metric", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Metric", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Metric", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Metric", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MetricValue", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.MetricValue", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.MetricValue", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.MetricValue", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Note", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Note", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Note", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Note", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.NoteType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.NoteType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.NoteType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.NoteType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PrayerRequest", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.PrayerRequest", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.PrayerRequest", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.PrayerRequest", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ReportField", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.ReportField", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.ReportField", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ReportField", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Report", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Report", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Report", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Report", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ServiceJob", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.ServiceJob", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.ServiceJob", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ServiceJob", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ServiceLog", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.ServiceLog", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.ServiceLog", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.ServiceLog", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.TaggedItem", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.TaggedItem", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.TaggedItem", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.TaggedItem", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Tag", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Tag", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Tag", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Tag", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowAction", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowAction", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowAction", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowAction", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowActionType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowActionType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowActionType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowActionType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowActivityType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowActivityType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowActivityType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowActivityType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowType", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowType", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowType", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowType", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowActivity", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowActivity", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.WorkflowActivity", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.WorkflowActivity", "ModifiedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Workflow", "CreatedDateTime", c => c.DateTime());
            AddColumn("dbo.Workflow", "ModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.Workflow", "CreatedByPersonAliasId", c => c.Int());
            AddColumn("dbo.Workflow", "ModifiedByPersonAliasId", c => c.Int());
            CreateIndex("dbo.DefinedValue", "CreatedByPersonAliasId");
            CreateIndex("dbo.DefinedType", "CreatedByPersonAliasId");
            CreateIndex("dbo.FieldType", "CreatedByPersonAliasId");
            CreateIndex("dbo.FieldType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.DefinedType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.DefinedValue", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Person", "CreatedByPersonAliasId");
            CreateIndex("dbo.EmailTemplate", "CreatedByPersonAliasId");
            CreateIndex("dbo.EmailTemplate", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Campus", "CreatedByPersonAliasId");
            CreateIndex("dbo.Location", "CreatedByPersonAliasId");
            CreateIndex("dbo.GroupLocation", "CreatedByPersonAliasId");
            CreateIndex("dbo.GroupLocation", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Category", "CreatedByPersonAliasId");
            CreateIndex("dbo.Category", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Schedule", "CreatedByPersonAliasId");
            CreateIndex("dbo.Schedule", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Location", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Device", "CreatedByPersonAliasId");
            CreateIndex("dbo.Device", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Campus", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Group", "CreatedByPersonAliasId");
            CreateIndex("dbo.GroupType", "CreatedByPersonAliasId");
            CreateIndex("dbo.GroupTypeRole", "CreatedByPersonAliasId");
            CreateIndex("dbo.GroupTypeRole", "ModifiedByPersonAliasId");
            CreateIndex("dbo.GroupType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.GroupMember", "CreatedByPersonAliasId");
            CreateIndex("dbo.GroupMember", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Group", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Person", "ModifiedByPersonAliasId");
            CreateIndex("dbo.PhoneNumber", "CreatedByPersonAliasId");
            CreateIndex("dbo.PhoneNumber", "ModifiedByPersonAliasId");
            CreateIndex("dbo.BinaryFileType", "CreatedByPersonAliasId");
            CreateIndex("dbo.BinaryFileType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.BinaryFile", "CreatedByPersonAliasId");
            CreateIndex("dbo.BinaryFileData", "CreatedByPersonAliasId");
            CreateIndex("dbo.BinaryFileData", "ModifiedByPersonAliasId");
            CreateIndex("dbo.BinaryFile", "ModifiedByPersonAliasId");
            CreateIndex("dbo.UserLogin", "CreatedByPersonAliasId");
            CreateIndex("dbo.UserLogin", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Attendance", "CreatedByPersonAliasId");
            CreateIndex("dbo.Attendance", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Attribute", "CreatedByPersonAliasId");
            CreateIndex("dbo.Attribute", "ModifiedByPersonAliasId");
            CreateIndex("dbo.AttributeValue", "CreatedByPersonAliasId");
            CreateIndex("dbo.AttributeValue", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Auth", "CreatedByPersonAliasId");
            CreateIndex("dbo.Auth", "ModifiedByPersonAliasId");
            CreateIndex("dbo.BlockType", "CreatedByPersonAliasId");
            CreateIndex("dbo.BlockType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Block", "CreatedByPersonAliasId");
            CreateIndex("dbo.Layout", "CreatedByPersonAliasId");
            CreateIndex("dbo.Layout", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Page", "CreatedByPersonAliasId");
            CreateIndex("dbo.Page", "ModifiedByPersonAliasId");
            CreateIndex("dbo.PageContext", "CreatedByPersonAliasId");
            CreateIndex("dbo.PageContext", "ModifiedByPersonAliasId");
            CreateIndex("dbo.PageRoute", "CreatedByPersonAliasId");
            CreateIndex("dbo.PageRoute", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Site", "CreatedByPersonAliasId");
            CreateIndex("dbo.Site", "ModifiedByPersonAliasId");
            CreateIndex("dbo.SiteDomain", "CreatedByPersonAliasId");
            CreateIndex("dbo.SiteDomain", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Block", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Communication", "CreatedByPersonAliasId");
            CreateIndex("dbo.Communication", "ModifiedByPersonAliasId");
            CreateIndex("dbo.CommunicationRecipient", "CreatedByPersonAliasId");
            CreateIndex("dbo.CommunicationRecipient", "ModifiedByPersonAliasId");
            CreateIndex("dbo.DataViewFilter", "CreatedByPersonAliasId");
            CreateIndex("dbo.DataViewFilter", "ModifiedByPersonAliasId");
            CreateIndex("dbo.DataView", "CreatedByPersonAliasId");
            CreateIndex("dbo.DataView", "ModifiedByPersonAliasId");
            CreateIndex("dbo.ExceptionLog", "CreatedByPersonAliasId");
            CreateIndex("dbo.ExceptionLog", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialAccount", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialAccount", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialBatch", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialBatch", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialTransaction", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialTransactionImage", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialTransactionImage", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialTransaction", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialTransactionRefund", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialTransactionRefund", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialScheduledTransaction", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialScheduledTransaction", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialScheduledTransactionDetail", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialScheduledTransactionDetail", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialTransactionDetail", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialTransactionDetail", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialPersonBankAccount", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialPersonBankAccount", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialPersonSavedAccount", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialPersonSavedAccount", "ModifiedByPersonAliasId");
            CreateIndex("dbo.FinancialPledge", "CreatedByPersonAliasId");
            CreateIndex("dbo.FinancialPledge", "ModifiedByPersonAliasId");
            CreateIndex("dbo.History", "CreatedByPersonAliasId");
            CreateIndex("dbo.History", "ModifiedByPersonAliasId");
            CreateIndex("dbo.HtmlContent", "CreatedByPersonAliasId");
            CreateIndex("dbo.HtmlContent", "ModifiedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignAd", "CreatedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaign", "CreatedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignAudience", "CreatedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignAudience", "ModifiedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignCampus", "CreatedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignCampus", "ModifiedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaign", "ModifiedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignAdType", "CreatedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignAdType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.MarketingCampaignAd", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Metric", "CreatedByPersonAliasId");
            CreateIndex("dbo.MetricValue", "CreatedByPersonAliasId");
            CreateIndex("dbo.MetricValue", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Metric", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Note", "CreatedByPersonAliasId");
            CreateIndex("dbo.Note", "ModifiedByPersonAliasId");
            CreateIndex("dbo.NoteType", "CreatedByPersonAliasId");
            CreateIndex("dbo.NoteType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.PrayerRequest", "CreatedByPersonAliasId");
            CreateIndex("dbo.PrayerRequest", "ModifiedByPersonAliasId");
            CreateIndex("dbo.ReportField", "CreatedByPersonAliasId");
            CreateIndex("dbo.ReportField", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Report", "CreatedByPersonAliasId");
            CreateIndex("dbo.Report", "ModifiedByPersonAliasId");
            CreateIndex("dbo.ServiceJob", "CreatedByPersonAliasId");
            CreateIndex("dbo.ServiceJob", "ModifiedByPersonAliasId");
            CreateIndex("dbo.ServiceLog", "CreatedByPersonAliasId");
            CreateIndex("dbo.ServiceLog", "ModifiedByPersonAliasId");
            CreateIndex("dbo.TaggedItem", "CreatedByPersonAliasId");
            CreateIndex("dbo.TaggedItem", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Tag", "CreatedByPersonAliasId");
            CreateIndex("dbo.Tag", "ModifiedByPersonAliasId");
            CreateIndex("dbo.WorkflowActivityType", "CreatedByPersonAliasId");
            CreateIndex("dbo.WorkflowActivityType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.WorkflowType", "CreatedByPersonAliasId");
            CreateIndex("dbo.WorkflowType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.WorkflowActionType", "CreatedByPersonAliasId");
            CreateIndex("dbo.WorkflowActionType", "ModifiedByPersonAliasId");
            CreateIndex("dbo.WorkflowActivity", "CreatedByPersonAliasId");
            CreateIndex("dbo.WorkflowActivity", "ModifiedByPersonAliasId");
            CreateIndex("dbo.Workflow", "CreatedByPersonAliasId");
            CreateIndex("dbo.Workflow", "ModifiedByPersonAliasId");
            CreateIndex("dbo.WorkflowAction", "CreatedByPersonAliasId");
            CreateIndex("dbo.WorkflowAction", "ModifiedByPersonAliasId");
            AddForeignKey("dbo.DefinedValue", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.DefinedType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FieldType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FieldType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.DefinedType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.DefinedValue", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Person", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.EmailTemplate", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.EmailTemplate", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Campus", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Location", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupLocation", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupLocation", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Category", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Category", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Schedule", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Schedule", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Location", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Device", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Device", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Campus", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Group", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupTypeRole", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupTypeRole", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupMember", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.GroupMember", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Group", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Person", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PhoneNumber", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PhoneNumber", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BinaryFileType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BinaryFileType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BinaryFile", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BinaryFileData", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BinaryFileData", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BinaryFile", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.UserLogin", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.UserLogin", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Attendance", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Attendance", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Attribute", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Attribute", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.AttributeValue", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.AttributeValue", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Auth", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Auth", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BlockType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.BlockType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Block", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Layout", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Layout", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Page", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Page", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PageContext", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PageContext", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PageRoute", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PageRoute", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Site", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Site", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.SiteDomain", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.SiteDomain", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Block", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Communication", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Communication", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.CommunicationRecipient", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.CommunicationRecipient", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.DataViewFilter", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.DataViewFilter", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.DataView", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.DataView", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ExceptionLog", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ExceptionLog", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialAccount", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialAccount", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialBatch", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialBatch", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransaction", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransactionImage", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransactionImage", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransaction", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransactionRefund", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransactionRefund", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialScheduledTransaction", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialScheduledTransaction", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialScheduledTransactionDetail", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialScheduledTransactionDetail", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransactionDetail", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialTransactionDetail", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialPersonBankAccount", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialPersonBankAccount", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialPersonSavedAccount", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialPersonSavedAccount", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialPledge", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.FinancialPledge", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.History", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.History", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.HtmlContent", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.HtmlContent", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignAd", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaign", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignAudience", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignAudience", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignCampus", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignCampus", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaign", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignAdType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignAdType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MarketingCampaignAd", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Metric", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MetricValue", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.MetricValue", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Metric", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Note", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Note", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.NoteType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.NoteType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PrayerRequest", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.PrayerRequest", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ReportField", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ReportField", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Report", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Report", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ServiceJob", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ServiceJob", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ServiceLog", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.ServiceLog", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.TaggedItem", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.TaggedItem", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Tag", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Tag", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowActivityType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowActivityType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowActionType", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowActionType", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowActivity", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowActivity", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Workflow", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.Workflow", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowAction", "CreatedByPersonAliasId", "dbo.PersonAlias", "Id");
            AddForeignKey("dbo.WorkflowAction", "ModifiedByPersonAliasId", "dbo.PersonAlias", "Id");

            Sql( @"
    UPDATE [UserLogin] SET [CreatedDateTime] = [CreationDateTime]

    UPDATE H SET 
        [CreatedDateTime] = H.[CreationDateTime], 
        [CreatedByPersonAliasId] = A.[Id]
    FROM [History] H
    INNER JOIN [PersonAlias] A ON A.[AliasPersonId] = H.[CreatedByPersonId]

    UPDATE H SET 
        [ModifiedDateTime] = H.[LastModifiedDateTime], 
        [ModifiedByPersonAliasId] = A.[Id]
    FROM [HtmlContent] H
    INNER JOIN [PersonAlias] A ON A.[AliasPersonId] = H.[LastModifiedPersonId]
" );
            DropColumn("dbo.UserLogin", "CreationDateTime");
            DropColumn("dbo.History", "CreatedByPersonId");
            DropColumn("dbo.History", "CreationDateTime");
            DropColumn("dbo.HtmlContent", "LastModifiedDateTime");
            DropColumn("dbo.HtmlContent", "LastModifiedPersonId");
        }
        
        /// <summary>
        /// Operations to be performed during the downgrade process.
        /// </summary>
        public override void Down()
        {
            AddColumn("dbo.HtmlContent", "LastModifiedPersonId", c => c.Int());
            AddColumn("dbo.HtmlContent", "LastModifiedDateTime", c => c.DateTime());
            AddColumn("dbo.History", "CreationDateTime", c => c.DateTime(nullable: false));
            AddColumn("dbo.History", "CreatedByPersonId", c => c.Int());
            AddColumn("dbo.UserLogin", "CreationDateTime", c => c.DateTime());

            Sql( @"
    UPDATE [UserLogin] SET [CreationDateTime] = [CreatedDateTime]

    UPDATE H SET 
        [CreationDateTime] = H.[CreatedDateTime], 
        [CreatedByPersonId] = A.[PersonId]
    FROM [History] H
    INNER JOIN [PersonAlias] A ON A.[Id] = H.[CreatedByPersonAliasId]

    UPDATE H SET 
        [LastModifiedDateTime] = H.[ModifiedDateTime], 
        [LastModifiedPersonId] = A.[PersonId]
    FROM [HtmlContent] H
    INNER JOIN [PersonAlias] A ON A.[Id] = H.[ModifiedByPersonAliasId]
" );
            DropForeignKey("dbo.WorkflowAction", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowAction", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Workflow", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Workflow", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowActivity", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowActivity", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowActionType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowActionType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowActivityType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.WorkflowActivityType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Tag", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Tag", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.TaggedItem", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.TaggedItem", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ServiceLog", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ServiceLog", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ServiceJob", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ServiceJob", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Report", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Report", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ReportField", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ReportField", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PrayerRequest", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PrayerRequest", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.NoteType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.NoteType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Note", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Note", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Metric", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MetricValue", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MetricValue", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Metric", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignAd", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignAdType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignAdType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaign", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignCampus", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignCampus", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignAudience", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignAudience", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaign", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.MarketingCampaignAd", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.HtmlContent", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.HtmlContent", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.History", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.History", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialPledge", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialPledge", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialPersonSavedAccount", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialPersonSavedAccount", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialPersonBankAccount", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialPersonBankAccount", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransactionDetail", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransactionDetail", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialScheduledTransactionDetail", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialScheduledTransactionDetail", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialScheduledTransaction", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialScheduledTransaction", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransactionRefund", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransactionRefund", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransaction", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransactionImage", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransactionImage", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialTransaction", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialBatch", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialBatch", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialAccount", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FinancialAccount", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ExceptionLog", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.ExceptionLog", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DataView", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DataView", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DataViewFilter", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DataViewFilter", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.CommunicationRecipient", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.CommunicationRecipient", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Communication", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Communication", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Block", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.SiteDomain", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.SiteDomain", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Site", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Site", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PageRoute", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PageRoute", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PageContext", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PageContext", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Page", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Page", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Layout", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Layout", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Block", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BlockType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BlockType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Auth", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Auth", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.AttributeValue", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.AttributeValue", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Attribute", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Attribute", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Attendance", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Attendance", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.UserLogin", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.UserLogin", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BinaryFile", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BinaryFileData", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BinaryFileData", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BinaryFile", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BinaryFileType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.BinaryFileType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PhoneNumber", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.PhoneNumber", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Person", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Group", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupMember", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupMember", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupTypeRole", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupTypeRole", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Group", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Campus", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Device", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Device", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Location", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Schedule", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Schedule", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Category", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Category", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupLocation", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.GroupLocation", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Location", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Campus", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.EmailTemplate", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.EmailTemplate", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.Person", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DefinedValue", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DefinedType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FieldType", "ModifiedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.FieldType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DefinedType", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropForeignKey("dbo.DefinedValue", "CreatedByPersonAliasId", "dbo.PersonAlias");
            DropIndex("dbo.WorkflowAction", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.WorkflowAction", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Workflow", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Workflow", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.WorkflowActivity", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.WorkflowActivity", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.WorkflowActionType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.WorkflowActionType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.WorkflowType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.WorkflowType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.WorkflowActivityType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.WorkflowActivityType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Tag", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Tag", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.TaggedItem", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.TaggedItem", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.ServiceLog", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.ServiceLog", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.ServiceJob", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.ServiceJob", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Report", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Report", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.ReportField", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.ReportField", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.PrayerRequest", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.PrayerRequest", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.NoteType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.NoteType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Note", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Note", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Metric", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.MetricValue", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.MetricValue", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Metric", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignAd", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignAdType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignAdType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaign", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignCampus", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignCampus", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignAudience", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignAudience", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaign", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.MarketingCampaignAd", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.HtmlContent", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.HtmlContent", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.History", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.History", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialPledge", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialPledge", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialPersonSavedAccount", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialPersonSavedAccount", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialPersonBankAccount", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialPersonBankAccount", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialTransactionDetail", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialTransactionDetail", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialScheduledTransactionDetail", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialScheduledTransactionDetail", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialScheduledTransaction", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialScheduledTransaction", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialTransactionRefund", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialTransactionRefund", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialTransaction", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialTransactionImage", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialTransactionImage", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialTransaction", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialBatch", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialBatch", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.FinancialAccount", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FinancialAccount", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.ExceptionLog", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.ExceptionLog", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.DataView", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.DataView", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.DataViewFilter", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.DataViewFilter", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.CommunicationRecipient", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.CommunicationRecipient", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Communication", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Communication", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Block", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.SiteDomain", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.SiteDomain", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Site", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Site", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.PageRoute", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.PageRoute", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.PageContext", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.PageContext", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Page", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Page", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Layout", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Layout", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Block", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.BlockType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.BlockType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Auth", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Auth", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.AttributeValue", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.AttributeValue", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Attribute", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Attribute", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Attendance", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Attendance", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.UserLogin", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.UserLogin", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.BinaryFile", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.BinaryFileData", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.BinaryFileData", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.BinaryFile", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.BinaryFileType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.BinaryFileType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.PhoneNumber", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.PhoneNumber", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Person", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Group", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.GroupMember", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.GroupMember", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.GroupType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.GroupTypeRole", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.GroupTypeRole", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.GroupType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Group", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Campus", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Device", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Device", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Location", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Schedule", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Schedule", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Category", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.Category", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.GroupLocation", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.GroupLocation", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Location", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Campus", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.EmailTemplate", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.EmailTemplate", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.Person", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.DefinedValue", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.DefinedType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FieldType", new[] { "ModifiedByPersonAliasId" });
            DropIndex("dbo.FieldType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.DefinedType", new[] { "CreatedByPersonAliasId" });
            DropIndex("dbo.DefinedValue", new[] { "CreatedByPersonAliasId" });
            DropColumn("dbo.Workflow", "ModifiedByPersonAliasId");
            DropColumn("dbo.Workflow", "CreatedByPersonAliasId");
            DropColumn("dbo.Workflow", "ModifiedDateTime");
            DropColumn("dbo.Workflow", "CreatedDateTime");
            DropColumn("dbo.WorkflowActivity", "ModifiedByPersonAliasId");
            DropColumn("dbo.WorkflowActivity", "CreatedByPersonAliasId");
            DropColumn("dbo.WorkflowActivity", "ModifiedDateTime");
            DropColumn("dbo.WorkflowActivity", "CreatedDateTime");
            DropColumn("dbo.WorkflowType", "ModifiedByPersonAliasId");
            DropColumn("dbo.WorkflowType", "CreatedByPersonAliasId");
            DropColumn("dbo.WorkflowType", "ModifiedDateTime");
            DropColumn("dbo.WorkflowType", "CreatedDateTime");
            DropColumn("dbo.WorkflowActivityType", "ModifiedByPersonAliasId");
            DropColumn("dbo.WorkflowActivityType", "CreatedByPersonAliasId");
            DropColumn("dbo.WorkflowActivityType", "ModifiedDateTime");
            DropColumn("dbo.WorkflowActivityType", "CreatedDateTime");
            DropColumn("dbo.WorkflowActionType", "ModifiedByPersonAliasId");
            DropColumn("dbo.WorkflowActionType", "CreatedByPersonAliasId");
            DropColumn("dbo.WorkflowActionType", "ModifiedDateTime");
            DropColumn("dbo.WorkflowActionType", "CreatedDateTime");
            DropColumn("dbo.WorkflowAction", "ModifiedByPersonAliasId");
            DropColumn("dbo.WorkflowAction", "CreatedByPersonAliasId");
            DropColumn("dbo.WorkflowAction", "ModifiedDateTime");
            DropColumn("dbo.WorkflowAction", "CreatedDateTime");
            DropColumn("dbo.Tag", "ModifiedByPersonAliasId");
            DropColumn("dbo.Tag", "CreatedByPersonAliasId");
            DropColumn("dbo.Tag", "ModifiedDateTime");
            DropColumn("dbo.Tag", "CreatedDateTime");
            DropColumn("dbo.TaggedItem", "ModifiedByPersonAliasId");
            DropColumn("dbo.TaggedItem", "CreatedByPersonAliasId");
            DropColumn("dbo.TaggedItem", "ModifiedDateTime");
            DropColumn("dbo.TaggedItem", "CreatedDateTime");
            DropColumn("dbo.ServiceLog", "ModifiedByPersonAliasId");
            DropColumn("dbo.ServiceLog", "CreatedByPersonAliasId");
            DropColumn("dbo.ServiceLog", "ModifiedDateTime");
            DropColumn("dbo.ServiceLog", "CreatedDateTime");
            DropColumn("dbo.ServiceJob", "ModifiedByPersonAliasId");
            DropColumn("dbo.ServiceJob", "CreatedByPersonAliasId");
            DropColumn("dbo.ServiceJob", "ModifiedDateTime");
            DropColumn("dbo.ServiceJob", "CreatedDateTime");
            DropColumn("dbo.Report", "ModifiedByPersonAliasId");
            DropColumn("dbo.Report", "CreatedByPersonAliasId");
            DropColumn("dbo.Report", "ModifiedDateTime");
            DropColumn("dbo.Report", "CreatedDateTime");
            DropColumn("dbo.ReportField", "ModifiedByPersonAliasId");
            DropColumn("dbo.ReportField", "CreatedByPersonAliasId");
            DropColumn("dbo.ReportField", "ModifiedDateTime");
            DropColumn("dbo.ReportField", "CreatedDateTime");
            DropColumn("dbo.PrayerRequest", "ModifiedByPersonAliasId");
            DropColumn("dbo.PrayerRequest", "CreatedByPersonAliasId");
            DropColumn("dbo.PrayerRequest", "ModifiedDateTime");
            DropColumn("dbo.PrayerRequest", "CreatedDateTime");
            DropColumn("dbo.NoteType", "ModifiedByPersonAliasId");
            DropColumn("dbo.NoteType", "CreatedByPersonAliasId");
            DropColumn("dbo.NoteType", "ModifiedDateTime");
            DropColumn("dbo.NoteType", "CreatedDateTime");
            DropColumn("dbo.Note", "ModifiedByPersonAliasId");
            DropColumn("dbo.Note", "CreatedByPersonAliasId");
            DropColumn("dbo.Note", "ModifiedDateTime");
            DropColumn("dbo.Note", "CreatedDateTime");
            DropColumn("dbo.MetricValue", "ModifiedByPersonAliasId");
            DropColumn("dbo.MetricValue", "CreatedByPersonAliasId");
            DropColumn("dbo.MetricValue", "ModifiedDateTime");
            DropColumn("dbo.MetricValue", "CreatedDateTime");
            DropColumn("dbo.Metric", "ModifiedByPersonAliasId");
            DropColumn("dbo.Metric", "CreatedByPersonAliasId");
            DropColumn("dbo.Metric", "ModifiedDateTime");
            DropColumn("dbo.Metric", "CreatedDateTime");
            DropColumn("dbo.MarketingCampaignAdType", "ModifiedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignAdType", "CreatedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignAdType", "ModifiedDateTime");
            DropColumn("dbo.MarketingCampaignAdType", "CreatedDateTime");
            DropColumn("dbo.MarketingCampaignCampus", "ModifiedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignCampus", "CreatedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignCampus", "ModifiedDateTime");
            DropColumn("dbo.MarketingCampaignCampus", "CreatedDateTime");
            DropColumn("dbo.MarketingCampaignAudience", "ModifiedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignAudience", "CreatedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignAudience", "ModifiedDateTime");
            DropColumn("dbo.MarketingCampaignAudience", "CreatedDateTime");
            DropColumn("dbo.MarketingCampaign", "ModifiedByPersonAliasId");
            DropColumn("dbo.MarketingCampaign", "CreatedByPersonAliasId");
            DropColumn("dbo.MarketingCampaign", "ModifiedDateTime");
            DropColumn("dbo.MarketingCampaign", "CreatedDateTime");
            DropColumn("dbo.MarketingCampaignAd", "ModifiedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignAd", "CreatedByPersonAliasId");
            DropColumn("dbo.MarketingCampaignAd", "ModifiedDateTime");
            DropColumn("dbo.MarketingCampaignAd", "CreatedDateTime");
            DropColumn("dbo.HtmlContent", "ModifiedByPersonAliasId");
            DropColumn("dbo.HtmlContent", "CreatedByPersonAliasId");
            DropColumn("dbo.HtmlContent", "ModifiedDateTime");
            DropColumn("dbo.HtmlContent", "CreatedDateTime");
            DropColumn("dbo.History", "ModifiedByPersonAliasId");
            DropColumn("dbo.History", "CreatedByPersonAliasId");
            DropColumn("dbo.History", "ModifiedDateTime");
            DropColumn("dbo.History", "CreatedDateTime");
            DropColumn("dbo.FinancialPledge", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialPledge", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialPledge", "ModifiedDateTime");
            DropColumn("dbo.FinancialPledge", "CreatedDateTime");
            DropColumn("dbo.FinancialPersonSavedAccount", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialPersonSavedAccount", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialPersonSavedAccount", "ModifiedDateTime");
            DropColumn("dbo.FinancialPersonSavedAccount", "CreatedDateTime");
            DropColumn("dbo.FinancialPersonBankAccount", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialPersonBankAccount", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialPersonBankAccount", "ModifiedDateTime");
            DropColumn("dbo.FinancialPersonBankAccount", "CreatedDateTime");
            DropColumn("dbo.FinancialTransactionDetail", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialTransactionDetail", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialTransactionDetail", "ModifiedDateTime");
            DropColumn("dbo.FinancialTransactionDetail", "CreatedDateTime");
            DropColumn("dbo.FinancialScheduledTransactionDetail", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialScheduledTransactionDetail", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialScheduledTransactionDetail", "ModifiedDateTime");
            DropColumn("dbo.FinancialScheduledTransactionDetail", "CreatedDateTime");
            DropColumn("dbo.FinancialScheduledTransaction", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialScheduledTransaction", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialScheduledTransaction", "ModifiedDateTime");
            DropColumn("dbo.FinancialScheduledTransaction", "CreatedDateTime");
            DropColumn("dbo.FinancialTransactionRefund", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialTransactionRefund", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialTransactionRefund", "ModifiedDateTime");
            DropColumn("dbo.FinancialTransactionRefund", "CreatedDateTime");
            DropColumn("dbo.FinancialTransactionImage", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialTransactionImage", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialTransactionImage", "ModifiedDateTime");
            DropColumn("dbo.FinancialTransactionImage", "CreatedDateTime");
            DropColumn("dbo.FinancialTransaction", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialTransaction", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialTransaction", "ModifiedDateTime");
            DropColumn("dbo.FinancialTransaction", "CreatedDateTime");
            DropColumn("dbo.FinancialBatch", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialBatch", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialBatch", "ModifiedDateTime");
            DropColumn("dbo.FinancialBatch", "CreatedDateTime");
            DropColumn("dbo.FinancialAccount", "ModifiedByPersonAliasId");
            DropColumn("dbo.FinancialAccount", "CreatedByPersonAliasId");
            DropColumn("dbo.FinancialAccount", "ModifiedDateTime");
            DropColumn("dbo.FinancialAccount", "CreatedDateTime");
            DropColumn("dbo.ExceptionLog", "ModifiedByPersonAliasId");
            DropColumn("dbo.ExceptionLog", "CreatedByPersonAliasId");
            DropColumn("dbo.ExceptionLog", "ModifiedDateTime");
            DropColumn("dbo.ExceptionLog", "CreatedDateTime");
            DropColumn("dbo.DataView", "ModifiedByPersonAliasId");
            DropColumn("dbo.DataView", "CreatedByPersonAliasId");
            DropColumn("dbo.DataView", "ModifiedDateTime");
            DropColumn("dbo.DataView", "CreatedDateTime");
            DropColumn("dbo.DataViewFilter", "ModifiedByPersonAliasId");
            DropColumn("dbo.DataViewFilter", "CreatedByPersonAliasId");
            DropColumn("dbo.DataViewFilter", "ModifiedDateTime");
            DropColumn("dbo.DataViewFilter", "CreatedDateTime");
            DropColumn("dbo.Communication", "ModifiedByPersonAliasId");
            DropColumn("dbo.Communication", "CreatedByPersonAliasId");
            DropColumn("dbo.Communication", "ModifiedDateTime");
            DropColumn("dbo.Communication", "CreatedDateTime");
            DropColumn("dbo.CommunicationRecipient", "ModifiedByPersonAliasId");
            DropColumn("dbo.CommunicationRecipient", "CreatedByPersonAliasId");
            DropColumn("dbo.CommunicationRecipient", "ModifiedDateTime");
            DropColumn("dbo.CommunicationRecipient", "CreatedDateTime");
            DropColumn("dbo.SiteDomain", "ModifiedByPersonAliasId");
            DropColumn("dbo.SiteDomain", "CreatedByPersonAliasId");
            DropColumn("dbo.SiteDomain", "ModifiedDateTime");
            DropColumn("dbo.SiteDomain", "CreatedDateTime");
            DropColumn("dbo.Site", "ModifiedByPersonAliasId");
            DropColumn("dbo.Site", "CreatedByPersonAliasId");
            DropColumn("dbo.Site", "ModifiedDateTime");
            DropColumn("dbo.Site", "CreatedDateTime");
            DropColumn("dbo.PageRoute", "ModifiedByPersonAliasId");
            DropColumn("dbo.PageRoute", "CreatedByPersonAliasId");
            DropColumn("dbo.PageRoute", "ModifiedDateTime");
            DropColumn("dbo.PageRoute", "CreatedDateTime");
            DropColumn("dbo.PageContext", "ModifiedByPersonAliasId");
            DropColumn("dbo.PageContext", "CreatedByPersonAliasId");
            DropColumn("dbo.PageContext", "ModifiedDateTime");
            DropColumn("dbo.Page", "ModifiedByPersonAliasId");
            DropColumn("dbo.Page", "CreatedByPersonAliasId");
            DropColumn("dbo.Page", "ModifiedDateTime");
            DropColumn("dbo.Page", "CreatedDateTime");
            DropColumn("dbo.Layout", "ModifiedByPersonAliasId");
            DropColumn("dbo.Layout", "CreatedByPersonAliasId");
            DropColumn("dbo.Layout", "ModifiedDateTime");
            DropColumn("dbo.Layout", "CreatedDateTime");
            DropColumn("dbo.BlockType", "ModifiedByPersonAliasId");
            DropColumn("dbo.BlockType", "CreatedByPersonAliasId");
            DropColumn("dbo.BlockType", "ModifiedDateTime");
            DropColumn("dbo.BlockType", "CreatedDateTime");
            DropColumn("dbo.Block", "ModifiedByPersonAliasId");
            DropColumn("dbo.Block", "CreatedByPersonAliasId");
            DropColumn("dbo.Block", "ModifiedDateTime");
            DropColumn("dbo.Block", "CreatedDateTime");
            DropColumn("dbo.Auth", "ModifiedByPersonAliasId");
            DropColumn("dbo.Auth", "CreatedByPersonAliasId");
            DropColumn("dbo.Auth", "ModifiedDateTime");
            DropColumn("dbo.Auth", "CreatedDateTime");
            DropColumn("dbo.AttributeValue", "ModifiedByPersonAliasId");
            DropColumn("dbo.AttributeValue", "CreatedByPersonAliasId");
            DropColumn("dbo.AttributeValue", "ModifiedDateTime");
            DropColumn("dbo.AttributeValue", "CreatedDateTime");
            DropColumn("dbo.Attribute", "ModifiedByPersonAliasId");
            DropColumn("dbo.Attribute", "CreatedByPersonAliasId");
            DropColumn("dbo.Attribute", "ModifiedDateTime");
            DropColumn("dbo.Attribute", "CreatedDateTime");
            DropColumn("dbo.Category", "ModifiedByPersonAliasId");
            DropColumn("dbo.Category", "CreatedByPersonAliasId");
            DropColumn("dbo.Category", "ModifiedDateTime");
            DropColumn("dbo.Category", "CreatedDateTime");
            DropColumn("dbo.Schedule", "ModifiedByPersonAliasId");
            DropColumn("dbo.Schedule", "CreatedByPersonAliasId");
            DropColumn("dbo.Schedule", "ModifiedDateTime");
            DropColumn("dbo.Schedule", "CreatedDateTime");
            DropColumn("dbo.UserLogin", "ModifiedByPersonAliasId");
            DropColumn("dbo.UserLogin", "CreatedByPersonAliasId");
            DropColumn("dbo.UserLogin", "ModifiedDateTime");
            DropColumn("dbo.UserLogin", "CreatedDateTime");
            DropColumn("dbo.BinaryFileData", "ModifiedByPersonAliasId");
            DropColumn("dbo.BinaryFileData", "CreatedByPersonAliasId");
            DropColumn("dbo.BinaryFileData", "ModifiedDateTime");
            DropColumn("dbo.BinaryFileData", "CreatedDateTime");
            DropColumn("dbo.BinaryFileType", "ModifiedByPersonAliasId");
            DropColumn("dbo.BinaryFileType", "CreatedByPersonAliasId");
            DropColumn("dbo.BinaryFileType", "ModifiedDateTime");
            DropColumn("dbo.BinaryFileType", "CreatedDateTime");
            DropColumn("dbo.BinaryFile", "ModifiedByPersonAliasId");
            DropColumn("dbo.BinaryFile", "CreatedByPersonAliasId");
            DropColumn("dbo.BinaryFile", "ModifiedDateTime");
            DropColumn("dbo.BinaryFile", "CreatedDateTime");
            DropColumn("dbo.PhoneNumber", "ModifiedByPersonAliasId");
            DropColumn("dbo.PhoneNumber", "CreatedByPersonAliasId");
            DropColumn("dbo.PhoneNumber", "ModifiedDateTime");
            DropColumn("dbo.PhoneNumber", "CreatedDateTime");
            DropColumn("dbo.EmailTemplate", "ModifiedByPersonAliasId");
            DropColumn("dbo.EmailTemplate", "CreatedByPersonAliasId");
            DropColumn("dbo.EmailTemplate", "ModifiedDateTime");
            DropColumn("dbo.EmailTemplate", "CreatedDateTime");
            DropColumn("dbo.Person", "ModifiedByPersonAliasId");
            DropColumn("dbo.Person", "CreatedByPersonAliasId");
            DropColumn("dbo.Person", "ModifiedDateTime");
            DropColumn("dbo.Person", "CreatedDateTime");
            DropColumn("dbo.GroupMember", "ModifiedByPersonAliasId");
            DropColumn("dbo.GroupMember", "CreatedByPersonAliasId");
            DropColumn("dbo.GroupMember", "ModifiedDateTime");
            DropColumn("dbo.GroupMember", "CreatedDateTime");
            DropColumn("dbo.GroupTypeRole", "ModifiedByPersonAliasId");
            DropColumn("dbo.GroupTypeRole", "CreatedByPersonAliasId");
            DropColumn("dbo.GroupTypeRole", "ModifiedDateTime");
            DropColumn("dbo.GroupTypeRole", "CreatedDateTime");
            DropColumn("dbo.GroupType", "ModifiedByPersonAliasId");
            DropColumn("dbo.GroupType", "CreatedByPersonAliasId");
            DropColumn("dbo.GroupType", "ModifiedDateTime");
            DropColumn("dbo.GroupType", "CreatedDateTime");
            DropColumn("dbo.Campus", "ModifiedByPersonAliasId");
            DropColumn("dbo.Campus", "CreatedByPersonAliasId");
            DropColumn("dbo.Campus", "ModifiedDateTime");
            DropColumn("dbo.Campus", "CreatedDateTime");
            DropColumn("dbo.Group", "ModifiedByPersonAliasId");
            DropColumn("dbo.Group", "CreatedByPersonAliasId");
            DropColumn("dbo.Group", "ModifiedDateTime");
            DropColumn("dbo.Group", "CreatedDateTime");
            DropColumn("dbo.GroupLocation", "ModifiedByPersonAliasId");
            DropColumn("dbo.GroupLocation", "CreatedByPersonAliasId");
            DropColumn("dbo.GroupLocation", "ModifiedDateTime");
            DropColumn("dbo.GroupLocation", "CreatedDateTime");
            DropColumn("dbo.Location", "ModifiedByPersonAliasId");
            DropColumn("dbo.Location", "CreatedByPersonAliasId");
            DropColumn("dbo.Location", "ModifiedDateTime");
            DropColumn("dbo.Location", "CreatedDateTime");
            DropColumn("dbo.FieldType", "ModifiedByPersonAliasId");
            DropColumn("dbo.FieldType", "CreatedByPersonAliasId");
            DropColumn("dbo.FieldType", "ModifiedDateTime");
            DropColumn("dbo.FieldType", "CreatedDateTime");
            DropColumn("dbo.DefinedType", "ModifiedByPersonAliasId");
            DropColumn("dbo.DefinedType", "CreatedByPersonAliasId");
            DropColumn("dbo.DefinedType", "ModifiedDateTime");
            DropColumn("dbo.DefinedType", "CreatedDateTime");
            DropColumn("dbo.DefinedValue", "ModifiedByPersonAliasId");
            DropColumn("dbo.DefinedValue", "CreatedByPersonAliasId");
            DropColumn("dbo.DefinedValue", "ModifiedDateTime");
            DropColumn("dbo.DefinedValue", "CreatedDateTime");
            DropColumn("dbo.Device", "ModifiedByPersonAliasId");
            DropColumn("dbo.Device", "CreatedByPersonAliasId");
            DropColumn("dbo.Device", "ModifiedDateTime");
            DropColumn("dbo.Device", "CreatedDateTime");
            DropColumn("dbo.Attendance", "ModifiedByPersonAliasId");
            DropColumn("dbo.Attendance", "CreatedByPersonAliasId");
            DropColumn("dbo.Attendance", "ModifiedDateTime");
            DropColumn("dbo.Attendance", "CreatedDateTime");
            CreateIndex("dbo.HtmlContent", "LastModifiedPersonId");
            CreateIndex("dbo.History", "CreatedByPersonId");
            AddForeignKey("dbo.HtmlContent", "LastModifiedPersonId", "dbo.Person", "Id");
            AddForeignKey("dbo.History", "CreatedByPersonId", "dbo.Person", "Id");
        }
    }
}
