//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** Determines the method for calculating the due date. */
export const DueDateCriteria = {
    /** A specific date. */
    Specific: 0,

    /** An offset of the class start date. */
    ClassStartOffset: 1,

    /** An offset of the class enrollment date. */
    EnrollmentOffset: 2,

    /** No calculation. */
    NoDate: 3
} as const;

/** Determines the method for calculating the due date. */
export const DueDateCriteriaDescription: Record<number, string> = {
    0: "Specific",

    1: "Class Start Offset",

    2: "Enrollment Offset",

    3: "No Date"
};

/** Determines the method for calculating the due date. */
export type DueDateCriteria = typeof DueDateCriteria[keyof typeof DueDateCriteria];
