
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//
using System.ComponentModel;
using System.ComponentModel.Composition;

namespace Rock.DataFilters.MarketingCampaignAdType
{
    /// <summary>
    /// MarketingCampaignAdType Name Filter
    /// </summary>
    [Description( "Filter Marketing Campaign Ad Types on Name" )]
    [Export( typeof( DataFilterComponent ) )]
    [ExportMetadata( "ComponentName", "MarketingCampaignAdType Name Filter" )]
    public partial class NameFilter : TextPropertyFilter
    {

        /// <summary>
        /// Gets the name of the filtered entity type.
        /// </summary>
        /// <value>
        /// The name of the filtered entity type.
        /// </value>
        public override string FilteredEntityTypeName
        {
            get { return "Rock.Model.MarketingCampaignAdType"; }
        }

        /// <summary>
        /// Gets the name of the column.
        /// </summary>
        /// <value>
        /// The name of the column.
        /// </value>
        public override string PropertyName
        {
            get { return "Name"; }
        }

    }
}
