//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import Entity from '../Entity';
import AttributeValue from './AttributeValueViewModel';
import { RockDateType } from '../../Util/RockDate';
import { Guid } from '../../Util/Guid';

export default interface Site extends Entity {
    id: number;
    additionalSettings: string | null;
    allowedFrameDomains: string | null;
    allowIndexing: boolean;
    attributes: Record<string, AttributeValue> | null;
    changePasswordPageId: number | null;
    changePasswordPageRouteId: number | null;
    communicationPageId: number | null;
    communicationPageRouteId: number | null;
    configurationMobilePhoneBinaryFileId: number | null;
    configurationMobileTabletBinaryFileId: number | null;
    defaultPageId: number | null;
    defaultPageRouteId: number | null;
    description: string | null;
    enabledForShortening: boolean;
    enableExclusiveRoutes: boolean;
    enableMobileRedirect: boolean;
    enablePageViews: boolean;
    errorPage: string | null;
    externalUrl: string | null;
    favIconBinaryFileId: number | null;
    googleAnalyticsCode: string | null;
    indexStartingLocation: string | null;
    isActive: boolean;
    isIndexEnabled: boolean;
    isSystem: boolean;
    latestVersionDateTime: RockDateType | null;
    loginPageId: number | null;
    loginPageRouteId: number | null;
    mobilePageId: number | null;
    name: string | null;
    pageHeaderContent: string | null;
    pageNotFoundPageId: number | null;
    pageNotFoundPageRouteId: number | null;
    redirectTablets: boolean;
    registrationPageId: number | null;
    registrationPageRouteId: number | null;
    requiresEncryption: boolean;
    siteLogoBinaryFileId: number | null;
    siteType: number;
    theme: string | null;
    thumbnailBinaryFileId: number | null;
    createdDateTime: RockDateType | null;
    modifiedDateTime: RockDateType | null;
    createdByPersonAliasId: number | null;
    modifiedByPersonAliasId: number | null;
    guid: Guid;
}
