//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

/** Represents a single package version. */
export type PackageVersionBag = {
    /** Date the version was added to the store. */
    date?: string | null;

    /** Release notes or description for the version. */
    description?: string | null;

    /** Display version of the date */
    displayDate?: string | null;

    /** URL to documentation specific to this version. */
    documentationUrl?: string | null;

    /** Unique identifier for the version. */
    id: number;

    /** Rating of the specific version */
    rating?: number | null;

    /** Pre-formatted Rock version requirement string. */
    requiredRockVersionDisplay?: string | null;

    /** Screenshots associated with this version. */
    screenshotURLs?: string[] | null;

    /** Human-readable version label (e.g., "1.2.0"). */
    versionLabel?: string | null;
};
