<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net9.0</TargetFrameworks>
    <PackageId>RockRMS.Rock.ViewModels</PackageId>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <RockWebPath>..\RockWeb</RockWebPath>
    <CopyToRockWeb>True</CopyToRockWeb>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rock.Enums\Rock.Enums.csproj" />
  </ItemGroup>

</Project>