//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the T4\Model.tt template.
//
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// THIS WORK IS LICENSED UNDER A CREATIVE COMMONS ATTRIBUTION-NONCOMMERCIAL-
// SHAREALIKE 3.0 UNPORTED LICENSE:
// http://creativecommons.org/licenses/by-nc-sa/3.0/
//
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using System.Runtime.Serialization;

using Rock.Data;

namespace Rock.Util
{
    /// <summary>
    /// Job POCO Entity.
    /// </summary>
    [Table( "utilJob" )]
    public partial class Job : ModelWithAttributes<Job>, IAuditable
    {
		/// <summary>
		/// Gets or sets the System.
		/// </summary>
		/// <value>
		/// Determines whether the job is a system job..
		/// </value>
		[DataMember]
		public bool IsSystem { get; set; }
		
		/// <summary>
		/// Gets or sets the Active.
		/// </summary>
		/// <value>
		/// Determines is the job is currently active..
		/// </value>
		[DataMember]
		public bool? IsActive { get; set; }
		
		/// <summary>
		/// Gets or sets the Name.
		/// </summary>
		/// <value>
		/// Friendly name for the job..
		/// </value>
		[Required]
		[MaxLength( 100 )]
		[DataMember]
		public string Name { get; set; }
		
		/// <summary>
		/// Gets or sets the Description.
		/// </summary>
		/// <value>
		/// Notes about the job..
		/// </value>
		[MaxLength( 500 )]
		[DataMember]
		public string Description { get; set; }
		
		/// <summary>
		/// Gets or sets the Assemby.
		/// </summary>
		/// <value>
		/// Assembly (.dll) that contains the job class..
		/// </value>
		[MaxLength( 100 )]
		[DataMember]
		public string Assemby { get; set; }
		
		/// <summary>
		/// Gets or sets the Class.
		/// </summary>
		/// <value>
		/// The class name of the job to run..
		/// </value>
		[Required]
		[MaxLength( 100 )]
		[DataMember]
		public string Class { get; set; }
		
		/// <summary>
		/// Gets or sets the Cron Expression.
		/// </summary>
		/// <value>
		/// The cron expression that is used to determine the schedule of the job (see http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger for syntax.).
		/// </value>
		[Required]
		[MaxLength( 120 )]
		[DataMember]
		public string CronExpression { get; set; }
		
		/// <summary>
		/// Gets or sets the Last Successful Run.
		/// </summary>
		/// <value>
		/// Date and time the job last completed successfully..
		/// </value>
		[DataMember]
		public DateTime? LastSuccessfulRun { get; set; }
		
		/// <summary>
		/// Gets or sets the Last Run Date.
		/// </summary>
		/// <value>
		/// Last date and time the job attempted to run..
		/// </value>
		[DataMember]
		public DateTime? LastRunDate { get; set; }
		
		/// <summary>
		/// Gets or sets the Last Run Duration.
		/// </summary>
		/// <value>
		/// Number of seconds that the last job took to finish..
		/// </value>
		[DataMember]
		public int? LastRunDuration { get; set; }
		
		/// <summary>
		/// Gets or sets the Last Status.
		/// </summary>
		/// <value>
		/// The completion status from the last time the job was run (valid values 'Success', 'Exception', 'Error Loading Job')..
		/// </value>
		[MaxLength( 50 )]
		[DataMember]
		public string LastStatus { get; set; }
		
		/// <summary>
		/// Gets or sets the Last Status Message.
		/// </summary>
		/// <value>
		/// Message from the last run.  Usually used to store the exception message..
		/// </value>
		[DataMember]
		public string LastStatusMessage { get; set; }
		
		/// <summary>
		/// Gets or sets the Last Run Scheduler Name.
		/// </summary>
		/// <value>
		/// Name of the scheduler that the job ran under.  This is used to determine if a job ran in IIS or the Windows service..
		/// </value>
		[MaxLength( 40 )]
		[DataMember]
		public string LastRunSchedulerName { get; set; }
		
		/// <summary>
		/// Gets or sets the Notification Emails.
		/// </summary>
		/// <value>
		/// Email addresses (separated with commas) to be used for notification..
		/// </value>
		[MaxLength( 1000 )]
		[DataMember]
		public string NotificationEmails { get; set; }
		
		/// <summary>
		/// Gets or sets the Notification Status.
		/// </summary>
		/// <value>
		/// States that should be used to determine when to notify (valid values = All = 1, Success = 2, Error = 3, None = 4  Enum[JobNotificationStatus].
		/// </value>
		[Required]
		[DataMember]
		internal int NotificationStatusInternal { get; set; }

		/// <summary>
		/// Gets or sets the Notification Status.
		/// </summary>
		/// <value>
		/// States that should be used to determine when to notify (valid values = All = 1, Success = 2, Error = 3, None = 4  Enum[JobNotificationStatus].
		/// </value>
		[NotMapped]
		public JobNotificationStatus NotificationStatus
		{
			get { return (JobNotificationStatus)this.NotificationStatusInternal; }
			set { this.NotificationStatusInternal = (int)value; }
		}
		
		/// <summary>
		/// Gets or sets the Created Date Time.
		/// </summary>
		/// <value>
		/// Created Date Time.
		/// </value>
		[DataMember]
		public DateTime? CreatedDateTime { get; set; }
		
		/// <summary>
		/// Gets or sets the Modified Date Time.
		/// </summary>
		/// <value>
		/// Modified Date Time.
		/// </value>
		[DataMember]
		public DateTime? ModifiedDateTime { get; set; }
		
		/// <summary>
		/// Gets or sets the Created By Person Id.
		/// </summary>
		/// <value>
		/// Created By Person Id.
		/// </value>
		[DataMember]
		public int? CreatedByPersonId { get; set; }
		
		/// <summary>
		/// Gets or sets the Modified By Person Id.
		/// </summary>
		/// <value>
		/// Modified By Person Id.
		/// </value>
		[DataMember]
		public int? ModifiedByPersonId { get; set; }
		
		/// <summary>
        /// Gets a Data Transfer Object (lightweight) version of this object.
        /// </summary>
        /// <value>
        /// A <see cref="Rock.Util.DTO.Job"/> object.
        /// </value>
		public Rock.Util.DTO.Job DataTransferObject
		{
			get 
			{ 
				Rock.Util.DTO.Job dto = new Rock.Util.DTO.Job();
				dto.Id = this.Id;
				dto.Guid = this.Guid;
				dto.IsSystem = this.IsSystem;
				dto.IsActive = this.IsActive;
				dto.Name = this.Name;
				dto.Description = this.Description;
				dto.Assemby = this.Assemby;
				dto.Class = this.Class;
				dto.CronExpression = this.CronExpression;
				dto.LastSuccessfulRun = this.LastSuccessfulRun;
				dto.LastRunDate = this.LastRunDate;
				dto.LastRunDuration = this.LastRunDuration;
				dto.LastStatus = this.LastStatus;
				dto.LastStatusMessage = this.LastStatusMessage;
				dto.LastRunSchedulerName = this.LastRunSchedulerName;
				dto.NotificationEmails = this.NotificationEmails;
				dto.NotificationStatus = this.NotificationStatusInternal;
				dto.CreatedDateTime = this.CreatedDateTime;
				dto.ModifiedDateTime = this.ModifiedDateTime;
				dto.CreatedByPersonId = this.CreatedByPersonId;
				dto.ModifiedByPersonId = this.ModifiedByPersonId;
				return dto; 
			}
		}

        /// <summary>
        /// Gets the auth entity.
        /// </summary>
		[NotMapped]
		public override string AuthEntity { get { return "Util.Job"; } }
        
		/// <summary>
        /// Gets or sets the Created By Person.
        /// </summary>
        /// <value>
        /// A <see cref="CRM.Person"/> object.
        /// </value>
		public virtual CRM.Person CreatedByPerson { get; set; }
        
		/// <summary>
        /// Gets or sets the Modified By Person.
        /// </summary>
        /// <value>
        /// A <see cref="CRM.Person"/> object.
        /// </value>
		public virtual CRM.Person ModifiedByPerson { get; set; }

    }
    /// <summary>
    /// Job Configuration class.
    /// </summary>
    public partial class JobConfiguration : EntityTypeConfiguration<Job>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobConfiguration"/> class.
        /// </summary>
        public JobConfiguration()
        {
			this.Property( p => p.NotificationStatusInternal ).HasColumnName( "NotificationStatus" );
			this.HasOptional( p => p.CreatedByPerson ).WithMany().HasForeignKey( p => p.CreatedByPersonId ).WillCascadeOnDelete(false);
			this.HasOptional( p => p.ModifiedByPerson ).WithMany().HasForeignKey( p => p.ModifiedByPersonId ).WillCascadeOnDelete(false);
		}
    }

    /// <summary>
    /// Job notification status
    /// </summary>
    public enum JobNotificationStatus
    {
        /// <summary>
        /// Notify on all status
        /// </summary>
        All = 1,

        /// <summary>
        /// Notify when successful
        /// </summary>
        /// 
        Success = 2,

        /// <summary>
        /// Notify when an error occurs
        /// </summary>
        Error = 3,

        /// <summary>
        /// Notify when a warning occurs
        /// </summary>
        None = 4
    }
}
